cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "CHECK_BINARY is required")
endif()
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
function(reject path expected)
  execute_process(COMMAND "${host}" "${path}" RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT _err MATCHES "${expected}")
    message(FATAL_ERROR "Expected ${expected}, got ${_result}: ${_out}${_err}")
  endif()
endfunction()
get_filename_component(_modules "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
set(_args)
if(CHECK_COMPILER)
  list(APPEND _args "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}")
endif()
if(NOT CHECK_GENERATOR)
  set(CHECK_GENERATOR Ninja)
endif()
set(_root "${CHECK_BINARY}/delivery")
file(REMOVE_RECURSE "${_root}")
set(_external "${_root}/external")
set(_build "${_root}/build")
run("${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/delivery/external" -B "${_external}"
  -G "${CHECK_GENERATOR}" -DCMAKE_BUILD_TYPE=Release ${_args})
run("${CMAKE_COMMAND}" --build "${_external}" --config Release)
include("${_external}/external-Release.cmake")
run("${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/delivery" -B "${_build}"
  -G "${CHECK_GENERATOR}" -DCMAKE_BUILD_TYPE=Release ${_args}
  "-DBOILERPLATE_MODULE_DIR=${_modules}" "-DEXTERNAL_LIBRARY=${EXTERNAL_LIBRARY}" "-DEXTERNAL_IMPLIB=${EXTERNAL_IMPLIB}"
  "-DEXTERNAL_LEAF=${EXTERNAL_LEAF}" "-DEXTERNAL_LEAF_IMPLIB=${EXTERNAL_LEAF_IMPLIB}")
run("${CMAKE_COMMAND}" --build "${_build}" --config Release --parallel 2)
include("${_build}/paths-Release.cmake")
if(NOT host_role STREQUAL "HOST" OR NOT "example_plugin" IN_LIST hosted_plugins)
  message(FATAL_ERROR "Plugin host graph is wrong: role=${host_role}, plugins=${hosted_plugins}")
endif()
run("${host}" "${plugin}")
reject("${wrong}" "Incompatible plugin ABI")
reject("${empty}" "Missing plugin entry point")
reject("${_root}/missing-plugin" "Cannot load plugin")
run("${CMAKE_COMMAND}" --install "${_build}" --config Release --prefix "${_root}/prefix" --component Runtime)
run("${CMAKE_CPACK_COMMAND}" --config "${_build}/CPackConfig.cmake" -G TGZ -C Release -B "${_root}/packages")
file(RENAME "${_root}/prefix" "${_root}/relocated")
# Remove both original library locations: a successful launch must use the install.
file(REMOVE_RECURSE "${_build}" "${_external}")
set(_prefix "${_root}/relocated")
run("${CMAKE_COMMAND}" -E env --unset=LD_LIBRARY_PATH --unset=DYLD_LIBRARY_PATH
  "${_prefix}/${installed_host}" "${_prefix}/${installed_plugin}" "${_prefix}/${installed_plugin}" "${_prefix}/${resource}")
message(STATUS "Plugin ABI rejection, reload, runtime dependencies, resources and relocated install passed (${CHECK_GENERATOR})")
