include_guard(GLOBAL)

function(_boilerplate_collect_policy_args output policies policy_options)
  set(_args)
  if(policies)
    list(APPEND _args POLICIES ${policies})
  endif()
  if(policy_options)
    list(APPEND _args POLICY_OPTIONS ${policy_options})
  endif()
  set(${output} "${_args}" PARENT_SCOPE)
endfunction()

# Examples are executable workloads, not a second target model. This helper
# composes the existing executable/scenario/check/PGO primitives and provides a
# common build aggregate. Long execution remains explicit through run_<name> or
# run_group_examples; the default build only compiles the example binaries.
function(boilerplate_add_example target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "SMOKE;PGO;INSTALL"
    "TIMEOUT;REPEATS;WARMUP;WORKING_DIRECTORY"
    "SOURCES;LIBRARIES;ARGS;SMOKE_ARGS;PGO_ARGS;ENVIRONMENT;LABELS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_example requires SOURCES; invalid arguments for ${target}")
  endif()
  if(ARG_SMOKE_ARGS AND NOT ARG_SMOKE)
    message(FATAL_ERROR "boilerplate_add_example(${target}): SMOKE_ARGS requires SMOKE")
  endif()
  if(ARG_PGO_ARGS AND NOT ARG_PGO)
    message(FATAL_ERROR "boilerplate_add_example(${target}): PGO_ARGS requires PGO")
  endif()

  _boilerplate_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  set(_executable_options)
  if(ARG_INSTALL)
    list(APPEND _executable_options INSTALL)
  endif()
  boilerplate_add_executable(${target} ${_executable_options}
    SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_policy_args})

  if(NOT TARGET boilerplate_examples)
    add_custom_target(boilerplate_examples)
  endif()
  add_dependencies(boilerplate_examples ${target})

  set(_scenario_options TARGET ${target} GROUP examples ARGS ${ARG_ARGS}
    ENVIRONMENT ${ARG_ENVIRONMENT} LABELS example ${ARG_LABELS})
  foreach(_field IN ITEMS TIMEOUT REPEATS WARMUP WORKING_DIRECTORY)
    if(DEFINED ARG_${_field} AND NOT "${ARG_${_field}}" STREQUAL "")
      list(APPEND _scenario_options ${_field} "${ARG_${_field}}")
    endif()
  endforeach()
  if(ARG_SMOKE)
    list(APPEND _scenario_options SMOKE SMOKE_ARGS ${ARG_SMOKE_ARGS})
  endif()
  if(ARG_PGO)
    list(APPEND _scenario_options PGO PGO_ARGS ${ARG_PGO_ARGS})
  endif()
  boilerplate_add_scenario(${target} ${_scenario_options})
endfunction()

function(boilerplate_benchmark_enabled output target group)
  string(MAKE_C_IDENTIFIER "${target}" _key)
  string(TOUPPER "${_key}" _key)
  option(BOILERPLATE_BUILD_${_key} "Build benchmark ${target}" ON)
  set(_enabled FALSE)
  if(BOILERPLATE_BUILD_${_key} AND ("all" IN_LIST BOILERPLATE_BENCHMARK_GROUPS OR
      "${group}" IN_LIST BOILERPLATE_BENCHMARK_GROUPS))
    set(_enabled TRUE)
  endif()
  set(${output} "${_enabled}" PARENT_SCOPE)
endfunction()

function(boilerplate_add_benchmark target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "GROUP;REPEATS;WARMUP" "SOURCES;LIBRARIES;ARGS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_benchmark requires SOURCES; invalid arguments")
  endif()
  if(NOT ARG_GROUP)
    set(ARG_GROUP custom)
  endif()
  boilerplate_benchmark_enabled(_enabled "${target}" "${ARG_GROUP}")
  if(NOT _enabled)
    return()
  endif()
  _boilerplate_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  boilerplate_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_policy_args})
  foreach(_aggregate IN ITEMS boilerplate_benchmarks benchmarks_${ARG_GROUP})
    if(NOT TARGET ${_aggregate})
      add_custom_target(${_aggregate})
    endif()
    add_dependencies(${_aggregate} ${target})
  endforeach()
  set(_run_options)
  foreach(_field IN ITEMS REPEATS WARMUP)
    if(DEFINED ARG_${_field})
      list(APPEND _run_options ${_field} "${ARG_${_field}}")
    endif()
  endforeach()
  boilerplate_add_scenario(${target} TARGET ${target} GROUP ${ARG_GROUP} ARGS ${ARG_ARGS} ${_run_options})
endfunction()

function(boilerplate_add_test target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "TIMEOUT;WORKING_DIRECTORY" "SOURCES;LIBRARIES;ARGS;LABELS;ENVIRONMENT;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_test requires SOURCES; invalid arguments")
  endif()
  if(NOT BUILD_TESTING)
    return()
  endif()
  _boilerplate_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  boilerplate_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_policy_args})
  set(_optional)
  foreach(_field IN ITEMS TIMEOUT WORKING_DIRECTORY)
    if(ARG_${_field})
      list(APPEND _optional ${_field} "${ARG_${_field}}")
    endif()
  endforeach()
  boilerplate_register_check(${target} ${target} ARGS ${ARG_ARGS}
    LABELS unit ${ARG_LABELS} ENVIRONMENT ${ARG_ENVIRONMENT} ${_optional})
endfunction()

function(boilerplate_add_google_benchmark target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "GROUP" "SOURCES;LIBRARIES;ARGS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "Invalid Google Benchmark arguments")
  endif()
  if(NOT ARG_GROUP)
    set(ARG_GROUP google)
  endif()
  boilerplate_benchmark_enabled(_enabled "${target}" "${ARG_GROUP}")
  if(NOT _enabled)
    return()
  endif()
  boilerplate_require_google_benchmark()
  file(MAKE_DIRECTORY "${BOILERPLATE_RESULTS_DIR}/google")
  _boilerplate_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  boilerplate_add_benchmark(${target} GROUP ${ARG_GROUP} REPEATS 1 WARMUP 0 SOURCES ${ARG_SOURCES}
    LIBRARIES ${ARG_LIBRARIES} benchmark::benchmark_main ${_policy_args}
    ARGS --benchmark_repetitions=5 --benchmark_out_format=json
      "--benchmark_out=${BOILERPLATE_RESULTS_DIR}/google/${target}-$<CONFIG>.json" ${ARG_ARGS})
  # Listing validates registration without timing. Bounded execution is explicit PGO.
  boilerplate_register_check(${target}_registration ${target}
    ARGS --benchmark_list_tests=true LABELS benchmark smoke google)
  boilerplate_pgo_workload(${target} --benchmark_min_time=1x --benchmark_repetitions=1)
endfunction()

function(boilerplate_add_googletest target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "OWN_MAIN" "" "SOURCES;LIBRARIES;LABELS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "Invalid GoogleTest arguments")
  endif()
  if(NOT BUILD_TESTING)
    return()
  endif()
  boilerplate_require_googletest()
  set(_main GTest::gtest_main)
  if(ARG_OWN_MAIN)
    set(_main GTest::gtest)
  endif()
  _boilerplate_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  boilerplate_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_main} ${_policy_args})
  include(GoogleTest)
  gtest_discover_tests(${target} TEST_PREFIX "${target}." DISCOVERY_MODE PRE_TEST
    PROPERTIES TIMEOUT 30 LABELS "unit;google;${ARG_LABELS}")
  # Aggregate dependency without a duplicate test running the whole binary.
  if(NOT TARGET boilerplate_tests)
    add_custom_target(boilerplate_tests)
    add_custom_target(boilerplate_check
      COMMAND ${CMAKE_CTEST_COMMAND} --test-dir "${CMAKE_BINARY_DIR}" -C "$<CONFIG>" --output-on-failure
      DEPENDS boilerplate_tests USES_TERMINAL VERBATIM)
  endif()
  add_dependencies(boilerplate_tests ${target})
endfunction()

function(boilerplate_add_property_test target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "BACKEND" "SOURCES;LIBRARIES;LABELS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_property_test requires SOURCES")
  endif()
  if(NOT BUILD_TESTING)
    return()
  endif()
  if(NOT ARG_BACKEND)
    set(ARG_BACKEND "${BOILERPLATE_PBT_BACKEND}")
  endif()
  if(NOT ARG_BACKEND STREQUAL "rapidcheck")
    message(FATAL_ERROR "Unsupported property-testing backend: ${ARG_BACKEND}")
  endif()
  boilerplate_require_googletest()
  boilerplate_require_rapidcheck()
  _boilerplate_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  boilerplate_add_executable(${target} SOURCES ${ARG_SOURCES}
    LIBRARIES ${ARG_LIBRARIES} rapidcheck rapidcheck_gtest GTest::gtest_main ${_policy_args})
  include(GoogleTest)
  gtest_discover_tests(${target} TEST_PREFIX "${target}." DISCOVERY_MODE PRE_TEST
    PROPERTIES TIMEOUT 30 LABELS "unit;property;pbt;rapidcheck;${ARG_LABELS}")
  if(NOT TARGET boilerplate_tests)
    add_custom_target(boilerplate_tests)
  endif()
  add_dependencies(boilerplate_tests ${target})
  set_property(GLOBAL APPEND PROPERTY BOILERPLATE_PROPERTY_TEST_TARGETS ${target})
endfunction()

function(_boilerplate_fuzz_sanitizer_flags output)
  if(BOILERPLATE_FUZZ_SANITIZER STREQUAL "none")
    set(_flags)
  elseif(BOILERPLATE_FUZZ_SANITIZER STREQUAL "address")
    set(_flags -fsanitize=address)
  elseif(BOILERPLATE_FUZZ_SANITIZER STREQUAL "undefined")
    set(_flags -fsanitize=undefined)
  elseif(BOILERPLATE_FUZZ_SANITIZER STREQUAL "address-undefined")
    set(_flags -fsanitize=address,undefined)
  else()
    message(FATAL_ERROR "Unsupported BOILERPLATE_FUZZ_SANITIZER=${BOILERPLATE_FUZZ_SANITIZER}")
  endif()
  set(${output} "${_flags}" PARENT_SCOPE)
endfunction()

function(_boilerplate_prepare_fuzz_dirs target corpus_arg output_corpus output_artifacts)
  if(corpus_arg)
    get_filename_component(_corpus "${corpus_arg}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  else()
    set(_corpus "${CMAKE_CURRENT_BINARY_DIR}/${target}-corpus")
  endif()
  set(_artifacts "${CMAKE_CURRENT_BINARY_DIR}/${target}-artifacts")
  file(MAKE_DIRECTORY "${_corpus}" "${_artifacts}")
  if(NOT EXISTS "${_corpus}/boilerplate-seed")
    file(WRITE "${_corpus}/boilerplate-seed" "0")
  endif()
  set(${output_corpus} "${_corpus}" PARENT_SCOPE)
  set(${output_artifacts} "${_artifacts}" PARENT_SCOPE)
endfunction()

# One harness API, multiple engines. The harness source always exports
# LLVMFuzzerTestOneInput(). AFL++ and honggfuzz require their compiler wrapper
# to be selected before project() (normally through a configure preset).
function(boilerplate_add_fuzzer target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "BACKEND;CORPUS;DICTIONARY;RUN_SECONDS;MAX_LEN"
    "SOURCES;LIBRARIES;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_fuzzer requires SOURCES")
  endif()
  if(NOT ARG_BACKEND)
    set(ARG_BACKEND "${BOILERPLATE_FUZZ_BACKEND}")
  endif()
  if(NOT ARG_BACKEND MATCHES "^(libfuzzer|aflpp|honggfuzz)$")
    message(FATAL_ERROR "Unsupported fuzz backend: ${ARG_BACKEND}")
  endif()
  if(NOT ARG_RUN_SECONDS)
    set(ARG_RUN_SECONDS "${BOILERPLATE_FUZZ_RUNTIME}")
  endif()
  _boilerplate_prepare_fuzz_dirs(${target} "${ARG_CORPUS}" _corpus _artifacts)
  _boilerplate_fuzz_sanitizer_flags(_san_flags)

  set(_policies minimal frame-pointers ${ARG_POLICIES})
  set(_policy_options SANITIZER none PGO_MODE none LTO_MODE none ${ARG_POLICY_OPTIONS})
  boilerplate_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES}
    POLICIES ${_policies} POLICY_OPTIONS ${_policy_options})
  target_compile_definitions(${target} PRIVATE FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1)

  get_filename_component(_compiler_name "${CMAKE_CXX_COMPILER}" NAME)
  set(_run_target "fuzz_${target}")
  set(_smoke_name "${target}")
  set(_dictionary_arg)

  if(ARG_BACKEND STREQUAL "libfuzzer")
    if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      message(FATAL_ERROR "libFuzzer backend requires GNU-style Clang/AppleClang")
    endif()
    target_compile_options(${target} PRIVATE -fsanitize=fuzzer-no-link ${_san_flags})
    target_link_options(${target} PRIVATE -fsanitize=fuzzer ${_san_flags})
    set(_run_args "${_corpus}" "-max_total_time=${ARG_RUN_SECONDS}" "-artifact_prefix=${_artifacts}/")
    set(_smoke_args "${_corpus}" -runs=1 "-artifact_prefix=${_artifacts}/")
    if(ARG_MAX_LEN)
      list(APPEND _run_args "-max_len=${ARG_MAX_LEN}")
      list(APPEND _smoke_args "-max_len=${ARG_MAX_LEN}")
    endif()
    if(ARG_DICTIONARY)
      get_filename_component(_dict "${ARG_DICTIONARY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      list(APPEND _run_args "-dict=${_dict}")
      list(APPEND _smoke_args "-dict=${_dict}")
    endif()
    add_custom_target(${_run_target}
      COMMAND "$<TARGET_FILE:${target}>" ${_run_args}
      DEPENDS ${target} USES_TERMINAL VERBATIM)
    if(BUILD_TESTING)
      boilerplate_register_check(${_smoke_name} ${target} ARGS ${_smoke_args}
        LABELS fuzz smoke libfuzzer TIMEOUT 30)
    endif()

  elseif(ARG_BACKEND STREQUAL "aflpp")
    if(NOT _compiler_name MATCHES "^afl-")
      message(FATAL_ERROR
        "AFL++ backend requires configuring CMAKE_CXX_COMPILER to an AFL++ wrapper (for example afl-clang-fast++ or afl-clang-lto++).")
    endif()
    find_program(BOILERPLATE_AFL_FUZZ NAMES afl-fuzz REQUIRED)
    find_program(BOILERPLATE_AFL_SHOWMAP NAMES afl-showmap REQUIRED)
    # AFL++ recognizes -fsanitize=fuzzer and injects its libFuzzer-compatible
    # persistent driver for LLVMFuzzerTestOneInput().
    target_compile_options(${target} PRIVATE -fsanitize=fuzzer-no-link ${_san_flags})
    target_link_options(${target} PRIVATE -fsanitize=fuzzer ${_san_flags})
    file(MAKE_DIRECTORY "${_artifacts}/afl" "${_artifacts}/afl-showmap")
    set(_afl_args -i "${_corpus}" -o "${_artifacts}/afl" -V "${ARG_RUN_SECONDS}")
    if(ARG_MAX_LEN)
      list(APPEND _afl_args -G "${ARG_MAX_LEN}")
    endif()
    if(ARG_DICTIONARY)
      get_filename_component(_dict "${ARG_DICTIONARY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      list(APPEND _afl_args -x "${_dict}")
    endif()
    add_custom_target(${_run_target}
      COMMAND "${CMAKE_COMMAND}" -E env AFL_NO_UI=1
        "${BOILERPLATE_AFL_FUZZ}" ${_afl_args} -- "$<TARGET_FILE:${target}>"
      DEPENDS ${target} USES_TERMINAL VERBATIM)
    if(BUILD_TESTING)
      add_test(NAME ${_smoke_name}
        COMMAND "${BOILERPLATE_AFL_SHOWMAP}" -q -i "${_corpus}"
          -o "${_artifacts}/afl-showmap" -- "$<TARGET_FILE:${target}>" @@)
      set_tests_properties(${_smoke_name} PROPERTIES LABELS "fuzz;smoke;aflpp" TIMEOUT 30)
    endif()

  else()
    if(NOT _compiler_name MATCHES "^hfuzz-")
      message(FATAL_ERROR
        "honggfuzz backend requires configuring CMAKE_CXX_COMPILER to hfuzz-clang++/hfuzz-g++ before project().")
    endif()
    find_program(BOILERPLATE_HONGGFUZZ NAMES honggfuzz REQUIRED)
    # hfuzz-* adds sanitizer coverage and libhfuzz, including the persistent
    # LLVMFuzzerTestOneInput driver. Keep optional ASan/UBSan target-scoped.
    target_compile_options(${target} PRIVATE ${_san_flags})
    target_link_options(${target} PRIVATE ${_san_flags})
    file(MAKE_DIRECTORY "${_artifacts}/honggfuzz" "${_artifacts}/honggfuzz-smoke")
    set(_hf_args -P -i "${_corpus}" --workspace "${_artifacts}/honggfuzz"
      --run_time "${ARG_RUN_SECONDS}")
    if(ARG_MAX_LEN)
      list(APPEND _hf_args --max_file_size "${ARG_MAX_LEN}")
    endif()
    if(ARG_DICTIONARY)
      get_filename_component(_dict "${ARG_DICTIONARY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      list(APPEND _hf_args -w "${_dict}")
    endif()
    add_custom_target(${_run_target}
      COMMAND "${BOILERPLATE_HONGGFUZZ}" ${_hf_args} -- "$<TARGET_FILE:${target}>"
      DEPENDS ${target} USES_TERMINAL VERBATIM)
    if(BUILD_TESTING)
      add_test(NAME ${_smoke_name}
        COMMAND "${BOILERPLATE_HONGGFUZZ}" -P -i "${_corpus}"
          --workspace "${_artifacts}/honggfuzz-smoke" --run_time 1 --iterations 1
          -- "$<TARGET_FILE:${target}>")
      set_tests_properties(${_smoke_name} PROPERTIES LABELS "fuzz;smoke;honggfuzz" TIMEOUT 30)
    endif()
  endif()

  set_property(GLOBAL APPEND PROPERTY BOILERPLATE_FUZZ_TARGETS ${target})
  set_property(GLOBAL APPEND PROPERTY BOILERPLATE_FUZZ_RUN_TARGETS ${_run_target})
  if(BUILD_TESTING)
    set_property(GLOBAL APPEND PROPERTY BOILERPLATE_FUZZ_SMOKE_TESTS ${_smoke_name})
  endif()
endfunction()

# Google FuzzTest is a separate typed/domain property-fuzzing model. Unit mode
# runs as ordinary GTest; fuzzing and libFuzzer compatibility mode are explicit
# build-wide FuzzTest modes but instrumentation stays scoped to the owned target.
function(boilerplate_add_fuzztest target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "MODE;FUZZ_TEST"
    "SOURCES;LIBRARIES;LABELS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_fuzztest requires SOURCES")
  endif()
  if(NOT BUILD_TESTING)
    return()
  endif()
  if(NOT ARG_MODE)
    set(ARG_MODE "${BOILERPLATE_FUZZTEST_MODE}")
  endif()
  boilerplate_require_fuzztest(MODE "${ARG_MODE}")
  set(_policies minimal frame-pointers ${ARG_POLICIES})
  set(_policy_options SANITIZER none PGO_MODE none LTO_MODE none ${ARG_POLICY_OPTIONS})
  boilerplate_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES}
    POLICIES ${_policies} POLICY_OPTIONS ${_policy_options})
  link_fuzztest(${target})

  if(NOT ARG_MODE STREQUAL "unit")
    target_compile_options(${target} PRIVATE -g -UNDEBUG -fsanitize=address
      -fsanitize-coverage=inline-8bit-counters -fsanitize-coverage=trace-cmp)
    target_compile_definitions(${target} PRIVATE
      FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 ADDRESS_SANITIZER=1)
    target_link_options(${target} PRIVATE -fsanitize=address)
    if(ARG_MODE STREQUAL "libfuzzer")
      target_compile_options(${target} PRIVATE -fsanitize=fuzzer-no-link)
      target_compile_definitions(${target} PRIVATE FUZZTEST_COMPATIBILITY_MODE=1)
    endif()
  endif()

  include(GoogleTest)
  gtest_discover_tests(${target} TEST_PREFIX "${target}." DISCOVERY_MODE PRE_TEST
    PROPERTIES TIMEOUT 30 LABELS "unit;property;fuzztest;${ARG_LABELS}")
  if(NOT TARGET boilerplate_tests)
    add_custom_target(boilerplate_tests)
  endif()
  add_dependencies(boilerplate_tests ${target})
  set_property(GLOBAL APPEND PROPERTY BOILERPLATE_FUZZTEST_TARGETS ${target})

  if(ARG_FUZZ_TEST AND NOT ARG_MODE STREQUAL "unit")
    set(_run_target "fuzz_${target}")
    add_custom_target(${_run_target}
      COMMAND "$<TARGET_FILE:${target}>" "--fuzz=${ARG_FUZZ_TEST}"
      DEPENDS ${target} USES_TERMINAL VERBATIM)
    set_property(GLOBAL APPEND PROPERTY BOILERPLATE_FUZZ_RUN_TARGETS ${_run_target})
  endif()
endfunction()
# Each registration becomes its own dependency, so calls from different
# subdirectories compose without directory-local command-list state.
function(boilerplate_pgo_workload target)
  if(NOT TARGET ${target})
    message(FATAL_ERROR "PGO workload target does not exist: ${target}")
  endif()
  boilerplate_get_target_setting(${target} PGO_MODE _pgo_mode)
  if(NOT _pgo_mode STREQUAL "generate")
    return()
  endif()
  boilerplate_get_target_setting(${target} PGO_DIR _pgo_dir)
  get_property(_registered_pgo_dir GLOBAL PROPERTY BOILERPLATE_REGISTERED_PGO_DIR)
  if(_registered_pgo_dir AND NOT _registered_pgo_dir STREQUAL _pgo_dir)
    message(FATAL_ERROR "PGO workloads in one build must share PGO_DIR: ${_registered_pgo_dir} vs ${_pgo_dir}")
  endif()
  set_property(GLOBAL PROPERTY BOILERPLATE_REGISTERED_PGO_DIR "${_pgo_dir}")
  get_target_property(_type ${target} TYPE)
  if(NOT _type STREQUAL "EXECUTABLE")
    message(FATAL_ERROR "PGO workload must be an executable: ${target}")
  endif()
  if(NOT TARGET boilerplate_pgo_train)
    add_custom_target(boilerplate_pgo_train)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      get_filename_component(_compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
      string(REGEX MATCH "^[0-9]+" _compiler_major "${CMAKE_CXX_COMPILER_VERSION}")
      find_program(BOILERPLATE_LLVM_PROFDATA NAMES llvm-profdata-${_compiler_major} llvm-profdata
        HINTS "${_compiler_dir}" REQUIRED)
      set(BOILERPLATE_PGO_MERGED_PROFILE "${_pgo_dir}/merged.profdata"
        CACHE FILEPATH "Output of boilerplate_pgo_merge")
      set(_merge ${CMAKE_COMMAND} "-DPROFILE_DIR=${_pgo_dir}"
        "-DPROFILE_OUTPUT=${BOILERPLATE_PGO_MERGED_PROFILE}"
        "-DPROFDATA=${BOILERPLATE_LLVM_PROFDATA}"
        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmark/MergeProfiles.cmake")
      add_custom_target(boilerplate_pgo_merge_only COMMAND ${_merge} USES_TERMINAL VERBATIM)
      add_custom_target(boilerplate_pgo_merge COMMAND ${_merge}
        DEPENDS boilerplate_pgo_train USES_TERMINAL VERBATIM)
    endif()
  endif()
  get_property(_count GLOBAL PROPERTY BOILERPLATE_PGO_WORKLOAD_COUNT)
  if(NOT _count)
    set(_count 0)
  endif()
  math(EXPR _next "${_count} + 1")
  set_property(GLOBAL PROPERTY BOILERPLATE_PGO_WORKLOAD_COUNT "${_next}")
  set(_workload "boilerplate_pgo_workload_${_next}")
  set(_content)
  boilerplate_append_setting(_content EXECUTABLE "$<TARGET_FILE:${target}>")
  boilerplate_append_setting(_content ARGS "${ARGN}")
  boilerplate_append_setting(_content ENVIRONMENT "${_boilerplate_pgo_environment}")
  if(NOT _boilerplate_pgo_workdir)
    set(_boilerplate_pgo_workdir "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
  if(NOT _boilerplate_pgo_timeout)
    set(_boilerplate_pgo_timeout "${BOILERPLATE_RUN_TIMEOUT}")
  endif()
  boilerplate_append_setting(_content WORKING_DIRECTORY "${_boilerplate_pgo_workdir}")
  boilerplate_append_setting(_content TIMEOUT "${_boilerplate_pgo_timeout}")
  boilerplate_append_setting(_content REPEATS 1)
  boilerplate_append_setting(_content WARMUP 0)
  boilerplate_append_setting(_content SCENARIO "${_workload}")
  boilerplate_append_setting(_content PROFILE "${BOILERPLATE_PROFILE}")
  boilerplate_append_setting(_content CONFIG "$<CONFIG>")
  boilerplate_append_setting(_content COMPILER "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  boilerplate_append_setting(_content SOURCE_DIR "${CMAKE_SOURCE_DIR}")
  boilerplate_append_setting(_content RESULT_ROOT "${BOILERPLATE_RESULTS_DIR}/pgo/${_workload}")
  set(_config "${CMAKE_CURRENT_BINARY_DIR}/scenarios/$<CONFIG>/${_workload}.cmake")
  file(GENERATE OUTPUT "${_config}" CONTENT "${_content}")
  add_custom_target(${_workload} COMMAND ${CMAKE_COMMAND} "-DRUN_CONFIG=${_config}"
    -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmark/RunWorkload.cmake"
    DEPENDS ${target} USES_TERMINAL VERBATIM)
  # Training order is deterministic even with a parallel build.
  if(_count GREATER 0)
    add_dependencies(${_workload} boilerplate_pgo_workload_${_count})
  endif()
  add_dependencies(boilerplate_pgo_train ${_workload})
endfunction()
