include_guard(GLOBAL)

option(BOILERPLATE_CUDA_SEPARABLE_COMPILATION "Enable separate compilation of CUDA device code" ON)
set(BOILERPLATE_CUDA_RUNTIME_LIBRARY Static CACHE STRING "CUDA runtime linkage: Static, Shared or None")
set_property(CACHE BOILERPLATE_CUDA_RUNTIME_LIBRARY PROPERTY STRINGS Static Shared None)

function(_boilerplate_validate_cuda target)
  boilerplate_get_target_setting(${target} CUDA _enabled)
  if(NOT _enabled)
    return()
  endif()
  get_property(_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
  if(NOT "CUDA" IN_LIST _languages)
    message(FATAL_ERROR "Target ${target}: cuda policy requires boilerplate_project(CAPABILITIES ... cuda) before creating targets")
  endif()
  if(NOT CMAKE_CUDA_COMPILER_ID STREQUAL "NVIDIA")
    message(FATAL_ERROR "Target ${target}: CUDA target policies currently require NVIDIA nvcc")
  endif()
  # CPU instrumentation and IPO flags are not CUDA device instrumentation/IPO.
  # Reject combinations explicitly until their host/device-link semantics are supported.
  foreach(_key IN ITEMS HARDENING COVERAGE REPRODUCIBLE FRAME_POINTERS ENABLE_NATIVE
      ENABLE_NO_SEMANTIC_INTERPOSITION ENABLE_NO_PLT ENABLE_GC_SECTIONS USE_LLD ENABLE_ICF WINDOWS_CFG)
    boilerplate_get_target_setting(${target} ${_key} _value)
    if(_value)
      message(FATAL_ERROR "Target ${target}: CUDA does not support ${_key}; use runtime-cuda or keep this CPU policy on a separate target")
    endif()
  endforeach()
  foreach(_key IN ITEMS LTO_MODE PGO_MODE SANITIZER CFI)
    boilerplate_get_target_setting(${target} ${_key} _value)
    if(NOT _value STREQUAL "none")
      message(FATAL_ERROR "Target ${target}: CUDA does not support ${_key}=${_value}; use runtime-cuda or a separate CPU target")
    endif()
  endforeach()
  boilerplate_get_target_setting(${target} CUDA_STANDARD _standard)
  boilerplate_get_target_setting(${target} CUDA_RUNTIME_LIBRARY _runtime)
  if(NOT _standard MATCHES "^(17|20)$")
    message(FATAL_ERROR "Target ${target}: CUDA_STANDARD must be 17 or 20")
  endif()
  if(NOT _runtime MATCHES "^(Static|Shared|None)$")
    message(FATAL_ERROR "Target ${target}: CUDA_RUNTIME_LIBRARY must be Static, Shared or None")
  endif()
endfunction()

function(_boilerplate_cuda_target target)
  boilerplate_get_target_setting(${target} CUDA _enabled)
  if(NOT _enabled)
    return()
  endif()
  foreach(_key IN ITEMS CUDA_STANDARD CUDA_SEPARABLE_COMPILATION CUDA_RUNTIME_LIBRARY)
    boilerplate_get_target_setting(${target} ${_key} _value)
    set_property(TARGET ${target} PROPERTY ${_key} "${_value}")
  endforeach()
  set_target_properties(${target} PROPERTIES CUDA_STANDARD_REQUIRED ON CUDA_EXTENSIONS OFF)
  foreach(_pair IN ITEMS "CUDA_LINEINFO;--generate-line-info" "CUDA_DEVICE_DEBUG;--device-debug" "CUDA_FAST_MATH;--use_fast_math")
    list(GET _pair 0 _key)
    list(GET _pair 1 _flag)
    boilerplate_get_target_setting(${target} ${_key} _value)
    if(_value)
      target_compile_options(${target} PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:${_flag}>")
    endif()
  endforeach()
endfunction()

# The project capability enables the language; these policies configure targets.
boilerplate_define_policy(cuda CUDA ON HOOKS _boilerplate_cuda_target)
boilerplate_define_policy(cuda-debug INHERITS cuda CUDA_DEVICE_DEBUG ON CUDA_LINEINFO OFF DEBUG_SYMBOLS ON)
boilerplate_define_policy(cuda-profiled INHERITS cuda CUDA_LINEINFO ON CUDA_DEVICE_DEBUG OFF)
boilerplate_define_policy(cuda-fast-math INHERITS cuda CUDA_FAST_MATH ON)
boilerplate_define_policy(runtime-cuda INHERITS runtime cuda)
