include_guard(GLOBAL)

set(BOILERPLATE_IMGUI_TARGET "" CACHE STRING
  "Existing ImGui target to link; empty auto-detects imgui::imgui, ImGui::ImGui or imgui")

function(_boilerplate_graphics_vulkan target)
  if(NOT TARGET Vulkan::Vulkan)
    find_package(Vulkan REQUIRED)
  endif()
  target_link_libraries(${target} PRIVATE Vulkan::Vulkan)
endfunction()

function(_boilerplate_graphics_glfw target)
  if(NOT TARGET glfw AND NOT TARGET glfw3::glfw)
    find_package(glfw3 CONFIG QUIET)
    if(NOT TARGET glfw AND NOT TARGET glfw3::glfw)
      find_package(glfw3 REQUIRED)
    endif()
  endif()
  if(TARGET glfw3::glfw)
    target_link_libraries(${target} PRIVATE glfw3::glfw)
  elseif(TARGET glfw)
    target_link_libraries(${target} PRIVATE glfw)
  else()
    message(FATAL_ERROR "GLFW was found but did not provide glfw or glfw3::glfw")
  endif()
endfunction()

function(_boilerplate_graphics_glew target)
  if(NOT TARGET GLEW::GLEW)
    find_package(GLEW REQUIRED)
  endif()
  target_link_libraries(${target} PRIVATE GLEW::GLEW)
endfunction()

function(_boilerplate_graphics_glm target)
  if(NOT TARGET glm::glm)
    find_package(glm CONFIG QUIET)
    if(NOT TARGET glm::glm)
      find_package(glm REQUIRED)
    endif()
  endif()
  if(NOT TARGET glm::glm)
    message(FATAL_ERROR "GLM was found but did not provide glm::glm")
  endif()
  target_link_libraries(${target} PRIVATE glm::glm)
endfunction()

function(_boilerplate_graphics_imgui target)
  set(_candidate "${BOILERPLATE_IMGUI_TARGET}")
  if(_candidate AND NOT TARGET ${_candidate})
    message(FATAL_ERROR "BOILERPLATE_IMGUI_TARGET does not exist: ${_candidate}")
  endif()
  if(NOT _candidate)
    foreach(_known IN ITEMS imgui::imgui ImGui::ImGui imgui)
      if(TARGET ${_known})
        set(_candidate ${_known})
        break()
      endif()
    endforeach()
  endif()
  if(NOT _candidate)
    find_package(imgui CONFIG QUIET)
    foreach(_known IN ITEMS imgui::imgui ImGui::ImGui imgui)
      if(TARGET ${_known})
        set(_candidate ${_known})
        break()
      endif()
    endforeach()
  endif()
  if(NOT _candidate)
    message(FATAL_ERROR
      "ImGui policy needs an existing target; set BOILERPLATE_IMGUI_TARGET or provide imgui::imgui/ImGui::ImGui/imgui")
  endif()
  target_link_libraries(${target} PRIVATE ${_candidate})
endfunction()

# Pure dependency capabilities. Compose them with `minimal`, runtime policies,
# Qt policies, or each other without resetting target optimization settings.
boilerplate_define_policy(vulkan HOOKS _boilerplate_graphics_vulkan)
boilerplate_define_policy(glfw HOOKS _boilerplate_graphics_glfw)
boilerplate_define_policy(glew HOOKS _boilerplate_graphics_glew)
boilerplate_define_policy(glm HOOKS _boilerplate_graphics_glm)
boilerplate_define_policy(imgui HOOKS _boilerplate_graphics_imgui)
boilerplate_define_policy(graphics-vulkan INHERITS vulkan glfw glm)
boilerplate_define_policy(graphics-opengl INHERITS glfw glew glm)
boilerplate_define_policy(graphics-vulkan-imgui INHERITS graphics-vulkan imgui)
boilerplate_define_policy(graphics-opengl-imgui INHERITS graphics-opengl imgui)
# Opinionated kitchen-sink profile matching projects that expose Vulkan and an
# OpenGL/ImGui path from the same executable.
boilerplate_define_policy(graphics INHERITS vulkan glfw glew glm imgui)

include("${CMAKE_CURRENT_LIST_DIR}/Shaders.cmake")
