include_guard(GLOBAL)

function(_boilerplate_qt_require target)
  set(_components ${ARGN})
  set(_missing FALSE)
  foreach(_component IN LISTS _components)
    if(NOT TARGET Qt6::${_component})
      set(_missing TRUE)
    endif()
  endforeach()
  if(_missing)
    find_package(Qt6 REQUIRED COMPONENTS ${_components})
  endif()
  foreach(_component IN LISTS _components)
    if(NOT TARGET Qt6::${_component})
      message(FATAL_ERROR "Qt6 component ${_component} did not provide Qt6::${_component}")
    endif()
    target_link_libraries(${target} PRIVATE Qt6::${_component})
  endforeach()
endfunction()

function(_boilerplate_qt_core target)
  _boilerplate_qt_require(${target} Core)
  set_target_properties(${target} PROPERTIES AUTOMOC ON)
endfunction()
function(_boilerplate_qt_gui target)
  _boilerplate_qt_require(${target} Core Gui)
  set_target_properties(${target} PROPERTIES AUTOMOC ON AUTORCC ON)
endfunction()
function(_boilerplate_qt_widgets target)
  _boilerplate_qt_require(${target} Core Gui Widgets)
  set_target_properties(${target} PROPERTIES AUTOMOC ON AUTOUIC ON AUTORCC ON)
endfunction()
function(_boilerplate_qt_network target)
  _boilerplate_qt_require(${target} Network)
endfunction()
function(_boilerplate_qt_qml target)
  _boilerplate_qt_require(${target} Core Gui Qml Quick)
  set_target_properties(${target} PROPERTIES AUTOMOC ON AUTORCC ON)
endfunction()
function(_boilerplate_qt_concurrent target)
  _boilerplate_qt_require(${target} Concurrent)
endfunction()
function(_boilerplate_qt_sql target)
  _boilerplate_qt_require(${target} Sql)
endfunction()
function(_boilerplate_qt_test target)
  _boilerplate_qt_require(${target} Test)
endfunction()

# Qt policies are capabilities, not project baselines: they deliberately do not
# inherit `minimal`, so `runtime-dagflow qt-widgets` does not reset runtime tuning.
boilerplate_define_policy(qt-core HOOKS _boilerplate_qt_core)
boilerplate_define_policy(qt-gui HOOKS _boilerplate_qt_gui)
boilerplate_define_policy(qt-widgets HOOKS _boilerplate_qt_widgets)
boilerplate_define_policy(qt-network HOOKS _boilerplate_qt_network)
boilerplate_define_policy(qt-qml HOOKS _boilerplate_qt_qml)
boilerplate_define_policy(qt-quick INHERITS qt-qml)
boilerplate_define_policy(qt-concurrent HOOKS _boilerplate_qt_concurrent)
boilerplate_define_policy(qt-sql HOOKS _boilerplate_qt_sql)
boilerplate_define_policy(qt-test HOOKS _boilerplate_qt_test)
boilerplate_define_policy(qt-desktop INHERITS qt-widgets qt-network qt-concurrent)
boilerplate_define_policy(qt-qml-app INHERITS qt-qml qt-network)

# Packaging/deployment is deliberately explicit: Qt linkage is target policy,
# while copying plugins/platform libraries is a distribution lifecycle action.
function(boilerplate_enable_qt_deployment target)
  if(NOT TARGET ${target})
    message(FATAL_ERROR "boilerplate_enable_qt_deployment: unknown target ${target}")
  endif()
  if(COMMAND qt_generate_deploy_app_script)
    qt_generate_deploy_app_script(
      TARGET ${target}
      OUTPUT_SCRIPT _deploy_script
      NO_UNSUPPORTED_PLATFORM_ERROR)
    install(SCRIPT ${_deploy_script} COMPONENT Runtime)
  else()
    message(WARNING
      "Qt deployment helper is unavailable in this Qt/CMake integration; target ${target} will be installed without Qt deployment scripting")
  endif()
endfunction()
