include_guard(GLOBAL)

# One invocation is one named variant; repeated invocations append to the target.
# Compiler depfiles track includes, including generated/transitive includes.
function(boilerplate_add_shaders target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "COPY_TO_RUNTIME" "LANGUAGE;NAME;SOURCE_DIR;OUTPUT_DIR;COMPILER;BACKEND;PROFILE;ENTRY_POINT;FORMAT"
    "SOURCES;DEFINES;INCLUDE_DIRS;OPTIONS;DEPENDS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT TARGET ${target})
    message(FATAL_ERROR "boilerplate_add_shaders(${target}): invalid arguments or target")
  endif()
  if(NOT ARG_LANGUAGE)
    set(ARG_LANGUAGE GLSL)
  endif()
  if(NOT ARG_LANGUAGE MATCHES "^(GLSL|HLSL)$")
    message(FATAL_ERROR "Shader LANGUAGE must be GLSL or HLSL")
  endif()
  if(NOT ARG_NAME)
    set(ARG_NAME default)
  endif()
  if(NOT ARG_NAME MATCHES "^[A-Za-z0-9_-]+$")
    message(FATAL_ERROR "Shader NAME must contain only letters, digits, underscore or hyphen")
  endif()
  set(_shader_target "${target}_shaders_${ARG_NAME}")
  if(TARGET ${_shader_target})
    message(FATAL_ERROR "Duplicate shader variant: ${_shader_target}")
  endif()
  if(NOT ARG_SOURCE_DIR)
    set(ARG_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/shaders")
  endif()
  get_filename_component(ARG_SOURCE_DIR "${ARG_SOURCE_DIR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  if(NOT ARG_OUTPUT_DIR)
    set(ARG_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/shaders/${target}")
  endif()
  get_filename_component(ARG_OUTPUT_DIR "${ARG_OUTPUT_DIR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
  set(_variant_dir "")
  if(NOT ARG_NAME STREQUAL "default")
    set(_variant_dir "/${ARG_NAME}")
  endif()
  # Config-specific outputs allow Ninja Multi-Config / VS builds to coexist.
  set(_output_root "${ARG_OUTPUT_DIR}/$<CONFIG>${_variant_dir}")
  if(NOT ARG_SOURCES)
    if(ARG_LANGUAGE STREQUAL "HLSL")
      message(FATAL_ERROR "HLSL requires explicit SOURCES with a common PROFILE and ENTRY_POINT")
    endif()
    file(GLOB_RECURSE ARG_SOURCES CONFIGURE_DEPENDS
      "${ARG_SOURCE_DIR}/*.vert" "${ARG_SOURCE_DIR}/*.frag" "${ARG_SOURCE_DIR}/*.comp"
      "${ARG_SOURCE_DIR}/*.geom" "${ARG_SOURCE_DIR}/*.tesc" "${ARG_SOURCE_DIR}/*.tese")
  endif()
  if(NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_shaders(${target}): no shader sources")
  endif()
  if(NOT ARG_COMPILER)
    set(_compiler _compiler-NOTFOUND)
    if(ARG_BACKEND STREQUAL "glslang")
      find_program(_compiler NAMES glslangValidator NO_CACHE REQUIRED)
    elseif(ARG_BACKEND STREQUAL "glslc")
      find_program(_compiler NAMES glslc NO_CACHE REQUIRED)
    elseif(ARG_LANGUAGE STREQUAL "HLSL")
      find_program(_compiler NAMES dxc NO_CACHE REQUIRED)
    elseif(Vulkan_GLSLC_EXECUTABLE)
      set(_compiler "${Vulkan_GLSLC_EXECUTABLE}")
    else()
      find_program(_compiler NAMES glslc glslangValidator NO_CACHE REQUIRED)
    endif()
    set(ARG_COMPILER "${_compiler}")
  endif()
  if(NOT IS_ABSOLUTE "${ARG_COMPILER}")
    set(_compiler _compiler-NOTFOUND)
    find_program(_compiler NAMES "${ARG_COMPILER}" NO_CACHE REQUIRED)
    set(ARG_COMPILER "${_compiler}")
  endif()
  if(NOT ARG_BACKEND)
    get_filename_component(_compiler_name "${ARG_COMPILER}" NAME_WE)
    if(_compiler_name MATCHES "glslang")
      set(ARG_BACKEND glslang)
    elseif(ARG_LANGUAGE STREQUAL "HLSL")
      set(ARG_BACKEND dxc)
    else()
      set(ARG_BACKEND glslc)
    endif()
  endif()
  if(ARG_LANGUAGE STREQUAL "HLSL")
    if(NOT ARG_BACKEND STREQUAL "dxc" OR NOT ARG_PROFILE OR NOT ARG_ENTRY_POINT)
      message(FATAL_ERROR "HLSL requires BACKEND dxc, PROFILE (e.g. ps_6_0) and ENTRY_POINT")
    endif()
    if(NOT ARG_FORMAT)
      set(ARG_FORMAT DXIL)
    endif()
    if(NOT ARG_FORMAT MATCHES "^(DXIL|SPIRV)$")
      message(FATAL_ERROR "HLSL FORMAT must be DXIL or SPIRV")
    endif()
  elseif(NOT ARG_BACKEND MATCHES "^(glslc|glslang)$" OR (ARG_FORMAT AND NOT ARG_FORMAT STREQUAL "SPIRV"))
    message(FATAL_ERROR "GLSL requires glslc/glslang and SPIRV output")
  endif()
  set(_flags ${ARG_OPTIONS})
  set(_include_paths)
  foreach(_dir IN LISTS ARG_INCLUDE_DIRS)
    get_filename_component(_dir "${_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    list(APPEND _flags "-I${_dir}")
    list(APPEND _include_paths "${_dir}/")
  endforeach()
  foreach(_define IN LISTS ARG_DEFINES)
    list(APPEND _flags "-D${_define}")
  endforeach()
  set(_extension spv)
  if(ARG_FORMAT STREQUAL "DXIL")
    set(_extension dxil)
  endif()
  set(_outputs)
  set(_copy_commands)
  foreach(_source IN LISTS ARG_SOURCES)
    get_filename_component(_source_abs "${_source}" ABSOLUTE BASE_DIR "${ARG_SOURCE_DIR}")
    file(RELATIVE_PATH _relative "${ARG_SOURCE_DIR}" "${_source_abs}")
    if(_relative MATCHES "^\\.\\./" OR IS_ABSOLUTE "${_relative}")
      message(FATAL_ERROR "Shader source must be inside SOURCE_DIR: ${_source}")
    endif()
    set(_output "${_output_root}/${_relative}.${_extension}")
    get_property(_claimed GLOBAL PROPERTY BOILERPLATE_SHADER_OUTPUTS)
    if(_output IN_LIST _claimed)
      message(FATAL_ERROR "Shader output already registered: ${_output}")
    endif()
    set_property(GLOBAL APPEND PROPERTY BOILERPLATE_SHADER_OUTPUTS "${_output}")
    get_filename_component(_parent "${_output}" DIRECTORY)
    set(_depfile "${_output}.d")
    set(_dependency_command)
    if(ARG_BACKEND STREQUAL "dxc")
      set(_args -T "${ARG_PROFILE}" -E "${ARG_ENTRY_POINT}" -Fo "${_output}")
      if(ARG_FORMAT STREQUAL "SPIRV")
        list(APPEND _args -spirv)
      endif()
      # DXC's -MD runs dependency generation instead of emitting the binary.
      # Keep it separate from compilation (unlike glslc/Clang's -MD behavior).
      set(_dependency_command COMMAND "${ARG_COMPILER}" ${_args} ${_flags}
        -MD -MF "${_depfile}" "${_source_abs}")
    elseif(ARG_BACKEND STREQUAL "glslang")
      set(_args -V -o "${_output}" --depfile "${_depfile}")
    else()
      set(_args -o "${_output}" -MD -MF "${_depfile}")
    endif()
    add_custom_command(OUTPUT "${_output}"
      COMMAND "${CMAKE_COMMAND}" -E make_directory "${_parent}"
      ${_dependency_command}
      COMMAND "${ARG_COMPILER}" ${_args} ${_flags} "${_source_abs}"
      COMMAND "${CMAKE_COMMAND}" "-DDEPFILE=${_depfile}"
        "-DPATHS=${_output};${_source_abs};${ARG_SOURCE_DIR}/;${_include_paths}"
        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/NormalizeShaderDepfile.cmake"
      DEPENDS "${_source_abs}" "${ARG_COMPILER}" ${ARG_DEPENDS}
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/NormalizeShaderDepfile.cmake"
      DEPFILE "${_depfile}" VERBATIM)
    list(APPEND _outputs "${_output}")
    if(ARG_COPY_TO_RUNTIME)
      get_filename_component(_relative_parent "${_relative}" DIRECTORY)
      list(APPEND _copy_commands
        COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:${target}>/shaders${_variant_dir}/${_relative_parent}"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_output}"
          "$<TARGET_FILE_DIR:${target}>/shaders${_variant_dir}/${_relative}.${_extension}")
    endif()
  endforeach()
  # Runs copy_if_different even when only a shader changed or a copy was deleted.
  add_custom_target(${_shader_target} ${_copy_commands} DEPENDS ${_outputs} VERBATIM)
  if(NOT TARGET ${target}_shaders)
    add_custom_target(${target}_shaders)
    add_dependencies(${target} ${target}_shaders)
  endif()
  add_dependencies(${target}_shaders ${_shader_target})
  set_property(TARGET ${target} APPEND PROPERTY BOILERPLATE_SHADER_OUTPUTS "${_outputs}")
  set_property(TARGET ${target} APPEND PROPERTY BOILERPLATE_SHADER_DIRECTORIES "${ARG_OUTPUT_DIR}/$<CONFIG>")
endfunction()

function(boilerplate_add_glsl_shaders target)
  boilerplate_add_shaders(${target} LANGUAGE GLSL ${ARGN})
endfunction()

function(boilerplate_add_hlsl_shaders target)
  boilerplate_add_shaders(${target} LANGUAGE HLSL ${ARGN})
endfunction()
