cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "Pass CHECK_BINARY")
endif()
get_filename_component(_toolkit "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
set(_source "${CHECK_BINARY}/capability-source")
file(MAKE_DIRECTORY "${_source}")
file(WRITE "${_source}/main.cpp" "int main() { return 0; }\n")
file(WRITE "${_source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.26)
project(CompilerCapabilities LANGUAGES CXX)
include("${TOOLKIT_DIR}/Boilerplate.cmake")
if(NOT MSVC)
  # A static try-compile would miss a broken linker. The helper must link even
  # when the caller's cross toolchain asks for static compiler probes.
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
  _boilerplate_probe_flags(_works "" "")
  _boilerplate_probe_flags(_bad_compile "-fdagflow-nonexistent-option" "")
  _boilerplate_probe_flags(_bad_link "" "-Wl,--dagflow-nonexistent-option")
  if(NOT _works OR _bad_compile OR _bad_link)
    message(FATAL_ERROR "Compiler/linker capability detection accepted invalid flags")
  endif()
endif()
boilerplate_add_executable(probe SOURCES main.cpp)
enable_testing()
add_test(NAME probe COMMAND probe)
]=])
set(_compiler)
if(CHECK_COMPILER)
  set(_compiler "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}")
endif()
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "${ARGV}: ${_out}${_err}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" -S "${_source}" -B "${CHECK_BINARY}/capability-build"
  -G "Ninja Multi-Config" "-DTOOLKIT_DIR=${_toolkit}" ${_compiler}
  -DBOILERPLATE_PROFILE=release -DBOILERPLATE_LTO_MODE=none)
run("${CMAKE_COMMAND}" --build "${CHECK_BINARY}/capability-build" --config Release)
run("${CMAKE_CTEST_COMMAND}" --test-dir "${CHECK_BINARY}/capability-build" -C Release --output-on-failure)
message(STATUS "Compiler/linker rejection and multi-config profile checks passed")
