cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "CHECK_BINARY is required")
endif()
get_filename_component(_modules "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
set(_args "-DTOOLKIT_DIR=${_modules}" -DBOILERPLATE_COMPILER_CACHE=none
  -DBOILERPLATE_CUDA_ARCHITECTURES=75 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON)
if(CHECK_COMPILER)
  list(APPEND _args "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}")
endif()
if(CHECK_CUDA_HOST_COMPILER)
  list(APPEND _args "-DCMAKE_CUDA_HOST_COMPILER=${CHECK_CUDA_HOST_COMPILER}")
endif()
if(CHECK_CUDA_COMPILER)
  list(APPEND _args "-DCMAKE_CUDA_COMPILER=${CHECK_CUDA_COMPILER}")
endif()
if(NOT CHECK_GENERATOR)
  set(CHECK_GENERATOR Ninja)
endif()
set(_source "${CMAKE_CURRENT_LIST_DIR}/cuda")
set(_build "${CHECK_BINARY}/cuda-build")
run("${CMAKE_COMMAND}" -S "${_source}" -B "${_build}" -G "${CHECK_GENERATOR}"
  -DCMAKE_BUILD_TYPE=Release ${_args})
run("${CMAKE_COMMAND}" --build "${_build}" --config Release --parallel 2)
run("${CMAKE_CTEST_COMMAND}" --test-dir "${_build}" -C Release --output-on-failure)
file(READ "${_build}/compile_commands.json" _commands)
foreach(_expected IN ITEMS --device-debug --generate-line-info --use_fast_math)
  if(NOT _commands MATCHES "${_expected}")
    message(FATAL_ERROR "CUDA fixture did not exercise ${_expected}")
  endif()
endforeach()
function(reject name expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_source}" -B "${CHECK_BINARY}/cuda-${name}" -G Ninja
    ${_args} ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}\n${_err}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected ${expected}, got: ${_out}\n${_err}")
  endif()
endfunction()
reject(no-language "cuda policy requires" -DTEST_MODE=no-language)
reject(lto "CUDA does not support LTO_MODE" -DTEST_MODE=invalid -DBAD_POLICY=full-lto)
reject(asan "CUDA does not support SANITIZER" -DTEST_MODE=invalid -DBAD_POLICY=asan)
reject(standard "CUDA_STANDARD must be" -DTEST_MODE=invalid -DBAD_STANDARD=23)
message(STATUS "CUDA shared/static, mixed C++/CUDA, device linking, profiles and negative checks passed")
