cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "CHECK_BINARY is required")
endif()
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
get_filename_component(_modules "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
set(_args)
if(CHECK_COMPILER)
  list(APPEND _args "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}")
endif()
if(NOT CHECK_GENERATOR)
  set(CHECK_GENERATOR Ninja)
endif()
set(_count 0)
foreach(_backend IN ITEMS glslc glslang dxc)
  if(_backend STREQUAL "glslang")
    set(_name glslangValidator)
  else()
    set(_name "${_backend}")
  endif()
  unset(_compiler)
  find_program(_compiler NAMES "${_name}" NO_CACHE)
  if(NOT _compiler)
    if(REQUIRE_ALL_BACKENDS)
      message(FATAL_ERROR "Shader checks require ${_name}")
    endif()
    message(STATUS "Shader backend ${_backend} skipped: compiler not installed")
    continue()
  endif()
  set(_formats SPIRV)
  if(_backend STREQUAL "dxc")
    list(APPEND _formats DXIL)
  endif()
  foreach(_format IN LISTS _formats)
    set(_root "${CHECK_BINARY}/shader paths/${_backend}-${_format}")
    file(REMOVE_RECURSE "${_root}")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/shaders/" DESTINATION "${_root}/source")
    set(_build "${_root}/build")
    run("${CMAKE_COMMAND}" -S "${_root}/source" -B "${_build}" -G "${CHECK_GENERATOR}"
      -DCMAKE_BUILD_TYPE=Debug ${_args} "-DBOILERPLATE_MODULE_DIR=${_modules}"
      "-DTEST_COMPILER=${_compiler}" "-DTEST_BACKEND=${_backend}" "-DTEST_FORMAT=${_format}" "-DTEST_SOURCE_DIR=${_root}/source")
    run("${CMAKE_COMMAND}" --build "${_build}" --config Debug --parallel 2)
    include("${_build}/paths-Debug.cmake")
    list(GET outputs 0 _first)
    list(GET outputs 1 _second)
    file(SHA256 "${_first}" _hash)
    file(SHA256 "${_second}" _other_hash)
    if(_hash STREQUAL _other_hash)
      message(FATAL_ERROR "Shader variants produced identical output")
    endif()
    file(TIMESTAMP "${_first}" _timestamp "%s")
    file(TIMESTAMP "${executable}" _exe_timestamp "%s")
    run("${CMAKE_COMMAND}" -E sleep 1)
    run("${CMAKE_COMMAND}" --build "${_build}" --config Debug)
    file(TIMESTAMP "${_first}" _after "%s")
    if(NOT _timestamp STREQUAL _after)
      message(FATAL_ERROR "No-op build recompiled shader")
    endif()
    file(WRITE "${_root}/source/includes/nested.glsl" "#define SHIFT 0.75\n")
    run("${CMAKE_COMMAND}" --build "${_build}" --config Debug)
    file(SHA256 "${_first}" _changed)
    file(TIMESTAMP "${executable}" _exe_after "%s")
    if(_hash STREQUAL _changed OR NOT _exe_timestamp STREQUAL _exe_after)
      message(FATAL_ERROR "Include-only edit must recompile shaders without relinking executable")
    endif()
    get_filename_component(_filename "${_first}" NAME)
    file(SHA256 "${runtime}/low/${_filename}" _copied)
    if(NOT _copied STREQUAL _changed)
      message(FATAL_ERROR "Runtime shader copy is stale")
    endif()
    file(REMOVE "${runtime}/low/${_filename}")
    run("${CMAKE_COMMAND}" --build "${_build}" --config Debug)
    if(NOT EXISTS "${runtime}/low/${_filename}")
      message(FATAL_ERROR "Deleted runtime shader copy was not restored")
    endif()
    if(CHECK_GENERATOR STREQUAL "Ninja Multi-Config")
      run("${CMAKE_COMMAND}" --build "${_build}" --config Release --parallel 2)
      file(SHA256 "${_first}" _debug_after_release)
      include("${_build}/paths-Release.cmake")
      list(GET outputs 0 _release)
      if(_release STREQUAL _first OR NOT EXISTS "${_release}" OR NOT _debug_after_release STREQUAL _changed)
        message(FATAL_ERROR "Debug and Release shader outputs must coexist")
      endif()
    endif()
    math(EXPR _count "${_count}+1")
    message(STATUS "Shader ${_backend}/${_format}: variants, transitive include rebuild, no-op, runtime copy passed")
  endforeach()
endforeach()
if(_count EQUAL 0)
  message(FATAL_ERROR "No shader compiler installed; cannot validate shader pipeline")
endif()
