cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY OR NOT CHECK_COMPILER)
  message(FATAL_ERROR "Pass CHECK_BINARY and CHECK_COMPILER")
endif()
get_filename_component(_toolkit "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
set(_source "${CMAKE_CURRENT_LIST_DIR}/control-flow")

function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT "${_result}" STREQUAL "0")
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}${_err}")
  endif()
endfunction()

function(check name policy lto)
  set(_build "${CHECK_BINARY}/${name}")
  run("${CMAKE_COMMAND}" -S "${_source}" -B "${_build}" -G Ninja
    "-DTOOLKIT_DIR=${_toolkit}" "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}"
    -DCMAKE_BUILD_TYPE=Release "-DTEST_POLICY=${policy}" "-DTEST_LTO=${lto}" ${ARGN})
  run("${CMAKE_COMMAND}" --build "${_build}" --parallel 2)
  run("${CMAKE_CTEST_COMMAND}" --test-dir "${_build}" --output-on-failure --no-tests=error)
  message(STATUS "Control-flow check passed: ${name}")
endfunction()

function(reject name pattern)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_source}" -B "${CHECK_BINARY}/${name}" -G Ninja
    "-DTOOLKIT_DIR=${_toolkit}" "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}"
    -DCMAKE_BUILD_TYPE=Release ${ARGN}
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${pattern}")
    message(FATAL_ERROR "${name}: expected configure failure matching ${pattern}: ${_out}${_err}")
  endif()
endfunction()

if(WIN32)
  check(windows-cfg windows-cfg none)
  check(windows-cfg-shared windows-cfg none -DTEST_KIND=shared)
  reject(cfi-platform "CFI currently requires" -DTEST_POLICY=cfi)
  reject(cfg-edit-and-continue "incompatible with /ZI"
    -DTEST_POLICY=windows-cfg -DTEST_LTO=none -DTEST_EDIT_AND_CONTINUE=ON)
else()
  foreach(_policy IN ITEMS cfi cfi-icall cfi-vcall)
    check("${_policy}" "${_policy}" thin)
    check("${_policy}-diagnostics" "${_policy}" thin -DTEST_DIAGNOSTICS=ON)
  endforeach()
  check(cfi-full-lto cfi full)
  check(runtime-hardened runtime-hardened thin)
  check(cfi-shared cfi thin -DTEST_KIND=shared -DTEST_DIAGNOSTICS=ON)
  check(cfi-ubsan cfi thin -DTEST_SANITIZER=undefined -DTEST_DIAGNOSTICS=ON)
  reject(no-lto "CFI requires LTO_MODE" -DTEST_POLICY=cfi -DTEST_LTO=none)
  reject(invalid-cfi "invalid CFI" -DTEST_POLICY=cfi -DTEST_CFI=invalid)
  reject(cfg-platform "windows-cfg requires" -DTEST_POLICY=windows-cfg -DTEST_LTO=none)
  find_program(_gcc g++)
  if(_gcc)
    reject(gcc-platform "CFI currently requires" -DTEST_POLICY=cfi "-DCMAKE_CXX_COMPILER=${_gcc}")
  endif()
endif()
reject(mixed-backends "cannot be combined" -DTEST_POLICY=cfi -DTEST_CFG=ON)
message(STATUS "Control-flow policy composition, runtime protection and validation passed")
