version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/project
    working_dir: /project
    environment:
      - BUILD_TYPE=Release
    ports:
      - "8000:8000"  
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder 
    volumes:
      - .:/project
    working_dir: /project
    environment:
      - BUILD_TYPE=Debug
    command: /bin/bash
    tty: true
    stdin_open: true