include_guard(GLOBAL)
set(BOILERPLATE_CUDA_STANDARD 20 CACHE STRING "CUDA language standard")
set(BOILERPLATE_CUDA_ARCHITECTURES "native" CACHE STRING "CMAKE_CUDA_ARCHITECTURES used by the cuda project capability")

function(_boilerplate_project_cuda_configure)
  include(CheckLanguage)
  check_language(CUDA)
  if(NOT CMAKE_CUDA_COMPILER)
    message(FATAL_ERROR "cuda project capability requested but no CUDA compiler was found")
  endif()
  set_property(GLOBAL APPEND PROPERTY BOILERPLATE_PROJECT_LANGUAGES CUDA)
  set(CMAKE_CUDA_STANDARD "${BOILERPLATE_CUDA_STANDARD}" CACHE STRING "CUDA standard" FORCE)
  set(CMAKE_CUDA_STANDARD_REQUIRED ON CACHE BOOL "Require the selected CUDA standard" FORCE)
  if(BOILERPLATE_CUDA_ARCHITECTURES)
    set(CMAKE_CUDA_ARCHITECTURES "${BOILERPLATE_CUDA_ARCHITECTURES}" CACHE STRING "CUDA architectures" FORCE)
  endif()
endfunction()
