include_guard(GLOBAL)

function(_boilerplate_project_compile_commands)
  set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "Export compile_commands.json" FORCE)
endfunction()

set(BOILERPLATE_COMPILER_CACHE "auto" CACHE STRING "Compiler cache: auto, ccache, sccache, or none")
set_property(CACHE BOILERPLATE_COMPILER_CACHE PROPERTY STRINGS auto ccache sccache none)
function(_boilerplate_project_compiler_cache)
  if(NOT BOILERPLATE_COMPILER_CACHE MATCHES "^(auto|ccache|sccache|none)$")
    message(FATAL_ERROR "Invalid BOILERPLATE_COMPILER_CACHE=${BOILERPLATE_COMPILER_CACHE}")
  endif()
  if(BOILERPLATE_COMPILER_CACHE STREQUAL "none" OR CMAKE_CXX_COMPILER_LAUNCHER)
    return()
  endif()
  set(_names)
  if(BOILERPLATE_COMPILER_CACHE STREQUAL "auto")
    set(_names sccache ccache)
  else()
    set(_names ${BOILERPLATE_COMPILER_CACHE})
  endif()
  boilerplate_project_tool(_cache "compiler cache" NAMES ${_names})
  if(_cache)
    set(CMAKE_CXX_COMPILER_LAUNCHER "${_cache}" CACHE STRING "C++ compiler launcher" FORCE)
    if(CMAKE_C_COMPILER)
      set(CMAKE_C_COMPILER_LAUNCHER "${_cache}" CACHE STRING "C compiler launcher" FORCE)
    endif()
    message(STATUS "Boilerplate: compiler cache=${_cache}")
  endif()
endfunction()
