include_guard(GLOBAL)
include(GNUInstallDirs)
set(BOILERPLATE_DOC_INPUTS "${CMAKE_SOURCE_DIR}/include;${CMAKE_SOURCE_DIR}/src;${CMAKE_SOURCE_DIR}/lib" CACHE STRING
  "Documentation input paths")
option(BOILERPLATE_DOC_WARN_AS_ERROR "Fail documentation generation on Doxygen warnings" ON)
option(BOILERPLATE_DOC_WARN_IF_DOC_ERROR
  "Report invalid documentation and unresolved references" ON)
option(BOILERPLATE_DOC_WARN_IF_UNDOCUMENTED "Warn about undocumented API symbols" ON)
option(BOILERPLATE_DOC_WARN_NO_PARAMDOC "Warn about undocumented parameters and return values" ON)
set(BOILERPLATE_DOC_EXCLUDE_PATTERNS
  "*/tests/*;*/bench/*;*/build/*;*/out/*;*/_deps/*;*/doxygen_output/*"
  CACHE STRING "Paths excluded from API documentation")
set(BOILERPLATE_DOC_EXCLUDE_SYMBOLS "" CACHE STRING "Internal symbols excluded from the documented API")
option(BOILERPLATE_DOC_EXTRACT_STATIC "Document file-local static implementation symbols" OFF)
set(BOILERPLATE_DOC_MAINPAGE "" CACHE FILEPATH "Markdown file used as the generated documentation main page")
set(BOILERPLATE_DOC_MARKDOWN_ID_STYLE DOXYGEN CACHE STRING "Markdown heading IDs: DOXYGEN or GITHUB")
set_property(CACHE BOILERPLATE_DOC_MARKDOWN_ID_STYLE PROPERTY STRINGS DOXYGEN GITHUB)

function(_boilerplate_project_docs_finalize)
  find_package(Doxygen QUIET OPTIONAL_COMPONENTS dot)
  if(NOT Doxygen_FOUND)
    if(BOILERPLATE_REQUIRE_PROJECT_TOOLS)
      message(FATAL_ERROR "docs capability requires Doxygen")
    endif()
    message(STATUS "Boilerplate: Doxygen unavailable; docs target omitted")
    return()
  endif()
  set(_inputs)
  foreach(_input IN LISTS BOILERPLATE_DOC_INPUTS)
    if(EXISTS "${_input}")
      list(APPEND _inputs "${_input}")
    endif()
  endforeach()
  if(NOT _inputs)
    message(STATUS "Boilerplate: docs capability has no existing inputs")
    return()
  endif()
  set(DOXYGEN_GENERATE_TREEVIEW YES)
  set(DOXYGEN_EXTRACT_ALL NO)
  if(BOILERPLATE_DOC_EXTRACT_STATIC)
    set(DOXYGEN_EXTRACT_STATIC YES)
  else()
    set(DOXYGEN_EXTRACT_STATIC NO)
  endif()
  set(DOXYGEN_MARKDOWN_ID_STYLE "${BOILERPLATE_DOC_MARKDOWN_ID_STYLE}")
  foreach(_warning IN ITEMS WARN_IF_UNDOCUMENTED WARN_IF_DOC_ERROR WARN_NO_PARAMDOC)
    if(BOILERPLATE_DOC_${_warning})
      set(DOXYGEN_${_warning} YES)
    else()
      set(DOXYGEN_${_warning} NO)
    endif()
  endforeach()
  # WARN_AS_ERROR is an enum in Doxygen, so CMake's ON/OFF is not accepted.
  if(BOILERPLATE_DOC_WARN_AS_ERROR)
    set(DOXYGEN_WARN_AS_ERROR FAIL_ON_WARNINGS)
  else()
    set(DOXYGEN_WARN_AS_ERROR NO)
  endif()
  set(DOXYGEN_FILE_PATTERNS *.h *.hh *.hpp *.hxx *.c *.cc *.cpp *.cxx *.md *.dox)
  list(APPEND DOXYGEN_EXCLUDE_PATTERNS ${BOILERPLATE_DOC_EXCLUDE_PATTERNS})
  list(APPEND DOXYGEN_EXCLUDE_SYMBOLS ${BOILERPLATE_DOC_EXCLUDE_SYMBOLS})
  set(DOXYGEN_SOURCE_BROWSER YES)
  if(Doxygen_dot_FOUND)
    set(DOXYGEN_HAVE_DOT YES)
  endif()
  if(NOT BOILERPLATE_DOC_MAINPAGE AND EXISTS "${CMAKE_SOURCE_DIR}/README.md")
    set(BOILERPLATE_DOC_MAINPAGE "${CMAKE_SOURCE_DIR}/README.md")
  endif()
  if(BOILERPLATE_DOC_MAINPAGE AND EXISTS "${BOILERPLATE_DOC_MAINPAGE}")
    set(DOXYGEN_USE_MDFILE_AS_MAINPAGE "${BOILERPLATE_DOC_MAINPAGE}")
    list(APPEND _inputs "${BOILERPLATE_DOC_MAINPAGE}")
  endif()
  list(REMOVE_DUPLICATES _inputs)
  doxygen_add_docs(docs ${_inputs} COMMENT "Generate API documentation")
  set_property(TARGET docs PROPERTY FOLDER "boilerplate/docs")
  if(BOILERPLATE_INSTALL)
    install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/html"
      DESTINATION "${CMAKE_INSTALL_DOCDIR}" COMPONENT Documentation OPTIONAL)
  endif()
endfunction()
