include_guard(GLOBAL)
include(GNUInstallDirs)
set(BOILERPLATE_DOC_INPUTS "${CMAKE_SOURCE_DIR}/include;${CMAKE_SOURCE_DIR}/src;${CMAKE_SOURCE_DIR}/lib" CACHE STRING
  "Documentation input paths")
option(BOILERPLATE_DOC_WARN_AS_ERROR "Fail documentation generation on Doxygen warnings" ON)

function(_boilerplate_project_docs_finalize)
  find_package(Doxygen QUIET OPTIONAL_COMPONENTS dot)
  if(NOT Doxygen_FOUND)
    if(BOILERPLATE_REQUIRE_PROJECT_TOOLS)
      message(FATAL_ERROR "docs capability requires Doxygen")
    endif()
    message(STATUS "Boilerplate: Doxygen unavailable; docs target omitted")
    return()
  endif()
  set(_inputs)
  foreach(_input IN LISTS BOILERPLATE_DOC_INPUTS)
    if(EXISTS "${_input}")
      list(APPEND _inputs "${_input}")
    endif()
  endforeach()
  if(NOT _inputs)
    message(STATUS "Boilerplate: docs capability has no existing inputs")
    return()
  endif()
  set(DOXYGEN_GENERATE_TREEVIEW YES)
  set(DOXYGEN_EXTRACT_ALL NO)
  set(DOXYGEN_EXTRACT_STATIC YES)
  set(DOXYGEN_WARN_IF_UNDOCUMENTED YES)
  set(DOXYGEN_WARN_IF_DOC_ERROR YES)
  set(DOXYGEN_WARN_NO_PARAMDOC YES)
  # WARN_AS_ERROR is an enum in Doxygen, so CMake's ON/OFF is not accepted.
  if(BOILERPLATE_DOC_WARN_AS_ERROR)
    set(DOXYGEN_WARN_AS_ERROR YES)
  else()
    set(DOXYGEN_WARN_AS_ERROR NO)
  endif()
  set(DOXYGEN_FILE_PATTERNS *.h *.hh *.hpp *.hxx *.c *.cc *.cpp *.cxx *.md *.dox)
  list(APPEND DOXYGEN_EXCLUDE_PATTERNS
    "*/tests/*" "*/bench/*" "*/build/*" "*/out/*" "*/_deps/*")
  set(DOXYGEN_SOURCE_BROWSER YES)
  if(Doxygen_dot_FOUND)
    set(DOXYGEN_HAVE_DOT YES)
  endif()
  if(EXISTS "${CMAKE_SOURCE_DIR}/README.md")
    set(DOXYGEN_USE_MDFILE_AS_MAINPAGE "${CMAKE_SOURCE_DIR}/README.md")
    list(APPEND _inputs "${CMAKE_SOURCE_DIR}/README.md")
  endif()
  list(REMOVE_DUPLICATES _inputs)
  doxygen_add_docs(docs ${_inputs} COMMENT "Generate API documentation")
  set_property(TARGET docs PROPERTY FOLDER "boilerplate/docs")
  if(BOILERPLATE_INSTALL)
    install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/html"
      DESTINATION "${CMAKE_INSTALL_DOCDIR}" COMPONENT Documentation OPTIONAL)
  endif()
endfunction()
