include_guard(GLOBAL)

option(BOILERPLATE_REQUIRE_PROJECT_TOOLS "Fail when an enabled optional project tool is unavailable" OFF)
set(BOILERPLATE_PROJECT_SOURCE_DIRS "src;include;lib;tests;test;examples;bench;cmake" CACHE STRING
  "Source directories scanned by formatting/analysis project workflows")

function(_boilerplate_project_capability_id name output)
  string(MAKE_C_IDENTIFIER "${name}" _id)
  string(TOUPPER "${_id}" _id)
  set(${output} "${_id}" PARENT_SCOPE)
endfunction()

function(boilerplate_project_tool output description)
  cmake_parse_arguments(PARSE_ARGV 2 ARG "" "" "NAMES")
  # Do not reuse a previous lookup (or the legacy shared cache entry): each
  # caller asks for a different tool, including optional tools that are absent.
  set(_tool _tool-NOTFOUND)
  find_program(_tool NAMES ${ARG_NAMES} NO_CACHE)
  if(NOT _tool AND BOILERPLATE_REQUIRE_PROJECT_TOOLS)
    message(FATAL_ERROR "${description} capability requires one of: ${ARG_NAMES}")
  elseif(NOT _tool)
    message(STATUS "Boilerplate: ${description} unavailable (${ARG_NAMES}); related target omitted")
  endif()
  set(${output} "${_tool}" PARENT_SCOPE)
endfunction()

function(boilerplate_collect_project_sources output)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "CMAKE" "" "EXTENSIONS")
  if(NOT ARG_EXTENSIONS)
    set(ARG_EXTENSIONS c cc cpp cxx h hh hpp hxx inl ipp)
  endif()
  set(_files)
  foreach(_entry IN LISTS BOILERPLATE_PROJECT_SOURCE_DIRS)
    if(IS_ABSOLUTE "${_entry}")
      set(_root "${_entry}")
    else()
      set(_root "${CMAKE_SOURCE_DIR}/${_entry}")
    endif()
    if(NOT EXISTS "${_root}")
      continue()
    endif()
    set(_patterns)
    if(ARG_CMAKE)
      list(APPEND _patterns "${_root}/CMakeLists.txt" "${_root}/*.cmake")
    else()
      foreach(_ext IN LISTS ARG_EXTENSIONS)
        list(APPEND _patterns "${_root}/*.${_ext}")
      endforeach()
    endif()
    file(GLOB_RECURSE _found CONFIGURE_DEPENDS ${_patterns})
    list(APPEND _files ${_found})
  endforeach()
  if(ARG_CMAKE AND EXISTS "${CMAKE_SOURCE_DIR}/CMakeLists.txt")
    list(APPEND _files "${CMAKE_SOURCE_DIR}/CMakeLists.txt")
  endif()
  if(_files)
    list(REMOVE_DUPLICATES _files)
    list(SORT _files)
  endif()
  set(${output} "${_files}" PARENT_SCOPE)
endfunction()

function(boilerplate_collect_targets directory output)
  get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(_subdirs DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(_subdir IN LISTS _subdirs)
    boilerplate_collect_targets("${_subdir}" _child_targets)
    list(APPEND _targets ${_child_targets})
  endforeach()
  if(_targets)
    list(REMOVE_DUPLICATES _targets)
  endif()
  set(${output} "${_targets}" PARENT_SCOPE)
endfunction()

function(boilerplate_define_project_capability name)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "INHERITS;CONFIGURE_HOOKS;FINALIZE_HOOKS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "boilerplate_define_project_capability(${name}): invalid arguments")
  endif()
  _boilerplate_project_capability_id("${name}" _id)
  get_property(_defined GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_DEFINED")
  if(_defined)
    message(FATAL_ERROR "Project capability '${name}' is already defined")
  endif()

  set(_configure)
  set(_finalize)
  set(_closure)
  foreach(_parent IN LISTS ARG_INHERITS)
    _boilerplate_project_capability_id("${_parent}" _parent_id)
    get_property(_parent_defined GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_parent_id}_DEFINED")
    if(NOT _parent_defined)
      message(FATAL_ERROR "Project capability '${name}' inherits unknown capability '${_parent}'")
    endif()
    get_property(_parent_configure GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_parent_id}_CONFIGURE_HOOKS")
    get_property(_parent_finalize GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_parent_id}_FINALIZE_HOOKS")
    get_property(_parent_closure GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_parent_id}_CLOSURE")
    list(APPEND _configure ${_parent_configure})
    list(APPEND _finalize ${_parent_finalize})
    list(APPEND _closure ${_parent_closure})
  endforeach()
  list(APPEND _configure ${ARG_CONFIGURE_HOOKS})
  list(APPEND _finalize ${ARG_FINALIZE_HOOKS})
  list(APPEND _closure "${name}")
  if(_configure)
    list(REMOVE_DUPLICATES _configure)
  endif()
  if(_finalize)
    list(REMOVE_DUPLICATES _finalize)
  endif()
  if(_closure)
    list(REMOVE_DUPLICATES _closure)
  endif()
  set_property(GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_CONFIGURE_HOOKS" "${_configure}")
  set_property(GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_FINALIZE_HOOKS" "${_finalize}")
  set_property(GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_CLOSURE" "${_closure}")
  set_property(GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_DEFINED" TRUE)
  set_property(GLOBAL APPEND PROPERTY BOILERPLATE_DEFINED_PROJECT_CAPABILITIES "${name}")
endfunction()

function(_boilerplate_project_configure)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "MODE" "CAPABILITIES;TOP_LEVEL_CAPABILITIES;EMBEDDED_CAPABILITIES")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "boilerplate_project: invalid arguments: ${ARG_UNPARSED_ARGUMENTS};${ARG_KEYWORDS_MISSING_VALUES}")
  endif()
  get_property(_configured GLOBAL PROPERTY BOILERPLATE_PROJECT_CONFIGURED)
  if(_configured)
    message(FATAL_ERROR "boilerplate_project() may only be configured once per CMake build")
  endif()

  if(NOT ARG_MODE OR ARG_MODE STREQUAL "auto")
    if(PROJECT_IS_TOP_LEVEL)
      set(ARG_MODE top-level)
    else()
      set(ARG_MODE embedded)
    endif()
  endif()
  if(NOT ARG_MODE MATCHES "^(top-level|embedded)$")
    message(FATAL_ERROR "boilerplate_project MODE must be auto, top-level, or embedded")
  endif()

  set(_caps ${ARG_CAPABILITIES})
  if(ARG_MODE STREQUAL "top-level")
    list(APPEND _caps ${ARG_TOP_LEVEL_CAPABILITIES})
  else()
    list(APPEND _caps ${ARG_EMBEDDED_CAPABILITIES})
  endif()
  if(NOT _caps)
    set(_caps project-minimal)
  endif()
  list(REMOVE_DUPLICATES _caps)

  set(_configure_hooks)
  set(_finalize_hooks)
  set(_expanded_caps)
  foreach(_cap IN LISTS _caps)
    _boilerplate_project_capability_id("${_cap}" _id)
    get_property(_defined GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_DEFINED")
    if(NOT _defined)
      get_property(_known GLOBAL PROPERTY BOILERPLATE_DEFINED_PROJECT_CAPABILITIES)
      message(FATAL_ERROR "Unknown project capability '${_cap}'. Defined: ${_known}")
    endif()
    get_property(_c GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_CONFIGURE_HOOKS")
    get_property(_f GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_FINALIZE_HOOKS")
    get_property(_closure GLOBAL PROPERTY "BOILERPLATE_PROJECT_CAP_${_id}_CLOSURE")
    list(APPEND _configure_hooks ${_c})
    list(APPEND _finalize_hooks ${_f})
    list(APPEND _expanded_caps ${_closure})
  endforeach()
  if(_configure_hooks)
    list(REMOVE_DUPLICATES _configure_hooks)
  endif()
  if(_finalize_hooks)
    list(REMOVE_DUPLICATES _finalize_hooks)
  endif()
  if(_expanded_caps)
    list(REMOVE_DUPLICATES _expanded_caps)
  endif()

  set_property(GLOBAL PROPERTY BOILERPLATE_PROJECT_MODE "${ARG_MODE}")
  set_property(GLOBAL PROPERTY BOILERPLATE_ACTIVE_PROJECT_CAPABILITIES "${_caps}")
  set_property(GLOBAL PROPERTY BOILERPLATE_ACTIVE_PROJECT_CAPABILITIES_EXPANDED "${_expanded_caps}")
  set_property(GLOBAL PROPERTY BOILERPLATE_PROJECT_FINALIZE_HOOKS "${_finalize_hooks}")
  set_property(GLOBAL PROPERTY BOILERPLATE_PROJECT_CONFIGURED TRUE)
  foreach(_hook IN LISTS _configure_hooks)
    if(NOT COMMAND ${_hook})
      message(FATAL_ERROR "Project capability configure hook '${_hook}' is not a CMake command")
    endif()
    cmake_language(CALL ${_hook})
  endforeach()
  message(STATUS "Boilerplate project: mode=${ARG_MODE}, capabilities=${_caps}")
endfunction()

macro(boilerplate_project)
  _boilerplate_project_configure(${ARGV})
  # enable_language() must run in the caller's directory scope. Compiler rules
  # created inside a configure-hook function disappear when it returns.
  get_property(_boilerplate_project_languages GLOBAL PROPERTY BOILERPLATE_PROJECT_LANGUAGES)
  foreach(_boilerplate_project_language IN LISTS _boilerplate_project_languages)
    enable_language(${_boilerplate_project_language})
  endforeach()
  unset(_boilerplate_project_language)
  unset(_boilerplate_project_languages)
endmacro()

function(boilerplate_finalize_project)
  get_property(_configured GLOBAL PROPERTY BOILERPLATE_PROJECT_CONFIGURED)
  if(NOT _configured)
    return()
  endif()
  get_property(_finalized GLOBAL PROPERTY BOILERPLATE_PROJECT_FINALIZED)
  if(_finalized)
    return()
  endif()
  get_property(_hooks GLOBAL PROPERTY BOILERPLATE_PROJECT_FINALIZE_HOOKS)
  foreach(_hook IN LISTS _hooks)
    if(NOT COMMAND ${_hook})
      message(FATAL_ERROR "Project capability finalize hook '${_hook}' is not a CMake command")
    endif()
    cmake_language(CALL ${_hook})
  endforeach()
  set_property(GLOBAL PROPERTY BOILERPLATE_PROJECT_FINALIZED TRUE)
endfunction()

function(boilerplate_project_has_capability name output)
  get_property(_expanded GLOBAL PROPERTY BOILERPLATE_ACTIVE_PROJECT_CAPABILITIES_EXPANDED)
  if(name IN_LIST _expanded)
    set(${output} TRUE PARENT_SCOPE)
  else()
    set(${output} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(boilerplate_list_project_capabilities output)
  get_property(_caps GLOBAL PROPERTY BOILERPLATE_DEFINED_PROJECT_CAPABILITIES)
  set(${output} "${_caps}" PARENT_SCOPE)
endfunction()

include("${CMAKE_CURRENT_LIST_DIR}/DeveloperTools.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Formatting.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/StaticAnalysis.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../testing/Testing.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../testing/PropertyTesting.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../testing/Fuzzing.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../testing/Coverage.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Documentation.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../packaging/Packaging.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ReproducibleBuild.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/BuildInfo.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Diagnostics.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Cuda.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Web.cmake")

# Primitive project capabilities.
boilerplate_define_project_capability(project-minimal)
boilerplate_define_project_capability(compile-commands CONFIGURE_HOOKS _boilerplate_project_compile_commands)
boilerplate_define_project_capability(compiler-cache CONFIGURE_HOOKS _boilerplate_project_compiler_cache)
boilerplate_define_project_capability(formatting FINALIZE_HOOKS _boilerplate_project_formatting_finalize)
boilerplate_define_project_capability(static-analysis
  CONFIGURE_HOOKS _boilerplate_project_static_analysis_configure
  FINALIZE_HOOKS _boilerplate_project_static_analysis_finalize)
boilerplate_define_project_capability(testing
  CONFIGURE_HOOKS _boilerplate_project_testing_configure
  FINALIZE_HOOKS _boilerplate_project_testing_finalize)
boilerplate_define_project_capability(property-testing
  INHERITS testing
  FINALIZE_HOOKS _boilerplate_project_property_testing_finalize)
boilerplate_define_project_capability(fuzzing
  INHERITS testing
  FINALIZE_HOOKS _boilerplate_project_fuzzing_finalize)
boilerplate_define_project_capability(coverage-report INHERITS testing
  FINALIZE_HOOKS _boilerplate_project_coverage_finalize)
boilerplate_define_project_capability(docs FINALIZE_HOOKS _boilerplate_project_docs_finalize)
boilerplate_define_project_capability(packaging FINALIZE_HOOKS _boilerplate_project_packaging_finalize)
boilerplate_define_project_capability(reproducible-build CONFIGURE_HOOKS _boilerplate_project_reproducible_configure)
boilerplate_define_project_capability(build-info CONFIGURE_HOOKS _boilerplate_project_build_info_configure)
boilerplate_define_project_capability(diagnostics FINALIZE_HOOKS _boilerplate_project_diagnostics_finalize)
boilerplate_define_project_capability(cuda CONFIGURE_HOOKS _boilerplate_project_cuda_configure)
boilerplate_define_project_capability(web-deployment FINALIZE_HOOKS _boilerplate_project_web_finalize)

# Compositions. They are convenience names only; callers can always list the
# primitive capabilities directly and avoid a project-profile cross product.
boilerplate_define_project_capability(developer
  INHERITS compile-commands compiler-cache formatting static-analysis testing build-info diagnostics)
boilerplate_define_project_capability(quality
  INHERITS testing property-testing fuzzing static-analysis)
boilerplate_define_project_capability(distribution
  INHERITS build-info reproducible-build packaging diagnostics)
boilerplate_define_project_capability(ci
  INHERITS compile-commands testing static-analysis build-info diagnostics)
boilerplate_define_project_capability(full
  INHERITS developer quality docs distribution)
