set(ANDROID_NDK_ROOT "$ENV{ANDROID_NDK_ROOT}" CACHE PATH "Android NDK root")
if(NOT ANDROID_NDK_ROOT)
  set(ANDROID_NDK_ROOT "$ENV{ANDROID_NDK_HOME}" CACHE PATH "Android NDK root" FORCE)
endif()
set(ANDROID_ABI arm64-v8a CACHE STRING "Android target ABI")
set(ANDROID_PLATFORM android-24 CACHE STRING "Android API level")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ANDROID_NDK_ROOT ANDROID_ABI ANDROID_PLATFORM)
if(NOT EXISTS "${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake")
  message(FATAL_ERROR "Set ANDROID_NDK_ROOT to an installed Android NDK")
endif()
include("${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/TargetRoots.cmake")
