cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "Pass -DCHECK_BINARY=<temporary test directory>")
endif()
get_filename_component(_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_command_directory "${_root}")
get_filename_component(CHECK_BINARY "${CHECK_BINARY}" ABSOLUTE)
if(EXISTS "${CHECK_BINARY}")
  message(FATAL_ERROR "Use a fresh CHECK_BINARY directory")
endif()
function(run)
  execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${_command_directory}"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
function(reject)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
  if(_rc STREQUAL "0")
    message(FATAL_ERROR "Expected rejection: ${ARGV}")
  endif()
endfunction()
set(_project "${CHECK_BINARY}/project with spaces")
run("${CMAKE_COMMAND}" -DNAME=My_Project-2 "-DOUTPUT=${CHECK_BINARY}/separators" -P "${_root}/scripts/Init.cmake")
file(READ "${CHECK_BINARY}/separators/vcpkg.json" _separator_manifest)
string(JSON _separator_name GET "${_separator_manifest}" name)
if(NOT _separator_name STREQUAL "my-project-2")
  message(FATAL_ERROR "Valid separators were not normalized correctly")
endif()
run("${CMAKE_COMMAND}" -DNAME=A "-DOUTPUT=${CHECK_BINARY}/seed" -P "${_root}/scripts/Init.cmake")
# A generated project can itself be reused as a template, even with a short name.
run("${CMAKE_COMMAND}" -DNAME=MyProject "-DOUTPUT=${_project}" -P "${CHECK_BINARY}/seed/scripts/Init.cmake")
file(READ "${_project}/vcpkg.json" _manifest)
string(JSON _name GET "${_manifest}" name)
if(NOT _name STREQUAL "my-project")
  message(FATAL_ERROR "Incorrect manifest identity: ${_name}")
endif()
foreach(_pair IN ITEMS "CMakeLists.txt|project(MyProject " "lib/CMakeLists.txt|project(MyProjectLibraries "
    "tests/CMakeLists.txt|boilerplate_add_googletest(MyProject_tests "
    "Dockerfile|/bin/MyProject" "tools/container.sh|image=my-project"
    "tools/container.ps1|[string]$Image = 'my-project'"
    ".github/workflows/cmake-multi-platform.yml|--image my-project-build")
  string(REPLACE "|" ";" _parts "${_pair}")
  list(GET _parts 0 _file)
  list(GET _parts 1 _expected)
  file(READ "${_project}/${_file}" _content)
  string(FIND "${_content}" "${_expected}" _index)
  if(_index LESS 0)
    message(FATAL_ERROR "Missing '${_expected}' in ${_file}")
  endif()
endforeach()
foreach(_excluded IN ITEMS .git docs out build .env cmake_boilerplate_capabilities_graph.png)
  if(EXISTS "${_project}/${_excluded}")
    message(FATAL_ERROR "Local artifact copied: ${_excluded}")
  endif()
endforeach()
# Generated output must preserve the actual zero-knowledge user entry points.
foreach(_entry IN ITEMS setup.sh setup.ps1 build.sh build.ps1
    scripts/entry-options.sh scripts/entry-options.ps1 scripts/default-preset.txt
    scripts/install-cmake.sh)
  if(NOT EXISTS "${_project}/${_entry}")
    message(FATAL_ERROR "Generated project lacks required bootstrap entry: ${_entry}")
  endif()
endforeach()
if(NOT EXISTS "${_project}/lib/cmake/build/BuildProfiles.cmake")
  message(FATAL_ERROR "Source build/ modules were excluded")
endif()
file(SHA256 "${_project}/CMakeLists.txt" _before)
reject("${CMAKE_COMMAND}" -DNAME=Other "-DOUTPUT=${_project}" -P "${_root}/scripts/Init.cmake")
file(SHA256 "${_project}/CMakeLists.txt" _after)
if(NOT _before STREQUAL _after)
  message(FATAL_ERROR "Existing project was overwritten")
endif()
file(MAKE_DIRECTORY "${CHECK_BINARY}/hidden")
file(WRITE "${CHECK_BINARY}/hidden/.keep" "preserve me")
reject("${CMAKE_COMMAND}" -DNAME=Other "-DOUTPUT=${CHECK_BINARY}/hidden" -P "${_root}/scripts/Init.cmake")
foreach(_bad IN ITEMS "../Bad" "Bad Name" "bad;name" "install" "INSTALL" "Test" "All_Build" "Zero_Check"
    "My__Project" "My--Project" "My_-Project" "MyProject_" "MyProject-" "_MyProject" "1Project")
  # Keep the invalid value as a single argument, including semicolons.
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DNAME=${_bad}" "-DOUTPUT=${CHECK_BINARY}/invalid"
    -P "${_root}/scripts/Init.cmake" RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
  if(_rc STREQUAL "0" OR EXISTS "${CHECK_BINARY}/invalid")
    message(FATAL_ERROR "Invalid project name accepted: ${_bad}")
  endif()
endforeach()
run("${CMAKE_COMMAND}" --list-presets -S "${_project}")
run("${CMAKE_COMMAND}" --list-presets -S "${_project}/lib")
set(_command_directory "${_project}")
run("${CMAKE_COMMAND}" --preset app-release
  -DBOILERPLATE_PROJECT_CAPABILITIES=testing -DBOILERPLATE_COMPILER_CACHE=none)
run("${CMAKE_COMMAND}" --build --preset app-release --parallel 2)
run("${CMAKE_CTEST_COMMAND}" --preset app-release --output-on-failure)
run("${CMAKE_COMMAND}" --build --preset app-release --target boilerplate_run --parallel 2)
run("${CMAKE_COMMAND}" --install "${_project}/out/build/app-release" --prefix "${CHECK_BINARY}/install")
if(NOT EXISTS "${CHECK_BINARY}/install/bin/MyProject" AND NOT EXISTS "${CHECK_BINARY}/install/bin/MyProject.exe")
  message(FATAL_ERROR "Renamed application was not installed")
endif()
# Exercise the complete package entry point in a generated (and renamed) project.
# Archives are always available even if optional native installer tools are absent.
if(WIN32)
  find_program(_powershell NAMES pwsh powershell REQUIRED)
  run("${_powershell}" -NoProfile -File "${_project}/build.ps1"
    -Package -PackageFormat ZIP -NoTests)
  set(_package_ext "*.zip")
else()
  find_program(_bash bash REQUIRED)
  run("${_bash}" "${_project}/build.sh" --package --package-format TGZ --no-tests)
  set(_package_ext "*.tar.gz")
endif()
file(GLOB _packages "${_project}/out/packages/app-release/${_package_ext}")
if(NOT _packages)
  message(FATAL_ERROR "One-command packaging produced no ${_package_ext} package")
endif()
if(EXISTS "${_project}/out/packages/app-release/_CPack_Packages")
  message(FATAL_ERROR "One-command packaging left intermediate CPack staging in the distributions folder")
endif()
foreach(_package IN LISTS _packages)
  file(SIZE "${_package}" _bytes)
  if(_bytes LESS 100)
    message(FATAL_ERROR "Package is empty: ${_package}")
  endif()
endforeach()
message(STATUS "Project generation, build, CTest, install and end-to-end packaging passed: ${_packages}")
