include_guard(GLOBAL)
include(GNUInstallDirs)

function(_boilerplate_cpp_escape input output)
  string(REPLACE "\\" "\\\\" _value "${input}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(_boilerplate_project_build_info_configure)
  set(_revision "unknown")
  set(_short "unknown")
  set(_dirty false)
  find_package(Git QUIET)
  if(Git_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_SOURCE_DIR}" rev-parse HEAD
      OUTPUT_VARIABLE _git_revision OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE _git_result)
    if(_git_result EQUAL 0)
      set(_revision "${_git_revision}")
      string(SUBSTRING "${_revision}" 0 8 _short)
      execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_SOURCE_DIR}" status --porcelain
        OUTPUT_VARIABLE _git_dirty ERROR_QUIET)
      if(_git_dirty)
        set(_dirty true)
      endif()
    endif()
  endif()
  set_property(GLOBAL PROPERTY BOILERPLATE_GIT_SHORT_SHA "${_short}")

  set(_info "{}")
  string(JSON _info SET "${_info}" project "\"${CMAKE_PROJECT_NAME}\"")
  string(JSON _info SET "${_info}" version "\"${CMAKE_PROJECT_VERSION}\"")
  string(JSON _info SET "${_info}" compiler "\"${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\"")
  string(JSON _info SET "${_info}" system "\"${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}\"")
  string(JSON _info SET "${_info}" generator "\"${CMAKE_GENERATOR}\"")
  string(JSON _info SET "${_info}" configuration "\"$<CONFIG>\"")
  string(JSON _info SET "${_info}" revision "\"${_revision}\"")
  string(JSON _info SET "${_info}" dirty ${_dirty})
  get_property(_mode GLOBAL PROPERTY BOILERPLATE_PROJECT_MODE)
  get_property(_caps GLOBAL PROPERTY BOILERPLATE_ACTIVE_PROJECT_CAPABILITIES)
  get_property(_expanded_caps GLOBAL PROPERTY BOILERPLATE_ACTIVE_PROJECT_CAPABILITIES_EXPANDED)
  string(REPLACE ";" "," _caps_text "${_caps}")
  string(REPLACE ";" "," _expanded_caps_text "${_expanded_caps}")
  string(JSON _info SET "${_info}" project_mode "\"${_mode}\"")
  string(JSON _info SET "${_info}" capabilities "\"${_caps_text}\"")
  string(JSON _info SET "${_info}" capabilities_expanded "\"${_expanded_caps_text}\"")
  if(BOILERPLATE_SOURCE_DATE_EPOCH)
    string(JSON _info SET "${_info}" source_date_epoch "\"${BOILERPLATE_SOURCE_DATE_EPOCH}\"")
  endif()

  set(_config_name "$<IF:$<BOOL:$<CONFIG>>,$<CONFIG>,default>")
  set(_output "${CMAKE_BINARY_DIR}/build-info-${_config_name}.json")
  file(GENERATE OUTPUT "${_output}" CONTENT "${_info}\n")

  _boilerplate_cpp_escape("${CMAKE_PROJECT_NAME}" _project_cpp)
  _boilerplate_cpp_escape("${CMAKE_PROJECT_VERSION}" _version_cpp)
  _boilerplate_cpp_escape("${_revision}" _revision_cpp)
  _boilerplate_cpp_escape("${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}" _compiler_cpp)
  set(_generated_dir "${CMAKE_BINARY_DIR}/generated/boilerplate")
  file(MAKE_DIRECTORY "${_generated_dir}")
  set(_header "${_generated_dir}/build_info.hpp")
  file(WRITE "${_header}" "#pragma once\n#include <string_view>\n\nnamespace boilerplate::build_info {\ninline constexpr std::string_view project = \"${_project_cpp}\";\ninline constexpr std::string_view version = \"${_version_cpp}\";\ninline constexpr std::string_view revision = \"${_revision_cpp}\";\ninline constexpr std::string_view compiler = \"${_compiler_cpp}\";\ninline constexpr bool dirty = ${_dirty};\n}\n")
  if(NOT TARGET boilerplate_build_info)
    add_library(boilerplate_build_info INTERFACE)
    add_library(boilerplate::build_info ALIAS boilerplate_build_info)
    target_include_directories(boilerplate_build_info INTERFACE "$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/generated>")
  endif()

  if(BOILERPLATE_INSTALL)
    install(FILES "${_output}" DESTINATION "${CMAKE_INSTALL_DATADIR}/${CMAKE_PROJECT_NAME}"
      COMPONENT Runtime)
    install(FILES "${_header}" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/boilerplate"
      COMPONENT Development)
  endif()
endfunction()
