cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "Pass -DCHECK_BINARY=<temporary build directory>")
endif()
get_filename_component(_toolkit "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Command failed: ${ARGV}\n${output}\n${error}")
  endif()
endfunction()
set(_source "${CHECK_BINARY}/capability-source")
set(_build "${CHECK_BINARY}/capability-build")
file(MAKE_DIRECTORY "${_source}/src")
file(WRITE "${_source}/src/main.cpp" "/// @file\n\n/// Smoke executable.\n/// @return Zero on success.\nint main() { return 0; }\n")
file(WRITE "${_source}/src/disabled.cpp" "#error This source is not part of a target\n")
file(WRITE "${_source}/probe.cu" "__global__ void capability_kernel() {}\n")
file(WRITE "${_source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.26)
project(CapabilityProbe VERSION 1.0 LANGUAGES CXX)
include(CTest)
include("${TOOLKIT_DIR}/Boilerplate.cmake")
set(_tool "${CMAKE_COMMAND}" CACHE FILEPATH "Legacy shared tool entry" FORCE)
boilerplate_project_tool(_cmake "CMake probe" NAMES cmake)
boilerplate_project_tool(_ctest "CTest probe" NAMES ctest)
boilerplate_project_tool(_absent "Missing tool probe" NAMES boilerplate-no-such-tool)
if(NOT _cmake OR NOT _ctest OR _cmake STREQUAL _ctest OR _absent)
  message(FATAL_ERROR "Tool lookups reused another capability's result")
endif()
set(_caps compile-commands coverage-report static-analysis build-info diagnostics)
if(CHECK_CUDA)
  list(APPEND _caps cuda)
endif()
if(CHECK_DOCS)
  list(APPEND _caps docs)
  set(BOILERPLATE_DOC_INPUTS "${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp")
endif()
boilerplate_project(CAPABILITIES ${_caps})
boilerplate_project_has_capability(testing _testing)
if(NOT _testing)
  message(FATAL_ERROR "coverage-report did not inherit testing")
endif()
boilerplate_add_test(capability_probe SOURCES src/main.cpp)
if(CHECK_CUDA)
  add_library(cuda_probe STATIC probe.cu)
  add_dependencies(boilerplate_tests cuda_probe)
endif()
boilerplate_finalize_project()
]=])
set(_compiler_args)
if(CHECK_COMPILER)
  list(APPEND _compiler_args "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}")
endif()
run("${CMAKE_COMMAND}" -S "${_source}" -B "${_build}" -G Ninja
  "-DTOOLKIT_DIR=${_toolkit}" ${_compiler_args}
  "-DCHECK_CUDA=${CHECK_CUDA}" "-DCHECK_DOCS=${CHECK_DOCS}"
  "-DBOILERPLATE_COVERAGE=${CHECK_COVERAGE}" -DBOILERPLATE_COMPILER_CACHE=none)
file(READ "${_build}/build.ninja" _ninja)
if(_ninja MATCHES "COMMAND = [^\n]*disabled\\.cpp")
  message(FATAL_ERROR "Static analysis includes a disabled source")
endif()
run("${CMAKE_COMMAND}" --build "${_build}" --target boilerplate_check --parallel 2)
if(CHECK_DOCS)
  run("${CMAKE_COMMAND}" --build "${_build}" --target docs)
  if(NOT EXISTS "${_build}/html/index.html")
    message(FATAL_ERROR "Documentation did not generate index.html")
  endif()
  # Verify strict defaults still detect malformed documentation.
  file(APPEND "${_source}/src/main.cpp" "\n/** @page invalid Broken link\n * @ref no_such_symbol_in_this_fixture\n */\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target docs
    RESULT_VARIABLE _bad_docs OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
  if(_bad_docs EQUAL 0 OR NOT "${_output}\n${_error}" MATCHES "no_such_symbol_in_this_fixture")
    message(FATAL_ERROR "Strict documentation did not reject an unresolved reference")
  endif()
endif()
if(CHECK_COVERAGE)
  run("${CMAKE_COMMAND}" --build "${_build}" --target coverage-report)
  if(NOT EXISTS "${_build}/coverage/html/index.html")
    message(FATAL_ERROR "Coverage did not generate index.html")
  endif()
endif()
message(STATUS "Generic capability checks passed")
