cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "Pass CHECK_BINARY")
endif()
get_filename_component(_root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(_fixture "${CMAKE_CURRENT_LIST_DIR}/cross")
file(MAKE_DIRECTORY "${CHECK_BINARY}/target/bin" "${CHECK_BINARY}/target/usr/lib/cmake/TargetOnly"
  "${CHECK_BINARY}/host/lib/cmake/HostOnly")
file(COPY "${CMAKE_COMMAND}" DESTINATION "${CHECK_BINARY}/target/bin")
file(WRITE "${CHECK_BINARY}/host/lib/cmake/HostOnly/HostOnlyConfig.cmake" "set(HostOnly_FOUND TRUE)\n")
file(WRITE "${CHECK_BINARY}/target/usr/lib/cmake/TargetOnly/TargetOnlyConfig.cmake" "set(TargetOnly_FOUND TRUE)\n")
if(NOT CHECK_TOOLCHAIN)
  if(NOT CHECK_COMPILER)
    find_program(CHECK_COMPILER NAMES c++ g++ clang++ REQUIRED)
  endif()
  set(CHECK_TOOLCHAIN "${CHECK_BINARY}/semantic-toolchain.cmake")
  file(WRITE "${CHECK_TOOLCHAIN}" "set(CMAKE_SYSTEM_NAME ${CMAKE_HOST_SYSTEM_NAME})\nset(CMAKE_SYSTEM_PROCESSOR semantic-cross)\nset(CMAKE_CXX_COMPILER [==[${CHECK_COMPILER}]==])\ninclude([==[${_root}/toolchains/TargetRoots.cmake]==])\n")
  set(_semantic TRUE)
endif()
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
function(reject)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_rc STREQUAL "0" OR NOT "${_out}${_err}" MATCHES "CROSSCOMPILING_EMULATOR|ENABLE_NATIVE")
    message(FATAL_ERROR "Expected cross-execution diagnostic: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
set(_args "-DCMAKE_TOOLCHAIN_FILE=${CHECK_TOOLCHAIN}" "-DTOOLKIT_DIR=${_root}/lib/cmake"
  "-DCMAKE_FIND_ROOT_PATH=${CHECK_BINARY}/target" "-DCMAKE_PREFIX_PATH=${CHECK_BINARY}/host"
  -DCMAKE_BUILD_TYPE=Release -DBOILERPLATE_BUILD_SHARED=OFF -DBOILERPLATE_BUILD_STATIC=ON
  -DBOILERPLATE_PACKAGE_GENERATORS=TGZ -DBOILERPLATE_COMPILER_CACHE=none)
set(_build "${CHECK_BINARY}/build")
run("${CMAKE_COMMAND}" -S "${_fixture}" -B "${_build}" -G Ninja ${_args})
run("${CMAKE_COMMAND}" --build "${_build}")
if(NOT EXISTS "${_build}/host-generated.txt")
  message(FATAL_ERROR "Host code generator did not run")
endif()
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${_build}" --show-only=json-v1
  RESULT_VARIABLE _rc OUTPUT_VARIABLE _tests)
if(NOT _rc STREQUAL "0" OR NOT _tests MATCHES "DISABLED")
  message(FATAL_ERROR "Cross tests must be visible but disabled without an emulator")
endif()
run("${CMAKE_CTEST_COMMAND}" --test-dir "${_build}" --output-on-failure)
reject("${CMAKE_COMMAND}" --build "${_build}" --target run_probe)
reject("${CMAKE_COMMAND}" --build "${_build}" --target run_matrix)
reject("${CMAKE_COMMAND}" --build "${_build}" --target boilerplate_pgo_train)
run("${CMAKE_COMMAND}" --install "${_build}" --prefix "${CHECK_BINARY}/target/usr")
run("${CMAKE_COMMAND}" --build "${_build}" --target package)
file(GLOB _packages "${_build}/*.tar.gz")
if(NOT _packages)
  message(FATAL_ERROR "Cross package was not produced")
endif()
run("${CMAKE_COMMAND}" -S "${_fixture}/consumer" -B "${CHECK_BINARY}/consumer" -G Ninja ${_args})
run("${CMAKE_COMMAND}" --build "${CHECK_BINARY}/consumer")
run("${CMAKE_COMMAND}" --build "${_build}" --target cross_reference)
reject("${CMAKE_COMMAND}" -S "${_fixture}" -B "${CHECK_BINARY}/native-policy" -G Ninja ${_args} -DTEST_NATIVE_POLICY=ON)
if(CHECK_ARCH STREQUAL aarch64)
  file(READ "${_build}/target-path.txt" _target_path)
  file(READ "${_target_path}" _header OFFSET 18 LIMIT 2 HEX)
  if(NOT _header STREQUAL "b700")
    message(FATAL_ERROR "Target executable is not AArch64 ELF: ${_header}")
  endif()
endif()
if(_semantic)
  set(_emulator "${CMAKE_COMMAND};-E;env;CROSS_TEST_EMULATED=1")
elseif(CHECK_EMULATOR)
  set(_emulator "${CHECK_EMULATOR}")
endif()
if(_emulator)
  # Keep the emulator list as ONE -D argument, including its arguments.
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_fixture}" -B "${CHECK_BINARY}/emulated" -G Ninja ${_args}
    "-DCMAKE_CROSSCOMPILING_EMULATOR=${_emulator}" "-DEXPECT_EMULATOR=${_semantic}"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "Emulated configure failed: ${_out}\n${_err}")
  endif()
  run("${CMAKE_COMMAND}" --build "${CHECK_BINARY}/emulated" --target cross_probe run_probe run_matrix boilerplate_pgo_train)
  run("${CMAKE_CTEST_COMMAND}" --test-dir "${CHECK_BINARY}/emulated" --output-on-failure)
endif()
message(STATUS "Cross configure/build/install/package/consumer, host isolation and execution checks passed")
