cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY)
  message(FATAL_ERROR "Pass CHECK_BINARY")
endif()
get_filename_component(toolkit "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
if(NOT CHECK_COMPILER)
  find_program(CHECK_COMPILER clang++ REQUIRED)
endif()
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT "${rc}" STREQUAL "0")
    message(FATAL_ERROR "${ARGV}: ${out}\n${err}")
  endif()
endfunction()
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/fuzz/seeds/safe" before)
run("${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/fuzz" -B "${CHECK_BINARY}" -G Ninja
  "-DTOOLKIT_DIR=${toolkit}" "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}"
  -DBOILERPLATE_FUZZ_SMOKE_LABEL=fixture-fuzz -DBOILERPLATE_FUZZ_SANITIZER=undefined)
run("${CMAKE_COMMAND}" --build "${CHECK_BINARY}" --parallel 2)
run("${CMAKE_COMMAND}" --build "${CHECK_BINARY}" --target fuzz-smoke)
file(READ "${CHECK_BINARY}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON cmd GET "${commands}" ${i} command)
  if(cmd MATCHES "instrumented.dir" AND NOT cmd MATCHES "fsanitize=fuzzer-no-link")
    message(FATAL_ERROR "Fuzz library lacks coverage instrumentation")
  endif()
  if(cmd MATCHES "normal.dir" AND cmd MATCHES "fsanitize")
    message(FATAL_ERROR "Fuzz instrumentation leaked to normal library")
  endif()
endforeach()
# The UB is in the separately compiled library, not the fuzzer driver.
string(ASCII 255 crashing_byte)
file(WRITE "${CHECK_BINARY}/overflow" "${crashing_byte}")
execute_process(COMMAND "${CHECK_BINARY}/driver" "${CHECK_BINARY}/overflow" -runs=1
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
if("${rc}" STREQUAL "0" OR NOT err MATCHES "signed integer overflow")
  message(FATAL_ERROR "Library UB was not detected: ${rc}\n${out}\n${err}")
endif()
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/fuzz/seeds/safe" after)
if(NOT before STREQUAL after OR EXISTS "${CMAKE_CURRENT_LIST_DIR}/fuzz/seeds/boilerplate-seed")
  message(FATAL_ERROR "Read-only seed corpus was modified")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/fuzz"
  -B "${CHECK_BINARY}/mismatch" -G Ninja "-DTOOLKIT_DIR=${toolkit}"
  "-DCMAKE_CXX_COMPILER=${CHECK_COMPILER}" -DMISMATCH=ON
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if("${rc}" STREQUAL "0" OR NOT err MATCHES "matching backend and[ \n]+sanitizer")
  message(FATAL_ERROR "Mismatched fuzz instrumentation was not rejected: ${out}\n${err}")
endif()
message(STATUS "Fuzz archive instrumentation, sanitizer failure, seeds, smoke and mismatch checks passed")
