include_guard(GLOBAL)

# Generate an overlay port at configure time. Local ports reference the checkout;
# URL ports are portable and use a pinned source archive.
function(boilerplate_vcpkg_port name)
  cmake_parse_arguments(PARSE_ARGV 1 ARG ""
    "VERSION;DESCRIPTION;HOMEPAGE;SPDX_LICENSE;LICENSE_FILE;SOURCE_DIR;SOURCE_SUBDIR;URL;SHA512;OUTPUT_DIRECTORY"
    "PACKAGES;DEPENDENCIES;OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "boilerplate_vcpkg_port: unknown or incomplete arguments")
  endif()
  if(NOT name MATCHES "^[a-z0-9]+(-[a-z0-9]+)*$")
    message(FATAL_ERROR "boilerplate_vcpkg_port: use a lowercase vcpkg port name")
  endif()
  if(NOT ARG_VERSION)
    set(ARG_VERSION "${PROJECT_VERSION}")
  endif()
  if(NOT ARG_VERSION OR NOT ARG_PACKAGES OR NOT ARG_LICENSE_FILE)
    message(FATAL_ERROR "boilerplate_vcpkg_port requires VERSION, PACKAGES and LICENSE_FILE")
  endif()
  if(ARG_URL)
    string(LENGTH "${ARG_SHA512}" _hash_length)
    if(NOT _hash_length EQUAL 128 OR NOT ARG_SHA512 MATCHES "^[a-fA-F0-9]+$")
      message(FATAL_ERROR "URL requires a 128-digit SHA512")
    endif()
    if(ARG_SOURCE_DIR)
      message(FATAL_ERROR "Use either URL or SOURCE_DIR")
    endif()
    set(_source "vcpkg_download_distfile(ARCHIVE\n  URLS [==[${ARG_URL}]==]\n  FILENAME [==[${name}-${ARG_VERSION}.tar.gz]==]\n  SHA512 ${ARG_SHA512})\nvcpkg_extract_source_archive(SOURCE_PATH ARCHIVE \"\${ARCHIVE}\")")
  else()
    if(ARG_SHA512)
      message(FATAL_ERROR "SHA512 requires URL")
    endif()
    if(NOT ARG_SOURCE_DIR)
      set(ARG_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
    get_filename_component(ARG_SOURCE_DIR "${ARG_SOURCE_DIR}" ABSOLUTE)
    set(_source "set(SOURCE_PATH [==[${ARG_SOURCE_DIR}]==])")
  endif()
  foreach(_relative IN ITEMS ARG_SOURCE_SUBDIR ARG_LICENSE_FILE)
    if(IS_ABSOLUTE "${${_relative}}" OR "${${_relative}}" MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "${_relative} must be relative to the source root without '..'")
    endif()
  endforeach()
  if(NOT ARG_OUTPUT_DIRECTORY)
    set(ARG_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/vcpkg-ports")
  endif()
  set(_port "${ARG_OUTPUT_DIRECTORY}/${name}")
  file(MAKE_DIRECTORY "${_port}")
  set(_manifest "{}")
  foreach(_field IN ITEMS name version-string description homepage license)
    if(_field STREQUAL "name")
      set(_value "${name}")
    elseif(_field STREQUAL "version-string")
      set(_value "${ARG_VERSION}")
    elseif(_field STREQUAL "license")
      set(_value "${ARG_SPDX_LICENSE}")
    else()
      string(TOUPPER "${_field}" _key)
      set(_value "${ARG_${_key}}")
    endif()
    if(NOT _value STREQUAL "")
      string(REPLACE "\\" "\\\\" _value "${_value}")
      string(REPLACE "\"" "\\\"" _value "${_value}")
      string(REPLACE "\n" "\\n" _value "${_value}")
      string(REPLACE "\r" "\\r" _value "${_value}")
      string(REPLACE "\t" "\\t" _value "${_value}")
      string(JSON _manifest SET "${_manifest}" "${_field}" "\"${_value}\"")
    endif()
  endforeach()
  set(_deps "[{\"name\":\"vcpkg-cmake\",\"host\":true},{\"name\":\"vcpkg-cmake-config\",\"host\":true}]")
  foreach(_dep IN LISTS ARG_DEPENDENCIES)
    if(NOT _dep MATCHES "^[a-z0-9]+(-[a-z0-9]+)*$")
      message(FATAL_ERROR "DEPENDENCIES accepts vcpkg port names: ${_dep}")
    endif()
    string(JSON _length LENGTH "${_deps}")
    string(JSON _deps SET "${_deps}" ${_length} "\"${_dep}\"")
  endforeach()
  string(JSON _manifest SET "${_manifest}" dependencies "${_deps}")
  file(WRITE "${_port}/vcpkg.json" "${_manifest}\n")
  set(_options "")
  foreach(_option IN LISTS ARG_OPTIONS)
    string(APPEND _options "\n    [==[${_option}]==]")
  endforeach()
  set(_fixup "")
  set(_usage "")
  foreach(_package IN LISTS ARG_PACKAGES)
    if(NOT _package MATCHES "^[A-Za-z0-9_-]+$")
      message(FATAL_ERROR "Invalid CMake package name: ${_package}")
    endif()
    string(APPEND _fixup "vcpkg_cmake_config_fixup(PACKAGE_NAME ${_package} CONFIG_PATH lib/cmake/${_package})\n")
    string(APPEND _usage "    find_package(${_package} CONFIG REQUIRED)\n    target_link_libraries(main PRIVATE ${_package}::${_package})\n")
  endforeach()
  configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VcpkgPortfile.cmake.in" "${_port}/portfile.cmake" @ONLY)
  file(WRITE "${_port}/usage" "${name} provides CMake targets:\n\n${_usage}")
endfunction()
