if(MODE STREQUAL "fail")
  message(FATAL_ERROR "Intentional harness fixture failure")
elseif(MODE STREQUAL "timeout")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 3)
else()
  if(NOT WORDS STREQUAL "two words" OR NOT "$ENV{HARNESS_FIXTURE}" STREQUAL "space value")
    message(FATAL_ERROR "Arguments/environment were not preserved")
  endif()
  if(NOT EXISTS cwd-marker)
    message(FATAL_ERROR "Working directory was not preserved")
  endif()
  message("fixture passed")
endif()
