include_guard(GLOBAL)

# Provision only inside the build tree (or an explicitly selected cache). The
# official toolchain bootstraps the vcpkg executable and installs the manifest.
option(BOILERPLATE_VCPKG_BOOTSTRAP "Provision pinned vcpkg instead of searching implicit installations" OFF)
set(BOILERPLATE_VCPKG_REPOSITORY "https://github.com/microsoft/vcpkg.git" CACHE STRING "vcpkg Git repository or local mirror")
set(BOILERPLATE_VCPKG_REVISION "" CACHE STRING "Pinned vcpkg commit; empty uses manifest builtin-baseline")
set(BOILERPLATE_VCPKG_CACHE "${CMAKE_BINARY_DIR}/_deps" CACHE PATH "Managed vcpkg checkout directory")

function(boilerplate_provision_vcpkg output source_dir)
  set(_revision "${BOILERPLATE_VCPKG_REVISION}")
  if(NOT _revision AND EXISTS "${source_dir}/vcpkg.json")
    file(READ "${source_dir}/vcpkg.json" _manifest)
    string(JSON _revision ERROR_VARIABLE _error GET "${_manifest}" builtin-baseline)
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-fA-F]+$")
    message(FATAL_ERROR "vcpkg bootstrap requires a 40-digit commit in BOILERPLATE_VCPKG_REVISION or manifest builtin-baseline")
  endif()
  get_filename_component(_cache "${BOILERPLATE_VCPKG_CACHE}" ABSOLUTE BASE_DIR "${CMAKE_BINARY_DIR}")
  set(_root "${_cache}/vcpkg-${_revision}")
  file(MAKE_DIRECTORY "${_cache}")
  file(LOCK "${_root}.lock" GUARD FUNCTION TIMEOUT 600 RESULT_VARIABLE _lock)
  if(NOT _lock STREQUAL "0")
    message(FATAL_ERROR "Cannot lock managed vcpkg checkout: ${_lock}")
  endif()
  if(EXISTS "${_root}/.boilerplate-ready" AND EXISTS "${_root}/scripts/buildsystems/vcpkg.cmake")
    set(${output} "${_root}" PARENT_SCOPE)
    return()
  endif()
  find_program(_boilerplate_git git REQUIRED NO_CMAKE_FIND_ROOT_PATH)
  set(_staging "${_root}.tmp")
  file(REMOVE_RECURSE "${_staging}")
  file(MAKE_DIRECTORY "${_staging}")
  message(STATUS "Boilerplate: provisioning vcpkg ${_revision} in ${_root}")
  foreach(_step IN ITEMS init remote fetch checkout)
    if(_step STREQUAL "init")
      set(_args init)
    elseif(_step STREQUAL "remote")
      set(_args remote add origin "${BOILERPLATE_VCPKG_REPOSITORY}")
    elseif(_step STREQUAL "fetch")
      set(_args fetch --depth 1 origin "${_revision}")
    else()
      set(_args checkout --detach "${_revision}")
    endif()
    execute_process(COMMAND "${_boilerplate_git}" ${_args}
      WORKING_DIRECTORY "${_staging}" TIMEOUT 600
      RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    file(APPEND "${_root}.log" "${_step}: ${_result}\n${_out}\n${_err}\n")
    if(NOT _result STREQUAL "0")
      message(FATAL_ERROR
        "vcpkg ${_step} failed: ${_err}\nSee ${_root}.log. "
        "Retry with network access, use BOILERPLATE_VCPKG_REPOSITORY for a mirror, "
        "or supply BOILERPLATE_VCPKG_ROOT for an existing offline checkout.")
    endif()
  endforeach()
  if(NOT EXISTS "${_staging}/scripts/buildsystems/vcpkg.cmake")
    message(FATAL_ERROR "Pinned repository is not vcpkg: missing scripts/buildsystems/vcpkg.cmake")
  endif()
  file(WRITE "${_staging}/.boilerplate-ready" "${_revision}\n")
  file(REMOVE_RECURSE "${_root}")
  file(RENAME "${_staging}" "${_root}")
  set(${output} "${_root}" PARENT_SCOPE)
endfunction()
