# Copy this directory into any C++ project; include after project().
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/BuildProfiles.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ProjectCapabilities.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ProjectOptions.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/TargetPolicies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/RuntimePolicies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/QtPolicies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GraphicsPolicies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/TargetOptions.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Library.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Plugins.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Deployment.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Scenarios.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Workloads.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Harness.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/BuildInfo.cmake")
