include_guard(GLOBAL)

function(_boilerplate_control_flow_flags target compile_out link_out)
  foreach(_key IN ITEMS CFI CFI_DIAGNOSTICS WINDOWS_CFG)
    boilerplate_get_target_setting(${target} ${_key} _${_key})
  endforeach()
  set(_compile)
  set(_link)
  if(NOT _CFI STREQUAL "none")
    list(APPEND _compile "-fsanitize=${_CFI}")
    list(APPEND _link "-fsanitize=${_CFI}")
    if(NOT _CFI STREQUAL "cfi-icall")
      list(APPEND _compile -fvisibility=hidden)
    endif()
    if(_CFI_DIAGNOSTICS)
      list(APPEND _compile -fno-sanitize-trap=cfi -fno-sanitize-recover=cfi)
      list(APPEND _link -fno-sanitize-trap=cfi -fno-sanitize-recover=cfi)
    else()
      list(APPEND _compile -fsanitize-trap=cfi)
      list(APPEND _link -fsanitize-trap=cfi)
    endif()
  endif()
  if(_WINDOWS_CFG)
    list(APPEND _compile /guard:cf)
    list(APPEND _link /GUARD:CF /DYNAMICBASE)
  endif()
  set(${compile_out} "${_compile}" PARENT_SCOPE)
  set(${link_out} "${_link}" PARENT_SCOPE)
endfunction()

function(_boilerplate_validate_control_flow target)
  foreach(_key IN ITEMS CFI CFI_DIAGNOSTICS WINDOWS_CFG LTO_MODE USE_LLD SANITIZER)
    boilerplate_get_target_setting(${target} ${_key} _${_key})
  endforeach()
  if(NOT _CFI MATCHES "^(none|cfi|cfi-icall|cfi-vcall)$")
    message(FATAL_ERROR "Target ${target}: invalid CFI=${_CFI}; expected none, cfi, cfi-icall or cfi-vcall")
  endif()
  if(_CFI STREQUAL "none" AND NOT _WINDOWS_CFG)
    return()
  endif()
  if(NOT _CFI STREQUAL "none")
    if(_WINDOWS_CFG)
      message(FATAL_ERROR "Target ${target}: Clang CFI and Windows CFG cannot be combined")
    endif()
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR MSVC OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      message(FATAL_ERROR "Target ${target}: CFI currently requires GNU-style Clang on Linux; Windows uses windows-cfg")
    endif()
    if(NOT _LTO_MODE MATCHES "^(thin|full)$")
      message(FATAL_ERROR "Target ${target}: CFI requires LTO_MODE=thin or full")
    endif()
  endif()
  if(_WINDOWS_CFG)
    if(NOT WIN32 OR NOT MSVC)
      message(FATAL_ERROR "Target ${target}: windows-cfg requires MSVC or clang-cl on Windows")
    endif()
    get_target_property(_debug_format ${target} MSVC_DEBUG_INFORMATION_FORMAT)
    set(_flags "${CMAKE_CXX_FLAGS}")
    foreach(_config IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
      string(APPEND _flags " ${CMAKE_CXX_FLAGS_${_config}}")
    endforeach()
    if(_debug_format MATCHES "EditAndContinue" OR _flags MATCHES "(^| )[-/]ZI( |$)|(^| )[-/]clr(:[^ ]*)?( |$)")
      message(FATAL_ERROR "Target ${target}: windows-cfg is incompatible with /ZI (EditAndContinue) and /clr")
    endif()
  endif()

  # Check compilation AND final linking. Compiler-flag checks alone miss absent
  # LTO linkers/plugins and incompatible sanitizer runtimes. No binary is run.
  _boilerplate_control_flow_flags(${target} _compile _link)
  if(NOT _CFI STREQUAL "none")
    list(APPEND _compile "-flto=${_LTO_MODE}")
    list(APPEND _link "-flto=${_LTO_MODE}")
    if(_USE_LLD)
      list(APPEND _link -fuse-ld=lld)
    endif()
    if(NOT _SANITIZER STREQUAL "none")
      string(REPLACE "address-undefined" "address,undefined" _san "${_SANITIZER}")
      list(APPEND _compile "-fsanitize=${_san}")
      list(APPEND _link "-fsanitize=${_san}")
    endif()
  endif()
  include(CheckCXXSourceCompiles)
  include(CMakePushCheckState)
  cmake_push_check_state(RESET)
  string(JOIN " " CMAKE_REQUIRED_FLAGS ${_compile})
  set(CMAKE_REQUIRED_LINK_OPTIONS ${_link})
  set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
  set(_context "${CMAKE_CXX_COMPILER};${CMAKE_CXX_COMPILER_VERSION};${CMAKE_CXX_COMPILER_TARGET};${CMAKE_SYSROOT};${CMAKE_BUILD_TYPE};${CMAKE_MSVC_RUNTIME_LIBRARY};${CMAKE_MSVC_DEBUG_INFORMATION_FORMAT}")
  foreach(_suffix IN ITEMS "" _DEBUG _RELEASE _RELWITHDEBINFO _MINSIZEREL)
    string(APPEND _context ";${CMAKE_CXX_FLAGS${_suffix}};${CMAKE_EXE_LINKER_FLAGS${_suffix}}")
  endforeach()
  string(SHA256 _hash "${_context};${_compile};${_link}")
  set(_check "BOILERPLATE_CONTROL_FLOW_${_hash}")
  check_cxx_source_compiles("int identity(int x) { return x; }
    int main() { int (*volatile call)(int) = identity; return call(0); }" ${_check})
  cmake_pop_check_state()
  if(NOT ${_check})
    message(FATAL_ERROR
      "Target ${target}: control-flow protection compile/link check failed. "
      "Check the selected compiler, LTO linker and sanitizer runtimes in CMake's configure log.")
  endif()
endfunction()

function(_boilerplate_apply_control_flow target)
  _boilerplate_control_flow_flags(${target} _compile _link)
  if(NOT _compile)
    return()
  endif()
  target_compile_options(${target} PRIVATE ${_compile})
  get_target_property(_type ${target} TYPE)
  if(_type MATCHES "^(STATIC_LIBRARY|OBJECT_LIBRARY)$")
    # The archive has no link step: its eventual consumer needs these options.
    target_link_options(${target} INTERFACE ${_link})
  else()
    # Shared libraries protect their own link unit, not arbitrary DSO callers.
    target_link_options(${target} PRIVATE ${_link})
    boilerplate_get_target_setting(${target} CFI _cfi)
    boilerplate_get_target_setting(${target} CFI_DIAGNOSTICS _diagnostics)
    if(_type STREQUAL "SHARED_LIBRARY" AND NOT _cfi STREQUAL "none" AND _diagnostics)
      # Clang leaves diagnostic-runtime symbols unresolved in a DSO. Pull in
      # UBSan's runtime at the final executable link without instrumenting the
      # consumer or claiming cross-DSO CFI protection.
      target_link_options(${target} INTERFACE -fsanitize=undefined)
    endif()
  endif()
endfunction()
