include_guard(GLOBAL)
include(GNUInstallDirs)

function(_boilerplate_deploy_rpath target destination library_destination)
  file(RELATIVE_PATH _relative "/${destination}" "/${library_destination}")
  if(APPLE)
    set(_origin "@loader_path")
  elseif(UNIX)
    set(_origin "$ORIGIN")
  else()
    return()
  endif()
  set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH "${_origin}" "${_origin}/${_relative}")
endfunction()

# Owned shared dependencies must be named in LIBRARIES (including transitive
# ones). CMake's runtime scanner handles external libraries, not owned targets.
function(boilerplate_install_application target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "NO_RUNTIME_DEPENDENCIES" ""
    "LIBRARIES;PLUGINS;RESOURCE_DIRS;RUNTIME_DIRS;PRE_EXCLUDE_REGEXES;POST_EXCLUDE_REGEXES")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT TARGET ${target})
    message(FATAL_ERROR "boilerplate_install_application(${target}): invalid arguments")
  endif()
  if(NOT BOILERPLATE_INSTALL)
    return()
  endif()
  get_target_property(_type ${target} TYPE)
  get_target_property(_done ${target} BOILERPLATE_DEPLOYMENT)
  if(NOT _type STREQUAL "EXECUTABLE" OR _done)
    message(FATAL_ERROR "Deployment requires an executable registered only once: ${target}")
  endif()
  if(CMAKE_CROSSCOMPILING AND NOT ARG_NO_RUNTIME_DEPENDENCIES)
    message(FATAL_ERROR "Cross deployment requires NO_RUNTIME_DEPENDENCIES and explicit target-platform packaging")
  endif()
  foreach(_dir IN ITEMS CMAKE_INSTALL_BINDIR CMAKE_INSTALL_LIBDIR CMAKE_INSTALL_DATADIR)
    if(IS_ABSOLUTE "${${_dir}}" OR "${${_dir}}" MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "Relocatable deployment requires a relative ${_dir}")
    endif()
  endforeach()
  set_property(TARGET ${target} PROPERTY BOILERPLATE_DEPLOYMENT TRUE)
  set(_set "${target}_runtime_dependencies")
  set(_set_args)
  if(NOT ARG_NO_RUNTIME_DEPENDENCIES)
    set(_set_args RUNTIME_DEPENDENCY_SET "${_set}")
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      find_program(BOILERPLATE_PATCHELF patchelf REQUIRED)
    endif()
  endif()
  set(_plugins "${CMAKE_INSTALL_LIBDIR}/${target}/plugins")
  set(_resources "${CMAKE_INSTALL_DATADIR}/${target}")
  _boilerplate_deploy_rpath(${target} "${CMAKE_INSTALL_BINDIR}" "${CMAKE_INSTALL_LIBDIR}")
  install(TARGETS ${target} ${_set_args}
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime)
  foreach(_dependency IN LISTS ARG_LIBRARIES ARG_PLUGINS)
    if(NOT TARGET ${_dependency})
      message(FATAL_ERROR "Deployment dependency is not a target: ${_dependency}")
    endif()
    get_target_property(_real ${_dependency} ALIASED_TARGET)
    if(NOT _real)
      set(_real "${_dependency}")
    endif()
    get_target_property(_kind ${_real} TYPE)
    get_target_property(_imported ${_real} IMPORTED)
    if(_dependency IN_LIST ARG_PLUGINS)
      if(NOT _kind STREQUAL "MODULE_LIBRARY")
        message(FATAL_ERROR "PLUGINS requires MODULE libraries: ${_dependency}")
      endif()
      set(_destination "${_plugins}")
      set(_runtime_destination "${_plugins}")
    else()
      if(NOT _kind STREQUAL "SHARED_LIBRARY")
        message(FATAL_ERROR "LIBRARIES requires shared libraries: ${_dependency}")
      endif()
      set(_destination "${CMAKE_INSTALL_LIBDIR}")
      set(_runtime_destination "${CMAKE_INSTALL_BINDIR}")
    endif()
    if(_imported)
      install(IMPORTED_RUNTIME_ARTIFACTS ${_real} ${_set_args}
        RUNTIME DESTINATION "${_runtime_destination}" COMPONENT Runtime
        LIBRARY DESTINATION "${_destination}" COMPONENT Runtime)
    else()
      _boilerplate_deploy_rpath(${_real} "${_destination}" "${CMAKE_INSTALL_LIBDIR}")
      install(TARGETS ${_real} ${_set_args}
        RUNTIME DESTINATION "${_runtime_destination}" COMPONENT Runtime
        LIBRARY DESTINATION "${_destination}" COMPONENT Runtime NAMELINK_SKIP)
      add_dependencies(${target} ${_real})
    endif()
    list(APPEND ARG_RUNTIME_DIRS "$<TARGET_FILE_DIR:${_real}>")
  endforeach()
  if(NOT ARG_NO_RUNTIME_DEPENDENCIES)
    # Keep third-party libraries even when found under /usr/lib. Only OS/ABI
    # components are excluded by default; caller exclusions extend this list.
    set(_pre "api-ms-.*" "ext-ms-.*")
    set(_post)
    if(WIN32)
      list(APPEND _post ".*[/\\\\][Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\][Ss][Yy][Ss][Tt][Ee][Mm]32[/\\\\].*")
    elseif(APPLE)
      list(APPEND _post "^/System/Library/" "^/usr/lib/")
    else()
      list(APPEND _pre "^linux-vdso" "^ld-linux" "^ld64\\." "^lib(c|m|pthread|dl|rt|resolv|util)\\.so(\\.|$)")
    endif()
    install(RUNTIME_DEPENDENCY_SET "${_set}"
      DIRECTORIES ${ARG_RUNTIME_DIRS}
      PRE_EXCLUDE_REGEXES ${_pre} ${ARG_PRE_EXCLUDE_REGEXES}
      POST_EXCLUDE_REGEXES ${_post} ${ARG_POST_EXCLUDE_REGEXES}
      RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime
      LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Runtime
      FRAMEWORK DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Runtime)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      set(_fixup [=[
set(_boilerplate_new_files "${CMAKE_INSTALL_MANIFEST_FILES}")
list(REMOVE_DUPLICATES _boilerplate_new_files)
foreach(_file IN LISTS _boilerplate_new_files)
  get_filename_component(_parent "${_file}" DIRECTORY)
  if(_parent STREQUAL "${CMAKE_INSTALL_PREFIX}/@CMAKE_INSTALL_LIBDIR@" AND
      _file MATCHES "[.]so([.][^/]*)?$" AND
      NOT IS_SYMLINK "$ENV{DESTDIR}${_file}")
    execute_process(COMMAND "@BOILERPLATE_PATCHELF@" --set-rpath "$ORIGIN" "$ENV{DESTDIR}${_file}"
      RESULT_VARIABLE _result ERROR_VARIABLE _error)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot make installed dependency relocatable: ${_file}: ${_error}")
    endif()
  endif()
endforeach()
]=])
      string(CONFIGURE "${_fixup}" _fixup @ONLY)
      install(CODE "${_fixup}" COMPONENT Runtime)
    endif()
  endif()
  foreach(_dir IN LISTS ARG_RESOURCE_DIRS)
    get_filename_component(_dir "${_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT IS_DIRECTORY "${_dir}")
      message(FATAL_ERROR "Resource directory does not exist: ${_dir}")
    endif()
    install(DIRECTORY "${_dir}/" DESTINATION "${_resources}" COMPONENT Runtime)
  endforeach()
  get_target_property(_shader_dirs ${target} BOILERPLATE_SHADER_DIRECTORIES)
  if(_shader_dirs)
    list(REMOVE_DUPLICATES _shader_dirs)
    foreach(_dir IN LISTS _shader_dirs)
      install(DIRECTORY "${_dir}/" DESTINATION "${_resources}/shaders" COMPONENT Runtime
        FILES_MATCHING PATTERN "*.spv" PATTERN "*.dxil")
    endforeach()
  endif()
  set_target_properties(${target} PROPERTIES
    BOILERPLATE_INSTALL_PLUGIN_DIR "${_plugins}" BOILERPLATE_INSTALL_RESOURCE_DIR "${_resources}")
endfunction()
