include_guard(GLOBAL)

set(BOILERPLATE_IMGUI_TARGET "" CACHE STRING
  "Existing ImGui target to link; empty auto-detects imgui::imgui, ImGui::ImGui or imgui")

function(_boilerplate_graphics_vulkan target)
  if(NOT TARGET Vulkan::Vulkan)
    find_package(Vulkan REQUIRED)
  endif()
  target_link_libraries(${target} PRIVATE Vulkan::Vulkan)
endfunction()

function(_boilerplate_graphics_glfw target)
  if(NOT TARGET glfw AND NOT TARGET glfw3::glfw)
    find_package(glfw3 CONFIG QUIET)
    if(NOT TARGET glfw AND NOT TARGET glfw3::glfw)
      find_package(glfw3 REQUIRED)
    endif()
  endif()
  if(TARGET glfw3::glfw)
    target_link_libraries(${target} PRIVATE glfw3::glfw)
  elseif(TARGET glfw)
    target_link_libraries(${target} PRIVATE glfw)
  else()
    message(FATAL_ERROR "GLFW was found but did not provide glfw or glfw3::glfw")
  endif()
endfunction()

function(_boilerplate_graphics_glew target)
  if(NOT TARGET GLEW::GLEW)
    find_package(GLEW REQUIRED)
  endif()
  target_link_libraries(${target} PRIVATE GLEW::GLEW)
endfunction()

function(_boilerplate_graphics_glm target)
  if(NOT TARGET glm::glm)
    find_package(glm CONFIG QUIET)
    if(NOT TARGET glm::glm)
      find_package(glm REQUIRED)
    endif()
  endif()
  if(NOT TARGET glm::glm)
    message(FATAL_ERROR "GLM was found but did not provide glm::glm")
  endif()
  target_link_libraries(${target} PRIVATE glm::glm)
endfunction()

function(_boilerplate_graphics_imgui target)
  set(_candidate "${BOILERPLATE_IMGUI_TARGET}")
  if(_candidate AND NOT TARGET ${_candidate})
    message(FATAL_ERROR "BOILERPLATE_IMGUI_TARGET does not exist: ${_candidate}")
  endif()
  if(NOT _candidate)
    foreach(_known IN ITEMS imgui::imgui ImGui::ImGui imgui)
      if(TARGET ${_known})
        set(_candidate ${_known})
        break()
      endif()
    endforeach()
  endif()
  if(NOT _candidate)
    find_package(imgui CONFIG QUIET)
    foreach(_known IN ITEMS imgui::imgui ImGui::ImGui imgui)
      if(TARGET ${_known})
        set(_candidate ${_known})
        break()
      endif()
    endforeach()
  endif()
  if(NOT _candidate)
    message(FATAL_ERROR
      "ImGui policy needs an existing target; set BOILERPLATE_IMGUI_TARGET or provide imgui::imgui/ImGui::ImGui/imgui")
  endif()
  target_link_libraries(${target} PRIVATE ${_candidate})
endfunction()

# Pure dependency capabilities. Compose them with `minimal`, runtime policies,
# Qt policies, or each other without resetting target optimization settings.
boilerplate_define_policy(vulkan HOOKS _boilerplate_graphics_vulkan)
boilerplate_define_policy(glfw HOOKS _boilerplate_graphics_glfw)
boilerplate_define_policy(glew HOOKS _boilerplate_graphics_glew)
boilerplate_define_policy(glm HOOKS _boilerplate_graphics_glm)
boilerplate_define_policy(imgui HOOKS _boilerplate_graphics_imgui)
boilerplate_define_policy(graphics-vulkan INHERITS vulkan glfw glm)
boilerplate_define_policy(graphics-opengl INHERITS glfw glew glm)
boilerplate_define_policy(graphics-vulkan-imgui INHERITS graphics-vulkan imgui)
boilerplate_define_policy(graphics-opengl-imgui INHERITS graphics-opengl imgui)
# Opinionated kitchen-sink profile matching projects that expose Vulkan and an
# OpenGL/ImGui path from the same executable.
boilerplate_define_policy(graphics INHERITS vulkan glfw glew glm imgui)

# Shader compilation needs source arguments, so it is an explicit helper rather
# than a policy hook. It prefers glslc and falls back to glslangValidator.
function(boilerplate_add_glsl_shaders target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "COPY_TO_RUNTIME" "SOURCE_DIR;OUTPUT_DIR;COMPILER" "SOURCES")
  if(ARG_UNPARSED_ARGUMENTS OR NOT TARGET ${target})
    message(FATAL_ERROR "boilerplate_add_glsl_shaders(${target}): target must exist")
  endif()
  if(NOT ARG_SOURCE_DIR)
    set(ARG_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/shaders")
  endif()
  get_filename_component(ARG_SOURCE_DIR "${ARG_SOURCE_DIR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  if(NOT ARG_OUTPUT_DIR)
    set(ARG_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/shaders/${target}")
  endif()
  if(NOT ARG_SOURCES)
    file(GLOB_RECURSE ARG_SOURCES CONFIGURE_DEPENDS
      "${ARG_SOURCE_DIR}/*.vert" "${ARG_SOURCE_DIR}/*.frag" "${ARG_SOURCE_DIR}/*.comp"
      "${ARG_SOURCE_DIR}/*.geom" "${ARG_SOURCE_DIR}/*.tesc" "${ARG_SOURCE_DIR}/*.tese")
  endif()
  if(NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_glsl_shaders(${target}): no shader sources")
  endif()
  if(NOT ARG_COMPILER)
    if(DEFINED Vulkan_GLSLC_EXECUTABLE AND Vulkan_GLSLC_EXECUTABLE)
      set(ARG_COMPILER "${Vulkan_GLSLC_EXECUTABLE}")
    else()
      find_program(ARG_COMPILER NAMES glslc glslangValidator REQUIRED)
    endif()
  endif()
  get_filename_component(_compiler_name "${ARG_COMPILER}" NAME)
  set(_outputs)
  foreach(_source IN LISTS ARG_SOURCES)
    get_filename_component(_source_abs "${_source}" ABSOLUTE BASE_DIR "${ARG_SOURCE_DIR}")
    file(RELATIVE_PATH _relative "${ARG_SOURCE_DIR}" "${_source_abs}")
    set(_output "${ARG_OUTPUT_DIR}/${_relative}.spv")
    get_filename_component(_output_parent "${_output}" DIRECTORY)
    if(_compiler_name MATCHES "glslangValidator")
      set(_compile_command "${ARG_COMPILER}" -V "${_source_abs}" -o "${_output}")
    else()
      set(_compile_command "${ARG_COMPILER}" "${_source_abs}" -o "${_output}")
    endif()
    add_custom_command(OUTPUT "${_output}"
      COMMAND ${CMAKE_COMMAND} -E make_directory "${_output_parent}"
      COMMAND ${_compile_command}
      DEPENDS "${_source_abs}"
      VERBATIM)
    list(APPEND _outputs "${_output}")
  endforeach()
  set(_shader_target "${target}_shaders")
  if(TARGET ${_shader_target})
    message(FATAL_ERROR "Shader target already exists: ${_shader_target}")
  endif()
  add_custom_target(${_shader_target} DEPENDS ${_outputs})
  add_dependencies(${target} ${_shader_target})
  set_property(TARGET ${target} PROPERTY BOILERPLATE_SHADER_OUTPUTS "${_outputs}")
  if(ARG_COPY_TO_RUNTIME)
    add_custom_command(TARGET ${target} POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:${target}>/shaders"
      COMMAND ${CMAKE_COMMAND} -E copy_directory "${ARG_OUTPUT_DIR}" "$<TARGET_FILE_DIR:${target}>/shaders"
      VERBATIM)
  endif()
endfunction()
