cmake_minimum_required(VERSION 3.26)

if(NOT HARNESS_CONFIG OR NOT EXISTS "${HARNESS_CONFIG}")
  message(FATAL_ERROR "Pass -DHARNESS_CONFIG=<generated harness config>")
endif()
include("${HARNESS_CONFIG}")

function(_json_quote out value)
  string(REPLACE "\\" "\\\\" _v "${value}")
  string(REPLACE "\"" "\\\"" _v "${_v}")
  string(REPLACE "\n" "\\n" _v "${_v}")
  string(REPLACE "\r" "\\r" _v "${_v}")
  string(REPLACE "\t" "\\t" _v "${_v}")
  set(${out} "\"${_v}\"" PARENT_SCOPE)
endfunction()

function(_json_try_get out json)
  string(JSON _value ERROR_VARIABLE _error GET "${json}" ${ARGN})
  if(_error)
    set(${out} "" PARENT_SCOPE)
  else()
    set(${out} "${_value}" PARENT_SCOPE)
  endif()
endfunction()

function(_json_array_to_list out json)
  set(_path ${ARGN})
  string(JSON _length ERROR_VARIABLE _error LENGTH "${json}" ${_path})
  if(_error)
    set(${out} "" PARENT_SCOPE)
    return()
  endif()
  set(_list)
  if(_length GREATER 0)
    math(EXPR _last "${_length}-1")
    foreach(_i RANGE 0 ${_last})
      string(JSON _value GET "${json}" ${_path} ${_i})
      list(APPEND _list "${_value}")
    endforeach()
  endif()
  set(${out} "${_list}" PARENT_SCOPE)
endfunction()

function(_json_object_pairs out json)
  set(_path ${ARGN})
  string(JSON _length ERROR_VARIABLE _error LENGTH "${json}" ${_path})
  if(_error)
    set(${out} "" PARENT_SCOPE)
    return()
  endif()
  set(_pairs)
  if(_length GREATER 0)
    math(EXPR _last "${_length}-1")
    foreach(_i RANGE 0 ${_last})
      string(JSON _key MEMBER "${json}" ${_path} ${_i})
      string(JSON _value GET "${json}" ${_path} "${_key}")
      list(APPEND _pairs "${_key}=${_value}")
    endforeach()
  endif()
  set(${out} "${_pairs}" PARENT_SCOPE)
endfunction()

function(_lookup_json_path out json path)
  string(REPLACE "." ";" _parts "${path}")
  string(JSON _value ERROR_VARIABLE _error GET "${json}" ${_parts})
  if(_error)
    message(FATAL_ERROR "Harness metric/invariant '${path}' is missing from result JSON")
  endif()
  set(${out} "${_value}" PARENT_SCOPE)
endfunction()

function(_sanitize_name out value)
  string(REGEX REPLACE "[^A-Za-z0-9_.-]" "_" _safe "${value}")
  set(${out} "${_safe}" PARENT_SCOPE)
endfunction()

function(_median out values)
  set(_values ${values})
  list(SORT _values COMPARE NATURAL)
  list(LENGTH _values _n)
  math(EXPR _mid "${_n}/2")
  list(GET _values ${_mid} _m)
  math(EXPR _odd "${_n}%2")
  if(NOT _odd)
    math(EXPR _lo "${_mid}-1")
    list(GET _values ${_lo} _a)
    math(EXPR _m "(${_a}+${_m})/2")
  endif()
  set(${out} "${_m}" PARENT_SCOPE)
endfunction()

function(_summary_json out values)
  set(_values ${values})
  list(SORT _values COMPARE NATURAL)
  list(LENGTH _values _n)
  if(_n EQUAL 0)
    set(${out} "{}" PARENT_SCOPE)
    return()
  endif()
  list(GET _values 0 _min)
  math(EXPR _last "${_n}-1")
  list(GET _values ${_last} _max)
  _median(_median "${_values}")
  set(_sum 0)
  foreach(_v IN LISTS _values)
    math(EXPR _sum "${_sum}+${_v}")
  endforeach()
  math(EXPR _mean "${_sum}/${_n}")
  math(EXPR _p95i "(${_n}*95+99)/100-1")
  list(GET _values ${_p95i} _p95)
  set(${out} "{\"scale\":1000000,\"count\":${_n},\"min\":${_min},\"median\":${_median},\"mean\":${_mean},\"p95\":${_p95},\"max\":${_max}}" PARENT_SCOPE)
endfunction()

# Deterministic Fisher-Yates using a tiny LCG. This avoids depending on Python
# merely to shuffle case order while preserving reproducibility from SEED.
function(_shuffle_indices out count seed)
  set(_items)
  if(count GREATER 0)
    math(EXPR _last "${count}-1")
    foreach(_i RANGE 0 ${_last})
      list(APPEND _items ${_i})
    endforeach()
  endif()
  math(EXPR _state "(${seed}) & 0x7fffffff")
  if(count GREATER 1)
    math(EXPR _i "${count}-1")
    while(_i GREATER 0)
      math(EXPR _state "(1103515245 * ${_state} + 12345) & 0x7fffffff")
      math(EXPR _j "${_state} % (${_i}+1)")
      list(GET _items ${_i} _a)
      list(GET _items ${_j} _b)
      list(REMOVE_AT _items ${_i})
      list(INSERT _items ${_i} ${_b})
      list(REMOVE_AT _items ${_j})
      list(INSERT _items ${_j} ${_a})
      math(EXPR _i "${_i}-1")
    endwhile()
  endif()
  set(${out} "${_items}" PARENT_SCOPE)
endfunction()

if(NOT EXISTS "${HARNESS_BINARY}")
  message(FATAL_ERROR "Harness binary does not exist: ${HARNESS_BINARY}")
endif()
file(MAKE_DIRECTORY "${HARNESS_OUTPUT}")
file(MAKE_DIRECTORY "${HARNESS_OUTPUT}/logs")
file(SHA256 "${HARNESS_BINARY}" _binary_sha256)

# Load declarative cases. The compact no-CASES form becomes one default case.
set(_case_names)
set(_case_args)
set(_case_envs)
set(_case_cwds)
set(_case_cpu_counts)
set(_case_cpus)
set(_case_metadata)
if(HARNESS_CASES)
  file(READ "${HARNESS_CASES}" _cases_json)
  string(JSON _root_type TYPE "${_cases_json}")
  set(_defaults_args)
  set(_defaults_env)
  set(_defaults_cpus)
  set(_defaults_cpu_count "")
  set(_defaults_metadata)
  if(_root_type STREQUAL "OBJECT")
    _json_array_to_list(_defaults_args "${_cases_json}" defaults args)
    _json_object_pairs(_defaults_env "${_cases_json}" defaults env)
    _json_array_to_list(_defaults_cpus "${_cases_json}" defaults cpus)
    _json_try_get(_defaults_cpu_count "${_cases_json}" defaults cpu_count)
    _json_object_pairs(_defaults_metadata "${_cases_json}" defaults metadata)
    string(JSON _case_count ERROR_VARIABLE _case_error LENGTH "${_cases_json}" cases)
    if(_case_error)
      message(FATAL_ERROR "cases object requires a non-empty 'cases' array")
    endif()
    set(_case_path cases)
  elseif(_root_type STREQUAL "ARRAY")
    string(JSON _case_count LENGTH "${_cases_json}")
    set(_case_path)
  else()
    message(FATAL_ERROR "cases file must contain an array or object")
  endif()
  if(_case_count LESS 1)
    message(FATAL_ERROR "cases file must contain at least one case")
  endif()

  set(_selected_names)
  if(HARNESS_CASE_GROUP)
    if(NOT _root_type STREQUAL "OBJECT")
      message(FATAL_ERROR "CASE_GROUP requires object-form cases JSON")
    endif()
    _json_array_to_list(_selected_names "${_cases_json}" groups "${HARNESS_CASE_GROUP}")
    if(NOT _selected_names)
      message(FATAL_ERROR "unknown/empty case group '${HARNESS_CASE_GROUP}'")
    endif()
  endif()

  math(EXPR _case_last "${_case_count}-1")
  foreach(_i RANGE 0 ${_case_last})
    set(_path ${_case_path} ${_i})
    _json_try_get(_name "${_cases_json}" ${_path} name)
    if(NOT _name)
      set(_name "case-${_i}")
    endif()
    if(HARNESS_CASE_GROUP AND NOT _name IN_LIST _selected_names)
      continue()
    endif()
    if(_name IN_LIST _case_names)
      message(FATAL_ERROR "duplicate harness case '${_name}'")
    endif()
    _json_array_to_list(_args "${_cases_json}" ${_path} args)
    set(_args ${_defaults_args} ${_args})
    _json_object_pairs(_env "${_cases_json}" ${_path} env)
    set(_env ${_defaults_env} ${_env})
    # Case keys override defaults. Remove any default entry with the same key.
    foreach(_entry IN LISTS _env)
      string(REGEX REPLACE "=.*$" "" _key "${_entry}")
      set(_merged)
      foreach(_old IN LISTS _env)
        string(REGEX REPLACE "=.*$" "" _old_key "${_old}")
        if(NOT _old_key STREQUAL _key OR _old STREQUAL _entry)
          list(APPEND _merged "${_old}")
        endif()
      endforeach()
      set(_env "${_merged}")
    endforeach()
    _json_try_get(_cwd "${_cases_json}" ${_path} cwd)
    _json_try_get(_cpu_count "${_cases_json}" ${_path} cpu_count)
    if(NOT _cpu_count)
      set(_cpu_count "${_defaults_cpu_count}")
    endif()
    _json_array_to_list(_cpus "${_cases_json}" ${_path} cpus)
    if(NOT _cpus)
      set(_cpus "${_defaults_cpus}")
    endif()
    _json_object_pairs(_meta "${_cases_json}" ${_path} metadata)
    set(_meta ${_defaults_metadata} ${_meta})
    list(APPEND _case_names "${_name}")
    string(REPLACE ";" "\\;" _packed_args "${_args}")
    string(REPLACE ";" "\\;" _packed_env "${_env}")
    string(REPLACE ";" "\\;" _packed_cpus "${_cpus}")
    string(REPLACE ";" "\\;" _packed_meta "${_meta}")
    if(_packed_args STREQUAL "")
      set(_packed_args "__BP_EMPTY__")
    endif()
    if(_packed_env STREQUAL "")
      set(_packed_env "__BP_EMPTY__")
    endif()
    if(_cwd STREQUAL "")
      set(_cwd "__BP_EMPTY__")
    endif()
    if(_cpu_count STREQUAL "")
      set(_cpu_count "__BP_EMPTY__")
    endif()
    if(_packed_cpus STREQUAL "")
      set(_packed_cpus "__BP_EMPTY__")
    endif()
    if(_packed_meta STREQUAL "")
      set(_packed_meta "__BP_EMPTY__")
    endif()
    list(APPEND _case_args "${_packed_args}")
    list(APPEND _case_envs "${_packed_env}")
    list(APPEND _case_cwds "${_cwd}")
    list(APPEND _case_cpu_counts "${_cpu_count}")
    list(APPEND _case_cpus "${_packed_cpus}")
    list(APPEND _case_metadata "${_packed_meta}")
  endforeach()
  if(NOT _case_names)
    message(FATAL_ERROR "no harness cases selected")
  endif()
else()
  set(_case_names default)
  string(REPLACE ";" "\\;" _packed_args "${HARNESS_ARGS}")
  if(_packed_args STREQUAL "")
    set(_packed_args "__BP_EMPTY__")
  endif()
  list(APPEND _case_args "${_packed_args}")
  list(APPEND _case_envs "__BP_EMPTY__")
  list(APPEND _case_cwds "__BP_EMPTY__")
  if(HARNESS_CPU_COUNT STREQUAL "")
    list(APPEND _case_cpu_counts "__BP_EMPTY__")
  else()
    list(APPEND _case_cpu_counts "${HARNESS_CPU_COUNT}")
  endif()
  string(REPLACE ";" "\\;" _packed_cpus "${HARNESS_CPUS}")
  if(_packed_cpus STREQUAL "")
    set(_packed_cpus "__BP_EMPTY__")
  endif()
  list(APPEND _case_cpus "${_packed_cpus}")
  list(APPEND _case_metadata "__BP_EMPTY__")
endif()

list(LENGTH _case_names _case_count)

# Linux affinity is an optional OS capability, not a harness language/runtime
# dependency. Explicit CPUS and physical placement use taskset if available.
set(_physical_cpus)
if(HARNESS_AFFINITY STREQUAL "physical")
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    file(GLOB _cpu_dirs "/sys/devices/system/cpu/cpu[0-9]*")
    set(_seen_cores)
    foreach(_dir IN LISTS _cpu_dirs)
      get_filename_component(_base "${_dir}" NAME)
      string(REGEX REPLACE "^cpu" "" _cpu "${_base}")
      if(EXISTS "${_dir}/topology/core_id")
        file(READ "${_dir}/topology/core_id" _core)
        string(STRIP "${_core}" _core)
      else()
        set(_core "${_cpu}")
      endif()
      if(EXISTS "${_dir}/topology/physical_package_id")
        file(READ "${_dir}/topology/physical_package_id" _pkg)
        string(STRIP "${_pkg}" _pkg)
      else()
        set(_pkg 0)
      endif()
      set(_key "${_pkg}:${_core}")
      if(NOT _key IN_LIST _seen_cores)
        list(APPEND _seen_cores "${_key}")
        list(APPEND _physical_cpus "${_cpu}")
      endif()
    endforeach()
    list(SORT _physical_cpus COMPARE NATURAL)
  endif()
endif()
find_program(_taskset taskset)
if((HARNESS_CPUS OR HARNESS_AFFINITY STREQUAL "physical") AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND NOT _taskset)
  message(FATAL_ERROR "Harness affinity requested but taskset is unavailable")
endif()

if(HARNESS_PERF_EVENTS)
  if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "PERF/PERF_EVENTS are supported only on Linux")
  endif()
  find_program(_perf perf REQUIRED)
endif()

# Stable manifest/provenance.
_json_quote(_q_name "${HARNESS_NAME}")
_json_quote(_q_binary "${HARNESS_BINARY}")
_json_quote(_q_hash "${_binary_sha256}")
_json_quote(_q_compiler "${HARNESS_COMPILER}")
_json_quote(_q_generator "${HARNESS_GENERATOR}")
_json_quote(_q_project "${HARNESS_PROJECT}")
set(_manifest "{\"name\":${_q_name},\"binary\":${_q_binary},\"binary_sha256\":${_q_hash},\"compiler\":${_q_compiler},\"generator\":${_q_generator},\"project\":${_q_project},\"rounds\":${HARNESS_ROUNDS},\"warmup_runs\":${HARNESS_WARMUP},\"timeout_seconds\":${HARNESS_TIMEOUT}}")
file(WRITE "${HARNESS_OUTPUT}/manifest.json" "${_manifest}\n")
file(WRITE "${HARNESS_OUTPUT}/runs.jsonl" "")

# Per-case accumulators use dynamic variables keyed by a sanitized case name.
set(_failed FALSE)
set(_failure_message "")
set(_invariant_keys)
foreach(_case IN LISTS _case_names)
  _sanitize_name(_safe "${_case}")
  foreach(_metric IN LISTS HARNESS_METRICS)
    _sanitize_name(_msafe "${_metric}")
    set(_metric_${_safe}_${_msafe})
  endforeach()
endforeach()

math(EXPR _total_rounds "${HARNESS_WARMUP}+${HARNESS_ROUNDS}")
math(EXPR _round_last "${_total_rounds}-1")
foreach(_round RANGE 0 ${_round_last})
  set(_warmup FALSE)
  if(_round LESS HARNESS_WARMUP)
    set(_warmup TRUE)
  endif()
  if(HARNESS_RANDOMIZE)
    math(EXPR _round_seed "(${HARNESS_SEED}) + ${_round}")
    _shuffle_indices(_order ${_case_count} ${_round_seed})
  else()
    set(_order)
    math(EXPR _case_last "${_case_count}-1")
    foreach(_i RANGE 0 ${_case_last})
      list(APPEND _order ${_i})
    endforeach()
  endif()

  foreach(_index IN LISTS _order)
    list(GET _case_names ${_index} _case)
    list(GET _case_args ${_index} _args)
    list(GET _case_envs ${_index} _case_env)
    list(GET _case_cwds ${_index} _case_cwd)
    list(GET _case_cpu_counts ${_index} _cpu_count)
    list(GET _case_cpus ${_index} _cpus)
    foreach(_slot IN ITEMS _args _case_env _case_cwd _cpu_count _cpus)
      if("${${_slot}}" STREQUAL "__BP_EMPTY__")
        set(${_slot} "")
      endif()
    endforeach()
    string(REPLACE "\\;" ";" _args "${_args}")
    string(REPLACE "\\;" ";" _case_env "${_case_env}")
    string(REPLACE "\\;" ";" _cpus "${_cpus}")
    set(_env ${HARNESS_ENV} ${_case_env})
    set(_cwd "${HARNESS_WORKING_DIRECTORY}")
    if(_case_cwd)
      if(IS_ABSOLUTE "${_case_cwd}")
        set(_cwd "${_case_cwd}")
      elseif(HARNESS_CASES)
        get_filename_component(_cases_dir "${HARNESS_CASES}" DIRECTORY)
        get_filename_component(_cwd "${_cases_dir}/${_case_cwd}" ABSOLUTE)
      else()
        get_filename_component(_cwd "${HARNESS_WORKING_DIRECTORY}/${_case_cwd}" ABSOLUTE)
      endif()
    endif()
    if(NOT IS_DIRECTORY "${_cwd}")
      message(FATAL_ERROR "Harness working directory does not exist: ${_cwd}")
    endif()

    set(_prefix)
    if(_cpus)
      string(JOIN "," _cpu_spec ${_cpus})
      set(_prefix "${_taskset}" -c "${_cpu_spec}")
    elseif(HARNESS_AFFINITY STREQUAL "physical" AND _physical_cpus)
      if(NOT _cpu_count OR _cpu_count EQUAL 0)
        set(_cpu_count "${HARNESS_CPU_COUNT}")
      endif()
      if(_cpu_count AND _cpu_count GREATER 0)
        list(SUBLIST _physical_cpus 0 ${_cpu_count} _chosen_cpus)
      else()
        set(_chosen_cpus ${_physical_cpus})
      endif()
      string(JOIN "," _cpu_spec ${_chosen_cpus})
      set(_prefix "${_taskset}" -c "${_cpu_spec}")
    endif()

    _sanitize_name(_safe_case "${_case}")
    set(_tag "${_safe_case}-r${_round}")
    set(_stdout_file "${HARNESS_OUTPUT}/logs/${_tag}.stdout.log")
    set(_stderr_file "${HARNESS_OUTPUT}/logs/${_tag}.stderr.log")
    set(_perf_file "${HARNESS_OUTPUT}/logs/${_tag}.perf.csv")
    set(_command ${_prefix})
    if(HARNESS_PERF_EVENTS)
      string(JOIN "," _events ${HARNESS_PERF_EVENTS})
      list(APPEND _command "${_perf}" stat -x ";" -o "${_perf_file}" -e "${_events}" --)
    endif()
    list(APPEND _command "${HARNESS_BINARY}" ${_args})

    string(TIMESTAMP _start "%s%f" UTC)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${_env} -- ${_command}
      WORKING_DIRECTORY "${_cwd}" TIMEOUT "${HARNESS_TIMEOUT}"
      RESULT_VARIABLE _result OUTPUT_FILE "${_stdout_file}" ERROR_FILE "${_stderr_file}")
    string(TIMESTAMP _end "%s%f" UTC)
    math(EXPR _elapsed "${_end}-${_start}")
    file(READ "${_stdout_file}" _stdout)

    set(_parsed "")
    if(HARNESS_PARSER STREQUAL "json")
      string(JSON _json_type ERROR_VARIABLE _parse_error TYPE "${_stdout}")
      if(_parse_error OR NOT _json_type STREQUAL "OBJECT")
        set(_result "parser-error")
      else()
        set(_parsed "${_stdout}")
      endif()
    elseif(HARNESS_PARSER STREQUAL "json-line")
      string(REPLACE "\r\n" "\n" _normalized "${_stdout}")
      string(REPLACE "\r" "\n" _normalized "${_normalized}")
      string(REPLACE "\n" ";" _lines "${_normalized}")
      set(_objects)
      foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if(_line MATCHES "^\\{")
          string(JSON _json_type ERROR_VARIABLE _parse_error TYPE "${_line}")
          if(NOT _parse_error AND _json_type STREQUAL "OBJECT")
            list(APPEND _objects "${_line}")
          endif()
        endif()
      endforeach()
      list(LENGTH _objects _object_count)
      if(NOT _object_count EQUAL 1)
        set(_result "parser-error")
      else()
        list(GET _objects 0 _parsed)
      endif()
    endif()

    if(_parsed)
      _json_try_get(_status "${_parsed}" status)
      if(_status AND NOT _status STREQUAL "ok")
        set(_result "status=${_status}")
      endif()
    endif()

    _json_quote(_q_case "${_case}")
    _json_quote(_q_result "${_result}")
    if(_warmup)
      set(_warmup_json true)
    else()
      set(_warmup_json false)
    endif()
    set(_record "{\"case\":${_q_case},\"round\":${_round},\"warmup\":${_warmup_json},\"elapsed_us\":${_elapsed},\"result\":${_q_result}")
    if(_parsed)
      string(APPEND _record ",\"output\":${_parsed}")
    endif()
    if(EXISTS "${_perf_file}")
      _json_quote(_q_perf "${_perf_file}")
      string(APPEND _record ",\"perf_file\":${_q_perf}")
    endif()
    string(APPEND _record "}")
    file(APPEND "${HARNESS_OUTPUT}/runs.jsonl" "${_record}\n")

    if(NOT "${_result}" STREQUAL "0")
      set(_failed TRUE)
      set(_failure_message "case ${_case}, round ${_round} failed (${_result}); see ${_stdout_file} / ${_stderr_file}")
      break()
    endif()

    if(NOT _warmup AND _parsed)
      _sanitize_name(_safe "${_case}")
      foreach(_metric IN LISTS HARNESS_METRICS)
        _lookup_json_path(_value "${_parsed}" "${_metric}")
        if(NOT _value MATCHES "^-?[0-9]+([.][0-9]+)?$")
          message(FATAL_ERROR "metric ${_metric} in case ${_case} is not numeric: ${_value}")
        endif()
        # CMake math is integer-only. Preserve floating point metrics by scaling
        # decimal values to micro-units before aggregation.
        if(_value MATCHES "\\.")
          string(REGEX REPLACE "^(-?[0-9]+)\\.([0-9]*).*$" "\\1;\\2" _parts "${_value}")
          list(GET _parts 0 _whole)
          list(GET _parts 1 _frac)
          string(SUBSTRING "${_frac}000000" 0 6 _frac6)
          if(_whole MATCHES "^-")
            math(EXPR _scaled "${_whole}*1000000 - ${_frac6}")
          else()
            math(EXPR _scaled "${_whole}*1000000 + ${_frac6}")
          endif()
        else()
          math(EXPR _scaled "${_value}*1000000")
        endif()
        _sanitize_name(_msafe "${_metric}")
        list(APPEND _metric_${_safe}_${_msafe} ${_scaled})
      endforeach()
      foreach(_invariant IN LISTS HARNESS_INVARIANTS)
        _lookup_json_path(_value "${_parsed}" "${_invariant}")
        _sanitize_name(_isafe "${_invariant}")
        set(_key "${_safe}_${_isafe}")
        if(DEFINED _invariant_${_key})
          if(NOT "${_invariant_${_key}}" STREQUAL "${_value}")
            message(FATAL_ERROR "invariant ${_invariant} changed in case ${_case}: ${_invariant_${_key}} -> ${_value}")
          endif()
        else()
          set(_invariant_${_key} "${_value}")
        endif()
      endforeach()
    endif()
  endforeach()
  if(_failed)
    break()
  endif()
endforeach()

set(_summary "{\"status\":\"passed\",\"cases\":{")
set(_first_case TRUE)
foreach(_case IN LISTS _case_names)
  if(NOT _first_case)
    string(APPEND _summary ",")
  endif()
  set(_first_case FALSE)
  _json_quote(_q_case "${_case}")
  string(APPEND _summary "${_q_case}:{\"metrics\":{")
  set(_first_metric TRUE)
  _sanitize_name(_safe "${_case}")
  foreach(_metric IN LISTS HARNESS_METRICS)
    if(NOT _first_metric)
      string(APPEND _summary ",")
    endif()
    set(_first_metric FALSE)
    _sanitize_name(_msafe "${_metric}")
    _summary_json(_stats "${_metric_${_safe}_${_msafe}}")
    _json_quote(_q_metric "${_metric}")
    string(APPEND _summary "${_q_metric}:${_stats}")
  endforeach()
  string(APPEND _summary "},\"invariants\":{")
  set(_first_inv TRUE)
  foreach(_invariant IN LISTS HARNESS_INVARIANTS)
    if(NOT _first_inv)
      string(APPEND _summary ",")
    endif()
    set(_first_inv FALSE)
    _sanitize_name(_isafe "${_invariant}")
    set(_key "${_safe}_${_isafe}")
    _json_quote(_q_inv "${_invariant}")
    _json_quote(_q_value "${_invariant_${_key}}")
    string(APPEND _summary "${_q_inv}:${_q_value}")
  endforeach()
  string(APPEND _summary "}}")
endforeach()
string(APPEND _summary "}}")
if(_failed)
  string(REPLACE "\"status\":\"passed\"" "\"status\":\"failed\"" _summary "${_summary}")
endif()
file(WRITE "${HARNESS_OUTPUT}/summary.json" "${_summary}\n")
message(STATUS "Harness result: ${HARNESS_OUTPUT}/summary.json")
if(_failed)
  message(FATAL_ERROR "${_failure_message}")
endif()
