include_guard(GLOBAL)
set(BOILERPLATE_CXX_STANDARD 23 CACHE STRING "C++ standard for owned targets")
set_property(CACHE BOILERPLATE_CXX_STANDARD PROPERTY STRINGS 17 20 23)
if(NOT BOILERPLATE_CXX_STANDARD MATCHES "^(17|20|23)$")
  message(FATAL_ERROR "BOILERPLATE_CXX_STANDARD must be 17, 20 or 23")
endif()
option(BOILERPLATE_WARNINGS "Enable useful compiler warnings" ON)
option(BOILERPLATE_WARNINGS_AS_ERRORS "Treat owned target warnings as errors" OFF)
option(BOILERPLATE_HARDENING "Stack protector and Linux RELRO (no global PIE flags)" OFF)
option(BOILERPLATE_COVERAGE "GCC/Clang gcov-compatible coverage instrumentation" OFF)
option(BOILERPLATE_REPRODUCIBLE "Map source paths for reproducible/debug-stable artifacts" OFF)
option(BOILERPLATE_UNITY_BUILD "Enable CMake unity builds on owned targets" OFF)
option(BOILERPLATE_CCACHE "Use ccache on owned targets" OFF)
option(BOILERPLATE_CLANG_TIDY "Run clang-tidy on owned targets" OFF)
option(BOILERPLATE_FRAME_POINTERS "Keep frame pointers for profiling/unwinding" OFF)
option(BOILERPLATE_BUILD_EXAMPLES "Build example programs" OFF)
option(BOILERPLATE_BUILD_GOOGLE_TESTS "Build optional GoogleTest examples" OFF)
option(BOILERPLATE_BUILD_GOOGLE_BENCHMARKS "Build optional Google Benchmark examples" OFF)
option(BOILERPLATE_BUILD_PROPERTY_TESTS "Build optional RapidCheck property-test example" OFF)
option(BOILERPLATE_BUILD_FUZZERS "Build byte-fuzz harness examples" OFF)
option(BOILERPLATE_BUILD_FUZZTESTS "Build optional Google FuzzTest example" OFF)
set(BOILERPLATE_BENCHMARK_GROUPS "all" CACHE STRING "Enabled benchmark groups (CMake list)")

function(boilerplate_apply_project_options target)
  get_target_property(_done ${target} BOILERPLATE_PROJECT_OPTIONS_APPLIED)
  if(_done)
    return()
  endif()
  set_property(TARGET ${target} PROPERTY BOILERPLATE_PROJECT_OPTIONS_APPLIED TRUE)

  foreach(_key IN ITEMS CXX_STANDARD WARNINGS WARNINGS_AS_ERRORS HARDENING COVERAGE REPRODUCIBLE UNITY_BUILD CCACHE CLANG_TIDY FRAME_POINTERS LTO_MODE PGO_MODE)
    boilerplate_get_target_setting(${target} ${_key} _${_key})
  endforeach()
  if(NOT _CXX_STANDARD MATCHES "^(17|20|23)$")
    message(FATAL_ERROR "Target ${target}: CXX_STANDARD must be 17, 20 or 23")
  endif()

  target_compile_features(${target} PUBLIC cxx_std_${_CXX_STANDARD})
  set_target_properties(${target} PROPERTIES CXX_STANDARD "${_CXX_STANDARD}"
    CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF
    UNITY_BUILD "${_UNITY_BUILD}" BUILD_RPATH_USE_ORIGIN ON)
  if(_WARNINGS)
    if(MSVC)
      target_compile_options(${target} PRIVATE /W4 /permissive-)
    else()
      target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
  endif()
  set_property(TARGET ${target} PROPERTY COMPILE_WARNING_AS_ERROR "${_WARNINGS_AS_ERRORS}")

  get_target_property(_type ${target} TYPE)
  if(_type STREQUAL "STATIC_LIBRARY")
    set(_link INTERFACE)
  else()
    set(_link PRIVATE)
  endif()
  if(_HARDENING)
    if(MSVC)
      target_compile_options(${target} PRIVATE /sdl /GS)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(${target} PRIVATE -fstack-protector-strong)
      if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(${target} ${_link} LINKER:-z,relro LINKER:-z,now)
      endif()
    endif()
  endif()
  if(_COVERAGE)
    if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" OR
        NOT _PGO_MODE STREQUAL "none" OR NOT _LTO_MODE STREQUAL "none")
      message(FATAL_ERROR "Target ${target}: coverage requires GCC/Clang without LTO or PGO")
    endif()
    target_compile_options(${target} PRIVATE --coverage -O0 -g)
    target_link_options(${target} ${_link} --coverage)
  endif()
  if(_REPRODUCIBLE)
    if(MSVC)
      target_compile_options(${target} PRIVATE "/pathmap:${CMAKE_SOURCE_DIR}=.")
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(${target} PRIVATE
        "-ffile-prefix-map=${CMAKE_SOURCE_DIR}=."
        "-fdebug-prefix-map=${CMAKE_SOURCE_DIR}=.")
    endif()
  endif()
  if(_CCACHE)
    find_program(BOILERPLATE_CCACHE_PROGRAM ccache REQUIRED)
    set_property(TARGET ${target} PROPERTY CXX_COMPILER_LAUNCHER "${BOILERPLATE_CCACHE_PROGRAM}")
  endif()
  if(_CLANG_TIDY)
    find_program(BOILERPLATE_CLANG_TIDY_PROGRAM clang-tidy REQUIRED)
    set_property(TARGET ${target} PROPERTY CXX_CLANG_TIDY "${BOILERPLATE_CLANG_TIDY_PROGRAM}")
  endif()
  if(_FRAME_POINTERS)
    if(MSVC)
      target_compile_options(${target} PRIVATE /Oy-)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(${target} PRIVATE -fno-omit-frame-pointer)
      if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64"))
        target_compile_options(${target} PRIVATE -mno-omit-leaf-frame-pointer)
      endif()
    endif()
  endif()
endfunction()

function(boilerplate_add_executable target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "INSTALL" "" "SOURCES;LIBRARIES;POLICIES;POLICY_OPTIONS")
  if(NOT ARG_SOURCES OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "boilerplate_add_executable: invalid arguments for ${target}")
  endif()
  add_executable(${target} ${ARG_SOURCES})
  target_link_libraries(${target} PRIVATE ${ARG_LIBRARIES})
  set(_policy_args)
  if(ARG_POLICIES)
    list(APPEND _policy_args POLICIES ${ARG_POLICIES})
  endif()
  if(ARG_POLICY_OPTIONS)
    list(APPEND _policy_args ${ARG_POLICY_OPTIONS})
  endif()
  boilerplate_apply_optimization(${target} ${_policy_args})
  boilerplate_set_output_name(${target} "${target}")
  if(ARG_INSTALL AND BOILERPLATE_INSTALL)
    if(APPLE)
      set_property(TARGET ${target} PROPERTY INSTALL_RPATH "@loader_path/../${CMAKE_INSTALL_LIBDIR}")
    elseif(UNIX)
      set_property(TARGET ${target} PROPERTY INSTALL_RPATH "$ORIGIN/../${CMAKE_INSTALL_LIBDIR}")
    endif()
    install(TARGETS ${target} RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime)
  endif()
endfunction()

# PCH needs actual header arguments, so it is an explicit helper instead of a
# named boolean policy with arbitrary built-in headers.
function(boilerplate_enable_pch target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "HEADERS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT TARGET ${target} OR NOT ARG_HEADERS)
    message(FATAL_ERROR "boilerplate_enable_pch(target HEADERS ...): invalid arguments")
  endif()
  target_precompile_headers(${target} PRIVATE ${ARG_HEADERS})
endfunction()
