cmake_minimum_required(VERSION 3.26)
if(NOT EXISTS "${RUN_CONFIG}")
  message(FATAL_ERROR "Pass an existing RUN_CONFIG")
endif()
include("${RUN_CONFIG}")
if(NOT EXISTS "${EXECUTABLE}" OR NOT IS_DIRECTORY "${WORKING_DIRECTORY}")
  message(FATAL_ERROR "Workload executable or working directory does not exist")
endif()
string(TIMESTAMP _stamp "%Y%m%dT%H%M%S" UTC)
string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef _nonce)
set(_output "${RESULT_ROOT}/${_stamp}-${_nonce}")
file(MAKE_DIRECTORY "${_output}")
function(json_string out value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()
set(_report "{}")
foreach(_field IN ITEMS SCENARIO EXECUTABLE PROFILE CONFIG COMPILER SOURCE_DIR WORKING_DIRECTORY)
  json_string(_value "${${_field}}")
  string(TOLOWER "${_field}" _key)
  string(JSON _report SET "${_report}" "${_key}" "${_value}")
endforeach()
foreach(_field IN ITEMS ARGS COMMAND_PREFIX)
  set(_array "[]")
  set(_i 0)
  foreach(_arg IN LISTS ${_field})
    json_string(_value "${_arg}")
    string(JSON _array SET "${_array}" ${_i} "${_value}")
    math(EXPR _i "${_i}+1")
  endforeach()
  string(TOLOWER "${_field}" _key)
  string(JSON _report SET "${_report}" "${_key}" "${_array}")
endforeach()
# Environment values may contain secrets: record only explicitly set variable names.
set(_env_names "[]")
set(_i 0)
foreach(_entry IN LISTS ENVIRONMENT)
  string(REGEX REPLACE "=.*$" "" _key "${_entry}")
  json_string(_value "${_key}")
  string(JSON _env_names SET "${_env_names}" ${_i} "${_value}")
  math(EXPR _i "${_i}+1")
endforeach()
string(JSON _report SET "${_report}" environment_names "${_env_names}")
file(SHA256 "${EXECUTABLE}" _hash)
string(JSON _report SET "${_report}" executable_sha256 "\"${_hash}\"")
find_program(_git git)
if(_git)
  execute_process(COMMAND "${_git}" -C "${SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE _revision OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  json_string(_value "${_revision}")
  string(JSON _report SET "${_report}" source_revision "${_value}")
endif()
set(_knobs "{}")
foreach(_entry IN LISTS BUILD_KNOBS)
  string(FIND "${_entry}" "=" _split)
  string(SUBSTRING "${_entry}" 0 ${_split} _key)
  math(EXPR _start "${_split}+1")
  string(SUBSTRING "${_entry}" ${_start} -1 _setting)
  json_string(_value "${_setting}")
  string(JSON _knobs SET "${_knobs}" "${_key}" "${_value}")
endforeach()
string(JSON _report SET "${_report}" build_knobs "${_knobs}")
set(_samples)
set(_records "[]")
set(_failed FALSE)
math(EXPR _total "${REPEATS}+${WARMUP}")
math(EXPR _last "${_total}-1")
foreach(_i RANGE 0 ${_last})
  string(TIMESTAMP _start "%s%f" UTC)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${ENVIRONMENT} -- ${COMMAND_PREFIX} "${EXECUTABLE}" ${ARGS}
    WORKING_DIRECTORY "${WORKING_DIRECTORY}" TIMEOUT "${TIMEOUT}" RESULT_VARIABLE _result
    OUTPUT_FILE "${_output}/${_i}.stdout.log" ERROR_FILE "${_output}/${_i}.stderr.log")
  string(TIMESTAMP _end "%s%f" UTC)
  math(EXPR _elapsed "${_end}-${_start}")
  if(_elapsed LESS 0)
    set(_result "wall clock moved backwards")
  endif()
  set(_record "{}")
  json_string(_value "${_result}")
  string(JSON _record SET "${_record}" result "${_value}")
  string(JSON _record SET "${_record}" elapsed_us ${_elapsed})
  if(_i LESS WARMUP)
    string(JSON _record SET "${_record}" warmup true)
  else()
    string(JSON _record SET "${_record}" warmup false)
    if("${_result}" STREQUAL "0")
      list(APPEND _samples ${_elapsed})
    endif()
  endif()
  string(JSON _records SET "${_records}" ${_i} "${_record}")
  if(NOT "${_result}" STREQUAL "0")
    set(_failed TRUE)
    break()
  endif()
endforeach()
string(JSON _report SET "${_report}" runs "${_records}")
if(NOT _failed)
  list(SORT _samples COMPARE NATURAL)
  list(GET _samples 0 _min)
  math(EXPR _middle "${REPEATS}/2")
  list(GET _samples ${_middle} _median)
  math(EXPR _parity "${REPEATS}%2")
  if(_parity EQUAL 0)
    math(EXPR _lower "${_middle}-1")
    list(GET _samples ${_lower} _lower_value)
    math(EXPR _median "(${_median}+${_lower_value})/2")
  endif()
  math(EXPR _p95_index "(${REPEATS}*95+99)/100-1")
  list(GET _samples ${_p95_index} _p95)
  set(_sum 0)
  foreach(_sample IN LISTS _samples)
    math(EXPR _sum "${_sum}+${_sample}")
  endforeach()
  math(EXPR _mean "${_sum}/${REPEATS}")
  string(JSON _report SET "${_report}" summary "{\"min_us\":${_min},\"median_us\":${_median},\"mean_us\":${_mean},\"p95_us\":${_p95}}")
  string(JSON _report SET "${_report}" status "\"passed\"")
else()
  string(JSON _report SET "${_report}" status "\"failed\"")
endif()
file(WRITE "${_output}/result.json" "${_report}\n")
message(STATUS "Process harness result: ${_output}/result.json")
if(_failed)
  message(FATAL_ERROR "Workload failed (${_result}); see captured logs")
endif()
