include_guard(GLOBAL)

# Select the target distribution family, not whatever packaging utilities happen
# to be installed. An explicit file is useful for isolated regression tests.
function(boilerplate_linux_family result)
  set(${result} generic PARENT_SCOPE)
  if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    return()
  endif()
  if(DEFINED BOILERPLATE_OS_RELEASE_FILE)
    set(_release "${BOILERPLATE_OS_RELEASE_FILE}")
  else()
    set(_release /etc/os-release)
  endif()
  if(NOT EXISTS "${_release}")
    return()
  endif()
  file(STRINGS "${_release}" _entries REGEX "^ID(_LIKE)?=")
  set(_id "")
  set(_like "")
  foreach(_entry IN LISTS _entries)
    if(_entry MATCHES "^ID=(.*)$")
      set(_id "${CMAKE_MATCH_1}")
    elseif(_entry MATCHES "^ID_LIKE=(.*)$")
      set(_like "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  string(REGEX REPLACE "^[\"']|[\"']$" "" _id "${_id}")
  string(REGEX REPLACE "^[\"']|[\"']$" "" _like "${_like}")
  string(TOLOWER "${_id} ${_like}" _tokens)
  # Anchored token matching avoids accidentally classifying e.g. 'archlinuxfoo'.
  if(" ${_tokens} " MATCHES "[ \t](arch|archlinux|cachyos|manjaro|endeavouros|artix)[ \t]")
    set(_family arch)
  elseif(" ${_tokens} " MATCHES "[ \t](debian|ubuntu|linuxmint|pop|raspbian)[ \t]")
    set(_family debian)
  elseif(" ${_tokens} " MATCHES "[ \t](fedora|rhel|centos|rocky|almalinux|ol|suse|opensuse|opensuse-tumbleweed)[ \t]")
    set(_family rpm)
  else()
    set(_family generic)
  endif()
  set(${result} "${_family}" PARENT_SCOPE)
endfunction()
