include_guard(GLOBAL)
include(GNUInstallDirs)
include("${CMAKE_CURRENT_LIST_DIR}/LinuxFamily.cmake")
set(BOILERPLATE_PACKAGE_VENDOR "${PROJECT_NAME}" CACHE STRING "Package vendor")
set(BOILERPLATE_PACKAGE_CONTACT "" CACHE STRING "Package maintainer/contact")
set(BOILERPLATE_PACKAGE_SUMMARY "${PROJECT_DESCRIPTION}" CACHE STRING "Package summary")
set(BOILERPLATE_PACKAGE_GENERATORS "" CACHE STRING "Explicit CPack generators; empty selects platform defaults")
set(BOILERPLATE_DEB_DEPENDS "" CACHE STRING "Optional Debian package dependency expression")
set(BOILERPLATE_RPM_REQUIRES "" CACHE STRING "Optional RPM package dependency expression")

function(_boilerplate_project_packaging_finalize)
  include(InstallRequiredSystemLibraries)
  set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
  set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
  set(CPACK_PACKAGE_VENDOR "${BOILERPLATE_PACKAGE_VENDOR}")
  set(CPACK_PACKAGE_CONTACT "${BOILERPLATE_PACKAGE_CONTACT}")
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${BOILERPLATE_PACKAGE_SUMMARY}")
  if(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE")
    set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
  endif()
  set(CPACK_STRIP_FILES TRUE)
  set(CPACK_COMPONENTS_ALL Runtime Development Documentation)
  set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Runtime")
  set(CPACK_COMPONENT_DEVELOPMENT_DISPLAY_NAME "Development")
  set(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Documentation")
  set(CPACK_COMPONENT_DEVELOPMENT_DEPENDS Runtime)
  # Isolate distributables from the configured binaries and install tree.
  get_filename_component(_preset_dir "${CMAKE_BINARY_DIR}" NAME)
  set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/out/packages/${_preset_dir}")

  if(BOILERPLATE_PACKAGE_GENERATORS)
    set(CPACK_GENERATOR "${BOILERPLATE_PACKAGE_GENERATORS}")
  elseif(WIN32)
    set(CPACK_GENERATOR ZIP)
    find_program(_boilerplate_makensis makensis)
    if(_boilerplate_makensis)
      list(APPEND CPACK_GENERATOR NSIS)
    else()
      message(STATUS "CPack: makensis not found; ZIP archive available (NSIS requires the package toolchain)")
    endif()
    set(CPACK_NSIS_MODIFY_PATH ON)
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  elseif(APPLE)
    set(CPACK_GENERATOR TGZ)
    find_program(_boilerplate_hdiutil hdiutil)
    if(_boilerplate_hdiutil)
      list(APPEND CPACK_GENERATOR DragNDrop)
    endif()
  elseif(UNIX)
    set(CPACK_GENERATOR TGZ)
    if(CMAKE_CROSSCOMPILING)
      message(STATUS "CPack: cross-compilation defaults to TGZ; choose a target format explicitly")
    else()
      boilerplate_linux_family(_family)
      if(_family STREQUAL "debian")
        find_program(_boilerplate_dpkg_deb dpkg-deb)
        if(_boilerplate_dpkg_deb)
          list(APPEND CPACK_GENERATOR DEB)
        else()
          message(WARNING "Debian family detected, but dpkg-deb is missing: TGZ only")
        endif()
      elseif(_family STREQUAL "rpm")
        find_program(_boilerplate_rpmbuild rpmbuild)
        if(_boilerplate_rpmbuild)
          list(APPEND CPACK_GENERATOR RPM)
        else()
          message(WARNING "RPM family detected, but rpmbuild is missing: TGZ only")
        endif()
      elseif(_family STREQUAL "arch")
        message(STATUS "Arch family detected: TGZ through CPack, native package through makepkg")
      else()
        message(STATUS "Unknown Linux family: portable TGZ only")
      endif()
    endif()
  else()
    set(CPACK_GENERATOR TGZ)
  endif()

  if(UNIX AND NOT APPLE)
    if(BOILERPLATE_PACKAGE_CONTACT)
      set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${BOILERPLATE_PACKAGE_CONTACT}")
    else()
      set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${BOILERPLATE_PACKAGE_VENDOR}")
    endif()
    set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
    if(BOILERPLATE_DEB_DEPENDS)
      set(CPACK_DEBIAN_PACKAGE_DEPENDS "${BOILERPLATE_DEB_DEPENDS}")
    endif()
    if(BOILERPLATE_RPM_REQUIRES)
      set(CPACK_RPM_PACKAGE_REQUIRES "${BOILERPLATE_RPM_REQUIRES}")
    endif()
  endif()

  get_property(_revision GLOBAL PROPERTY BOILERPLATE_GIT_SHORT_SHA)
  if(NOT _revision)
    set(_revision unknown)
  endif()
  if(CMAKE_CONFIGURATION_TYPES)
    set(_build multi)
  elseif(CMAKE_BUILD_TYPE)
    set(_build "${CMAKE_BUILD_TYPE}")
  else()
    set(_build default)
  endif()
  set(_platform "${CMAKE_SYSTEM_NAME}")
  if(CMAKE_CROSSCOMPILING)
    set(_platform "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
    set(CPACK_SYSTEM_NAME "${_platform}")
  endif()
  set(CPACK_PACKAGE_FILE_NAME
    "${PROJECT_NAME}-${PROJECT_VERSION}-${_revision}-${_platform}-${_build}-${CMAKE_CXX_COMPILER_ID}")
  include(CPack)
endfunction()
