cmake_minimum_required(VERSION 3.26)

# Native project generator: no Git, Python, .NET or installed compiler required.
if(NOT DEFINED NAME OR NAME STREQUAL "")
  message(FATAL_ERROR "Usage: cmake -DNAME=MyProject -DOUTPUT=/path/to/MyProject -P scripts/Init.cmake")
endif()
if(NOT NAME MATCHES "^[A-Za-z][A-Za-z0-9]*([_-][A-Za-z0-9]+)*$")
  message(FATAL_ERROR "NAME must start with a letter; single '_' or '-' separators must be between alphanumeric groups")
endif()
string(TOLOWER "${NAME}" _name_lower)
if(_name_lower MATCHES "^(all|clean|help|install|test|package|package_source|edit_cache|rebuild_cache|all_build|zero_check)$")
  message(FATAL_ERROR "NAME '${NAME}' is reserved by the build system")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  set(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${NAME}")
endif()
get_filename_component(_source "${CMAKE_CURRENT_LIST_DIR}/.." REALPATH)
get_filename_component(_output "${OUTPUT}" ABSOLUTE)
if(IS_SYMLINK "${_output}")
  message(FATAL_ERROR "OUTPUT must not be a symbolic link: ${_output}")
endif()
if(EXISTS "${_output}")
  if(NOT IS_DIRECTORY "${_output}")
    message(FATAL_ERROR "OUTPUT is not a directory: ${_output}")
  endif()
  file(GLOB _existing "${_output}/*" "${_output}/.[!.]*" "${_output}/..?*")
  if(_existing)
    message(FATAL_ERROR "OUTPUT must be empty; no files were changed: ${_output}")
  endif()
endif()

# The manifest is deliberately explicit: local SDKs, caches and generated files
# must not become part of somebody else's project.
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/template-files.txt" _files)
file(READ "${CMAKE_CURRENT_LIST_DIR}/template-identity.json" _identity)
foreach(_key IN ITEMS project package image ciImage libraries)
  string(JSON _template_${_key} GET "${_identity}" "${_key}")
endforeach()
foreach(_file IN LISTS _files)
  if(_file MATCHES "^#" OR _file STREQUAL "")
    continue()
  endif()
  if(IS_ABSOLUTE "${_file}" OR _file MATCHES "(^|/)\\.\\.(/|$)" OR
     NOT EXISTS "${_source}/${_file}" OR IS_DIRECTORY "${_source}/${_file}" OR
     IS_SYMLINK "${_source}/${_file}")
    message(FATAL_ERROR "Invalid or missing template file: ${_file}")
  endif()
endforeach()

# Project identity is distinct from the stable boilerplate_* API and example
# library names. Package/container names use kebab-case.
string(REGEX REPLACE "([A-Z]+)([A-Z][a-z])" "\\1-\\2" _slug "${NAME}")
string(REGEX REPLACE "([a-z0-9])([A-Z])" "\\1-\\2" _slug "${_slug}")
string(TOLOWER "${_slug}" _slug)
string(REGEX REPLACE "[_-]+" "-" _slug "${_slug}")
string(REGEX REPLACE "-+$" "" _slug "${_slug}")
file(MAKE_DIRECTORY "${_output}")
foreach(_file IN LISTS _files)
  if(_file MATCHES "^#" OR _file STREQUAL "")
    continue()
  endif()
  get_filename_component(_parent "${_file}" DIRECTORY)
  file(MAKE_DIRECTORY "${_output}/${_parent}")
  file(COPY "${_source}/${_file}" DESTINATION "${_output}/${_parent}")
  # Only these files contain project identity. Do not rewrite generator code,
  # regression fixtures, third-party files or public API names globally.
  if(_file MATCHES "^(CMakeLists.txt|lib/CMakeLists.txt|tests/CMakeLists.txt|Dockerfile|vcpkg.json|README.md|tools/container\\.(sh|ps1)|\\.github/workflows/cmake-multi-platform.yml)$")
    file(READ "${_output}/${_file}" _content)
    string(REPLACE "project(${_template_libraries} " "project(${NAME}Libraries " _content "${_content}")
    string(REPLACE "project(${_template_project} " "project(${NAME} " _content "${_content}")
    string(REPLACE "boilerplate_add_googletest(${_template_project}_tests " "boilerplate_add_googletest(${NAME}_tests " _content "${_content}")
    string(REPLACE "target_include_directories(${_template_project}_tests " "target_include_directories(${NAME}_tests " _content "${_content}")
    string(REPLACE "/bin/${_template_project}\"]" "/bin/${NAME}\"]" _content "${_content}")
    string(REPLACE "--image ${_template_ciImage}" "--image ${_slug}-build" _content "${_content}")
    string(REPLACE "image=${_template_image}\n" "image=${_slug}\n" _content "${_content}")
    string(REPLACE "[string]$Image = '${_template_image}'" "[string]$Image = '${_slug}'" _content "${_content}")
    string(REPLACE "`${_template_image}`" "`${_slug}`" _content "${_content}")
    string(REPLACE "APP[\"${_template_project}\"]" "APP[\"${NAME}\"]" _content "${_content}")
    if(_file STREQUAL "vcpkg.json")
      string(JSON _content SET "${_content}" name "\"${_slug}\"")
      string(APPEND _content "\n")
    elseif(_file STREQUAL "README.md")
      string(REGEX REPLACE "^#[^\n]*" "# ${NAME}" _content "${_content}")
    endif()
    file(WRITE "${_output}/${_file}" "${_content}")
  endif()
endforeach()
file(WRITE "${_output}/scripts/template-identity.json"
  "{\n  \"project\": \"${NAME}\",\n  \"package\": \"${_slug}\",\n  \"image\": \"${_slug}\",\n  \"ciImage\": \"${_slug}-build\",\n  \"libraries\": \"${NAME}Libraries\"\n}\n")
message(STATUS "Created ${NAME} in ${_output} (package/image: ${_slug})")
message(STATUS "Next: cd \"${_output}\"")
message(STATUS "  ./setup.sh --run              # Linux/macOS")
message(STATUS "  .\\setup.ps1 -Run            # Windows")
