# Registry maintenance uses only CMake and Git. Publishing itself stays in gh.
cmake_minimum_required(VERSION 3.26)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
find_program(GIT_EXECUTABLE git REQUIRED)
if(NOT DEFINED ACTION)
  set(ACTION verify)
endif()

function(git output)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROOT}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE value ERROR_VARIABLE error
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "git ${ARGN}: ${error}")
  endif()
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(check_hash value length label)
  string(LENGTH "${value}" actual)
  if(NOT actual EQUAL length OR NOT value MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Invalid ${label}")
  endif()
endfunction()

function(port_revision output manifest)
  string(JSON revision ERROR_VARIABLE error GET "${manifest}" port-version)
  if(error)
    set(revision 0)
  endif()
  set(${output} "${revision}" PARENT_SCOPE)
endfunction()

# JSON string escaping compatible with CMake 3.26.
function(json_quote output value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

file(READ "${ROOT}/vcpkg/release.json" release)
foreach(field IN ITEMS version tag repository commit sha512 vcpkg-baseline)
  string(JSON release_${field} GET "${release}" "${field}")
endforeach()
check_hash("${release_commit}" 40 "source SHA")
check_hash("${release_sha512}" 128 "SHA512")
check_hash("${release_vcpkg-baseline}" 40 "vcpkg baseline")
if(NOT release_version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR "Invalid release version")
endif()
if(NOT release_tag STREQUAL "v${release_version}")
  message(FATAL_ERROR "Release tag/version mismatch")
endif()

function(verify)
  file(READ "${ROOT}/versions/baseline.json" baselines)
  foreach(name IN ITEMS library1 library2)
    file(READ "${ROOT}/ports/${name}/vcpkg.json" manifest)
    string(JSON port_name GET "${manifest}" name)
    string(JSON version GET "${manifest}" version)
    port_revision(revision "${manifest}")
    if(NOT port_name STREQUAL name OR NOT version STREQUAL release_version)
      message(FATAL_ERROR "${name}: port name/release version mismatch")
    endif()
    string(JSON baseline GET "${baselines}" default "${name}")
    string(JSON matches EQUAL "${baseline}"
      "{\"baseline\":\"${version}\",\"port-version\":${revision}}")
    if(NOT matches)
      message(FATAL_ERROR "${name}: baseline mismatch")
    endif()

    string(SUBSTRING "${name}" 0 1 initial)
    file(READ "${ROOT}/versions/${initial}-/${name}.json" history)
    string(JSON count LENGTH "${history}" versions)
    if(count EQUAL 0)
      message(FATAL_ERROR "${name}: missing current version")
    endif()
    math(EXPR last "${count} - 1")
    set(keys)
    set(found FALSE)
    git(tree rev-parse "HEAD:ports/${name}")
    foreach(index RANGE ${last})
      string(JSON entry GET "${history}" versions ${index})
      string(JSON entry_version GET "${entry}" version)
      string(JSON entry_tree GET "${entry}" git-tree)
      port_revision(entry_revision "${entry}")
      set(key "${entry_version}#${entry_revision}")
      if(key IN_LIST keys)
        message(FATAL_ERROR "${name}: duplicate versions")
      endif()
      list(APPEND keys "${key}")
      check_hash("${entry_tree}" 40 "${name} git-tree")
      if(entry_version STREQUAL version AND entry_revision STREQUAL revision)
        set(found TRUE)
        if(NOT entry_tree STREQUAL tree)
          message(FATAL_ERROR "${name}: stale git-tree; run x-add-version after committing ports")
        endif()
      endif()
      # Historical trees must remain accessible; use a full Git checkout.
      git(historic show "${entry_tree}:vcpkg.json")
      string(JSON historic_name GET "${historic}" name)
      string(JSON historic_version GET "${historic}" version)
      port_revision(historic_revision "${historic}")
      if(NOT historic_name STREQUAL name OR NOT historic_version STREQUAL entry_version
          OR NOT historic_revision STREQUAL entry_revision)
        message(FATAL_ERROR "${name}: invalid historical tree")
      endif()
    endforeach()
    if(NOT found)
      message(FATAL_ERROR "${name}: missing current version")
    endif()

    file(READ "${ROOT}/ports/${name}/portfile.cmake" port)
    foreach(field IN ITEMS REPO REF SHA512)
      if(field STREQUAL "REPO")
        set(expected "${release_repository}")
      elseif(field STREQUAL "REF")
        set(expected "${release_commit}")
      else()
        set(expected "${release_sha512}")
      endif()
      string(REGEX MATCH "(^|[ \t\r\n])${field}[ \t\r\n]+([^ \t\r\n)]+)" match "${port}")
      if(NOT match OR NOT CMAKE_MATCH_2 STREQUAL expected)
        message(FATAL_ERROR "${name}: source ${field} mismatch")
      endif()
    endforeach()
    git(source_cmake show "${release_commit}:lib/${name}/CMakeLists.txt")
    string(FIND "${source_cmake}" "project(${name} VERSION ${version} " position)
    if(position EQUAL -1)
      message(FATAL_ERROR "${name}: source project version mismatch")
    endif()
  endforeach()
  message(STATUS "Registry versions, git trees and source pins verified")
endfunction()

function(prepare output repository baseline)
  check_hash("${baseline}" 40 "registry baseline (full commit SHA required)")
  if(EXISTS "${output}" OR IS_SYMLINK "${output}")
    message(FATAL_ERROR "Consumer output must not already exist: ${output}")
  endif()
  json_quote(repository_json "${repository}")
  file(COPY "${ROOT}/tests/registry-consumer/" DESTINATION "${output}")
  file(WRITE "${output}/vcpkg-configuration.json"
    "{\n  \"default-registry\": {\n    \"kind\": \"builtin\",\n"
    "    \"baseline\": \"${release_vcpkg-baseline}\"\n  },\n  \"registries\": [{\n"
    "    \"kind\": \"git\",\n    \"repository\": ${repository_json},\n"
    "    \"baseline\": \"${baseline}\",\n    \"packages\": [\"library1\", \"library2\"]\n  }]\n}\n")
  message(STATUS "Independent consumer: ${output}")
endfunction()

if(ACTION STREQUAL "verify")
  verify()
elseif(ACTION STREQUAL "pins")
  if(NOT OUTPUT)
    message(FATAL_ERROR "Pass -DOUTPUT=<GitHub output file>")
  endif()
  file(APPEND "${OUTPUT}" "vcpkg=${release_vcpkg-baseline}\n")
elseif(ACTION STREQUAL "prepare" OR ACTION STREQUAL "release")
  if(NOT OUTPUT)
    message(FATAL_ERROR "Pass -DOUTPUT=<fresh output directory>")
  endif()
  get_filename_component(OUTPUT "${OUTPUT}" ABSOLUTE)
  if(ACTION STREQUAL "prepare")
    if(NOT DEFINED BASELINE)
      git(BASELINE rev-parse HEAD)
    endif()
    if(NOT DEFINED REPOSITORY)
      # Git accepts native absolute paths, including C:/... on Windows.
      set(REPOSITORY "${ROOT}")
    endif()
    prepare("${OUTPUT}" "${REPOSITORY}" "${BASELINE}")
  else()
    verify()
    if(NOT RELEASE_REPOSITORY STREQUAL release_repository)
      message(FATAL_ERROR "Update source pins before publishing from a fork")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROOT}" rev-parse --verify
      "refs/tags/${release_tag}^{commit}" RESULT_VARIABLE result
      OUTPUT_VARIABLE existing ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(result STREQUAL "0" AND NOT existing STREQUAL release_commit)
      message(FATAL_ERROR "${release_tag} already points to a different source commit")
    endif()
    if(EXISTS "${OUTPUT}" OR IS_SYMLINK "${OUTPUT}")
      message(FATAL_ERROR "Release output must not already exist: ${OUTPUT}")
    endif()
    git(BASELINE rev-parse HEAD)
    prepare("${OUTPUT}/consumer" "https://github.com/${RELEASE_REPOSITORY}.git" "${BASELINE}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${OUTPUT}/registry-consumer.zip"
      --format=zip -- CMakeLists.txt main.cpp vcpkg.json vcpkg-configuration.json
      WORKING_DIRECTORY "${OUTPUT}/consumer" COMMAND_ERROR_IS_FATAL ANY)
    file(WRITE "${OUTPUT}/release-notes.md"
      "library1 and library2 ${release_version}\n\nSource tag: `${release_tag}`\n\n"
      "Source commit: `${release_commit}`\n\nSource archive SHA512: `${release_sha512}`\n\n"
      "vcpkg Git registry baseline: `${BASELINE}`\n\n"
      "The attached consumer uses this exact registry baseline. Install its manifest with vcpkg, "
      "then configure CMake with the vcpkg toolchain. See the repository's vcpkg/README.md.\n")
    if(DEFINED ENV{GITHUB_ENV})
      file(APPEND "$ENV{GITHUB_ENV}" "RELEASE_TAG=${release_tag}\nSOURCE_COMMIT=${release_commit}\n")
    endif()
    message(STATUS "Release archive and notes: ${OUTPUT}")
  endif()
else()
  message(FATAL_ERROR "ACTION must be verify, prepare, pins or release")
endif()
