cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY OR EXISTS "${CHECK_BINARY}")
  message(FATAL_ERROR "Pass -DCHECK_BINARY=<fresh temporary directory>")
endif()
get_filename_component(CHECK_BINARY "${CHECK_BINARY}" ABSOLUTE)
get_filename_component(source "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
find_program(git git REQUIRED)
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Failed: ${ARGV}\n${out}\n${err}")
  endif()
endfunction()
function(reject expected)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(result STREQUAL "0" OR NOT "${out}\n${err}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected '${expected}': ${ARGN}\n${out}\n${err}")
  endif()
endfunction()
function(reject_json path content expected)
  file(READ "${root}/${path}" original)
  file(WRITE "${root}/${path}" "${content}\n")
  reject("${expected}" "${CMAKE_COMMAND}" -P "${script}")
  file(WRITE "${root}/${path}" "${original}")
endfunction()

# A real Git clone exercises committed and historical trees, with spaces in paths.
set(root "${CHECK_BINARY}/registry with spaces")
set(script "${root}/scripts/Registry.cmake")
run("${git}" clone --quiet --shared "${source}" "${root}")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/Registry.cmake" DESTINATION "${root}/scripts")
run("${CMAKE_COMMAND}" -P "${script}")
file(READ "${root}/vcpkg/release.json" release)
string(JSON repository GET "${release}" repository)
string(JSON commit GET "${release}" commit)
string(JSON tag GET "${release}" tag)
string(JSON pin GET "${release}" vcpkg-baseline)

file(READ "${root}/versions/baseline.json" baseline)
string(JSON bad SET "${baseline}" default library1 port-version 1)
reject_json(versions/baseline.json "${bad}" "baseline mismatch")
file(READ "${root}/versions/l-/library1.json" history)
string(JSON entry GET "${history}" versions 0)
string(JSON bad SET "${history}" versions 1 "${entry}")
reject_json(versions/l-/library1.json "${bad}" "duplicate versions")
string(JSON bad SET "${history}" versions 0 git-tree "\"${commit}\"")
reject_json(versions/l-/library1.json "${bad}" "stale git-tree")
string(JSON older SET "${entry}" version "\"0.9.0\"")
string(JSON bad SET "${history}" versions 1 "${older}")
reject_json(versions/l-/library1.json "${bad}" "invalid historical tree")
reject_json(versions/l-/library1.json "{\"versions\":[]}" "missing current version")
string(JSON bad SET "${release}" commit "\"1234\"")
reject_json(vcpkg/release.json "${bad}" "Invalid source SHA")
string(JSON bad SET "${release}" tag "\"v9.9.9\"")
reject_json(vcpkg/release.json "${bad}" "Release tag/version mismatch")
file(READ "${root}/ports/library1/portfile.cmake" port)
string(REPLACE "REF ${commit}" "REF 0000000000000000000000000000000000000000" bad "${port}")
reject_json(ports/library1/portfile.cmake "${bad}" "source REF mismatch")

run("${CMAKE_COMMAND}" -DACTION=pins "-DOUTPUT=${CHECK_BINARY}/pins" -P "${script}")
file(READ "${CHECK_BINARY}/pins" actual)
if(NOT actual STREQUAL "vcpkg=${pin}\n")
  message(FATAL_ERROR "Incorrect GitHub output: ${actual}")
endif()
set(consumer "${CHECK_BINARY}/consumer with spaces")
run("${CMAKE_COMMAND}" -DACTION=prepare "-DOUTPUT=${consumer}" -P "${script}")
file(READ "${consumer}/vcpkg-configuration.json" config)
string(JSON local_repository GET "${config}" registries 0 repository)
string(JSON local_baseline GET "${config}" registries 0 baseline)
execute_process(COMMAND "${git}" -C "${root}" rev-parse HEAD
  OUTPUT_VARIABLE head OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT local_repository STREQUAL root OR NOT local_baseline STREQUAL head)
  message(FATAL_ERROR "Default consumer must use the local checkout and HEAD")
endif()
reject("must not already exist" "${CMAKE_COMMAND}" -DACTION=prepare "-DOUTPUT=${consumer}" -P "${script}")
reject("Invalid registry baseline" "${CMAKE_COMMAND}" -DACTION=prepare
  "-DOUTPUT=${CHECK_BINARY}/bad" -DBASELINE=1234 -P "${script}")
# Explicit repository strings are JSON-escaped, including Windows backslashes.
set(remote "C:\\registry with spaces\\quoted\"name")
run("${CMAKE_COMMAND}" -DACTION=prepare "-DOUTPUT=${CHECK_BINARY}/explicit"
  "-DREPOSITORY=${remote}" "-DBASELINE=${commit}" -P "${script}")
file(READ "${CHECK_BINARY}/explicit/vcpkg-configuration.json" config)
string(JSON actual GET "${config}" registries 0 repository)
if(NOT actual STREQUAL remote)
  message(FATAL_ERROR "Repository JSON escaping failed")
endif()

set(artifacts "${CHECK_BINARY}/release artifacts")
set(ENV{GITHUB_ENV} "${CHECK_BINARY}/github-env")
run("${CMAKE_COMMAND}" -DACTION=release "-DOUTPUT=${artifacts}"
  "-DRELEASE_REPOSITORY=${repository}" -P "${script}")
file(READ "${CHECK_BINARY}/github-env" actual)
if(NOT actual STREQUAL "RELEASE_TAG=${tag}\nSOURCE_COMMIT=${commit}\n")
  message(FATAL_ERROR "Incorrect GitHub release environment: ${actual}")
endif()
file(ARCHIVE_EXTRACT INPUT "${artifacts}/registry-consumer.zip" DESTINATION "${CHECK_BINARY}/unpacked")
foreach(name IN ITEMS CMakeLists.txt main.cpp vcpkg.json vcpkg-configuration.json)
  run("${CMAKE_COMMAND}" -E compare_files "${artifacts}/consumer/${name}" "${CHECK_BINARY}/unpacked/${name}")
endforeach()
file(READ "${CHECK_BINARY}/unpacked/vcpkg-configuration.json" config)
string(JSON actual GET "${config}" registries 0 baseline)
string(JSON remote GET "${config}" registries 0 repository)
file(READ "${artifacts}/release-notes.md" notes)
if(NOT actual STREQUAL head OR NOT remote STREQUAL "https://github.com/${repository}.git"
    OR NOT notes MATCHES "${head}" OR NOT notes MATCHES "${commit}")
  message(FATAL_ERROR "Release consumer/notes do not contain the tested pins")
endif()
reject("publishing from a fork" "${CMAKE_COMMAND}" -DACTION=release
  "-DOUTPUT=${CHECK_BINARY}/fork" -DRELEASE_REPOSITORY=other/fork -P "${script}")
run("${git}" -C "${root}" tag -f "${tag}" HEAD)
reject("different source commit" "${CMAKE_COMMAND}" -DACTION=release
  "-DOUTPUT=${CHECK_BINARY}/conflict" "-DRELEASE_REPOSITORY=${repository}" -P "${script}")
message(STATUS "Registry validation, consumer paths, release archive and rejection checks passed")
