cmake_minimum_required(VERSION 3.26)
if(NOT CHECK_BINARY OR EXISTS "${CHECK_BINARY}")
  message(FATAL_ERROR "Pass -DCHECK_BINARY=<fresh temporary directory>")
endif()
get_filename_component(CHECK_BINARY "${CHECK_BINARY}" ABSOLUTE)
set(_script "${CMAKE_CURRENT_LIST_DIR}/TemplateManifest.cmake")
find_program(_git git REQUIRED)
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "Failed: ${ARGV}\n${_out}\n${_err}")
  endif()
endfunction()
function(reject)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
  if(_rc STREQUAL "0")
    message(FATAL_ERROR "Expected failure: ${ARGV}")
  endif()
endfunction()
file(MAKE_DIRECTORY "${CHECK_BINARY}/scripts" "${CHECK_BINARY}/lib/cmake/build" "${CHECK_BINARY}/docs")
file(WRITE "${CHECK_BINARY}/CMakeLists.txt" "# fixture\n")
file(WRITE "${CHECK_BINARY}/lib/cmake/build/Keep.cmake" "# source, not build output\n")
file(WRITE "${CHECK_BINARY}/docs/generated.txt" "exclude\n")
file(WRITE "${CHECK_BINARY}/lib/.env" "exclude\n")
file(WRITE "${CHECK_BINARY}/scripts/template-files.txt" "# stale\n")
run("${_git}" init "${CHECK_BINARY}")
run("${_git}" -C "${CHECK_BINARY}" add .)
# Untracked files never participate, even when their directory is included.
file(WRITE "${CHECK_BINARY}/scripts/local-secret.txt" "do not copy\n")
reject("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -P "${_script}")
run("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -DACTION=update -P "${_script}")
run("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -P "${_script}")
file(READ "${CHECK_BINARY}/scripts/template-files.txt" _manifest)
if(NOT _manifest MATCHES "lib/cmake/build/Keep.cmake" OR _manifest MATCHES "generated.txt|local-secret|lib/\\.env")
  message(FATAL_ERROR "Policy did not select the expected payload: ${_manifest}")
endif()
file(WRITE "${CHECK_BINARY}/scripts/New.cmake" "# newly tracked source\n")
run("${_git}" -C "${CHECK_BINARY}" add scripts/New.cmake)
reject("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -P "${_script}")
run("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -DACTION=update -P "${_script}")
run("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -P "${_script}")
file(SHA256 "${CHECK_BINARY}/scripts/template-files.txt" _before)
file(WRITE "${CHECK_BINARY}/unclassified.txt" "requires a policy decision\n")
run("${_git}" -C "${CHECK_BINARY}" add unclassified.txt)
reject("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -DACTION=update -P "${_script}")
file(SHA256 "${CHECK_BINARY}/scripts/template-files.txt" _after)
if(NOT _before STREQUAL _after)
  message(FATAL_ERROR "Failed policy validation changed the manifest")
endif()
run("${_git}" -C "${CHECK_BINARY}" rm --cached unclassified.txt)
file(APPEND "${CHECK_BINARY}/scripts/template-files.txt" "scripts/local-secret.txt\n")
reject("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -P "${_script}")
run("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -DACTION=update -P "${_script}")
file(APPEND "${CHECK_BINARY}/scripts/template-files.txt" "CMakeLists.txt\n")
reject("${CMAKE_COMMAND}" "-DSOURCE_DIR=${CHECK_BINARY}" -P "${_script}")
message(STATUS "Template policy, drift, untracked files and duplicate checks passed")
