cmake_minimum_required(VERSION 3.26)
if(NOT PACKAGE_DIR OR NOT PACKAGE_FORMAT)
  message(FATAL_ERROR "Set PACKAGE_DIR and PACKAGE_FORMAT")
endif()
set(_pattern "")
if(PACKAGE_FORMAT STREQUAL "ARCH")
  set(_pattern "*.pkg.tar.zst")
elseif(PACKAGE_FORMAT STREQUAL "DEB")
  set(_pattern "*.deb")
elseif(PACKAGE_FORMAT STREQUAL "RPM")
  set(_pattern "*.rpm")
elseif(PACKAGE_FORMAT STREQUAL "TGZ")
  set(_pattern "*.tar.gz")
elseif(PACKAGE_FORMAT STREQUAL "NSIS")
  set(_pattern "*.exe")
elseif(PACKAGE_FORMAT STREQUAL "DragNDrop")
  set(_pattern "*.dmg")
elseif(PACKAGE_FORMAT STREQUAL "ZIP")
  set(_pattern "*.zip")
else()
  message(FATAL_ERROR "Unknown package format ${PACKAGE_FORMAT}")
endif()
file(GLOB _artifacts "${PACKAGE_DIR}/${_pattern}")
if(NOT _artifacts)
  message(FATAL_ERROR "Expected ${_pattern} in ${PACKAGE_DIR}")
endif()
set(_verified_arch 0)
foreach(_artifact IN LISTS _artifacts)
  file(SIZE "${_artifact}" _size)
  if(_size LESS 100)
    message(FATAL_ERROR "Package empty: ${_artifact}")
  endif()
  if(PACKAGE_FORMAT STREQUAL "ARCH")
    # makepkg may emit a separate -debug package on distributions whose
    # makepkg.conf enables split-debug; it does not contain the runtime exe.
    if(_artifact MATCHES "-debug-[0-9][^/]*\\.pkg\\.tar\\.zst$")
      message(STATUS "Skipping auxiliary Arch debug package: ${_artifact}")
      continue()
    endif()
    find_program(_bsdtar bsdtar REQUIRED)
    execute_process(COMMAND "${_bsdtar}" -tf "${_artifact}"
      OUTPUT_VARIABLE _contents RESULT_VARIABLE _rc ERROR_VARIABLE _err)
    if(NOT _rc EQUAL 0 OR NOT _contents MATCHES "(^|\n)usr/bin/[^\n]+")
      message(FATAL_ERROR "Invalid native Arch package content: ${_artifact}: ${_err}")
    endif()
    math(EXPR _verified_arch "${_verified_arch} + 1")
  elseif(PACKAGE_FORMAT STREQUAL "DEB")
    execute_process(COMMAND dpkg-deb --contents "${_artifact}"
      RESULT_VARIABLE _rc OUTPUT_VARIABLE _contents ERROR_VARIABLE _err)
    if(NOT _rc EQUAL 0 OR NOT _contents MATCHES "usr/bin/")
      message(FATAL_ERROR "Invalid DEB payload: ${_artifact}: ${_err}")
    endif()
  elseif(PACKAGE_FORMAT STREQUAL "RPM")
    execute_process(COMMAND rpm -qpl "${_artifact}"
      RESULT_VARIABLE _rc OUTPUT_VARIABLE _contents ERROR_VARIABLE _err)
    if(NOT _rc EQUAL 0 OR NOT _contents MATCHES "/usr/bin/")
      message(FATAL_ERROR "Invalid RPM payload: ${_artifact}: ${_err}")
    endif()
  endif()
  message(STATUS "Verified ${PACKAGE_FORMAT}: ${_artifact} (${_size} bytes)")
endforeach()
if(PACKAGE_FORMAT STREQUAL "ARCH" AND _verified_arch EQUAL 0)
  message(FATAL_ERROR "No runtime Arch package was verified in ${PACKAGE_DIR}")
endif()
