cmake_minimum_required(VERSION 3.26)

get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT ACTION)
  message(FATAL_ERROR "Pass -DACTION=build|test|dev|shell|run|clean")
endif()
if(NOT DOCKER)
  find_program(DOCKER NAMES docker podman REQUIRED)
endif()
if(NOT IMAGE)
  set(IMAGE cmake-boilerplate)
endif()
if(NOT PRESET)
  set(PRESET app-release)
endif()

function(run)
  message(STATUS "+ ${ARGV}")
  execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "Command failed (${_rc}): ${ARGV}")
  endif()
endfunction()

function(build_image target tag)
  set(_cmd "${DOCKER}" build --target "${target}" --build-arg "CMAKE_PRESET=${PRESET}")
  if(BASE_IMAGE)
    list(APPEND _cmd --build-arg "DEBIAN_IMAGE=${BASE_IMAGE}")
  endif()
  if(PULL)
    list(APPEND _cmd --pull)
  endif()
  if(NO_CACHE)
    list(APPEND _cmd --no-cache)
  endif()
  list(APPEND _cmd -t "${tag}" "${ROOT}")
  run(${_cmd})
endfunction()

if(ACTION STREQUAL "build")
  build_image(runtime "${IMAGE}")
elseif(ACTION STREQUAL "test")
  build_image(test "${IMAGE}:test")
elseif(ACTION STREQUAL "dev")
  build_image(dev "${IMAGE}:dev")
elseif(ACTION STREQUAL "shell")
  if(NOT NO_BUILD)
    build_image(dev "${IMAGE}:dev")
  endif()
  if(NOT SHELL)
    set(SHELL bash)
  endif()
  # execute_process inherits the terminal, so interactive shells work when the
  # CMake script itself is launched from a terminal.
  run("${DOCKER}" run --rm -it -v "${ROOT}:/workspace" -w /workspace "${IMAGE}:dev" "${SHELL}")
elseif(ACTION STREQUAL "run")
  if(NOT NO_BUILD)
    build_image(runtime "${IMAGE}")
  endif()
  run("${DOCKER}" run --rm "${IMAGE}" ${APP_ARGS})
elseif(ACTION STREQUAL "clean")
  foreach(_tag IN ITEMS "${IMAGE}" "${IMAGE}:dev" "${IMAGE}:test")
    execute_process(COMMAND "${DOCKER}" image rm -f "${_tag}" WORKING_DIRECTORY "${ROOT}")
  endforeach()
else()
  message(FATAL_ERROR "Unknown ACTION=${ACTION}")
endif()
