include_guard(GLOBAL)
include(GNUInstallDirs)
include(GenerateExportHeader)

# The application is a loadable program image, not a linkable library. MAIN
# entrypoint mode generates the small stable C ABI wrapper around
# boilerplate_application_main(argc, argv). CUSTOM leaves the bootstrap symbol
# entirely to the application implementation.
function(boilerplate_add_application_module target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "VERSION;ENTRYPOINT"
    "SOURCES;RUNTIMES;LIBRARIES;PLUGINS;INCLUDE_DIRS;RESOURCE_DIRS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_application_module(${target}): SOURCES required; invalid arguments")
  endif()
  if(NOT ARG_ENTRYPOINT)
    set(ARG_ENTRYPOINT MAIN)
  endif()
  string(TOUPPER "${ARG_ENTRYPOINT}" ARG_ENTRYPOINT)
  if(NOT ARG_ENTRYPOINT MATCHES "^(MAIN|CUSTOM)$")
    message(FATAL_ERROR "boilerplate_add_application_module(${target}): ENTRYPOINT must be MAIN or CUSTOM")
  endif()
  _boilerplate_validate_link_dependencies(${target} ${ARG_LIBRARIES} ${ARG_RUNTIMES})
  foreach(_library IN LISTS ARG_LIBRARIES)
    if(TARGET ${_library})
      boilerplate_get_artifact_role(${_library} _library_role)
      if(_library_role STREQUAL "RUNTIME")
        message(FATAL_ERROR
          "Application ${target}: runtime ${_library} must be declared in RUNTIMES, not LIBRARIES")
      endif()
    endif()
  endforeach()
  foreach(_runtime IN LISTS ARG_RUNTIMES)
    _boilerplate_require_artifact_role(${_runtime} "RUNTIME" "Application ${target} RUNTIMES")
  endforeach()
  foreach(_plugin IN LISTS ARG_PLUGINS)
    _boilerplate_require_artifact_role(${_plugin} "PLUGIN" "Application ${target} PLUGINS")
  endforeach()

  string(MAKE_C_IDENTIFIER "${target}" _prefix)
  string(TOUPPER "${_prefix}" _prefix)
  set(_generated "${CMAKE_CURRENT_BINARY_DIR}/generated/${target}")
  file(MAKE_DIRECTORY "${_generated}")
  set(_sources ${ARG_SOURCES})
  if(ARG_ENTRYPOINT STREQUAL "MAIN")
    set(BOILERPLATE_APPLICATION_EXPORT_HEADER "${target}_export.h")
    set(BOILERPLATE_APPLICATION_EXPORT_MACRO "${_prefix}_EXPORT")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/host/ApplicationEntry.cpp.in"
      "${_generated}/${target}_entry.cpp" @ONLY)
    list(APPEND _sources "${_generated}/${target}_entry.cpp")
  endif()

  add_library(${target} MODULE ${_sources})
  boilerplate_set_artifact_role(${target} APPLICATION)
  set_target_properties(${target} PROPERTIES
    PREFIX "" POSITION_INDEPENDENT_CODE ON
    CXX_EXTENSIONS OFF CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON
    DEFINE_SYMBOL "${_prefix}_EXPORTS"
    BOILERPLATE_APPLICATION_ENTRYPOINT_MODE "${ARG_ENTRYPOINT}")
  if(ARG_VERSION)
    set_property(TARGET ${target} PROPERTY BOILERPLATE_APPLICATION_VERSION "${ARG_VERSION}")
  endif()
  generate_export_header(${target} BASE_NAME "${_prefix}"
    EXPORT_FILE_NAME "${_generated}/${target}_export.h"
    EXPORT_MACRO_NAME "${_prefix}_EXPORT")
  target_include_directories(${target} PRIVATE
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/host/include" "${_generated}" ${ARG_INCLUDE_DIRS})
  target_link_libraries(${target} PRIVATE ${ARG_RUNTIMES} ${ARG_LIBRARIES})
  _boilerplate_apply_semantic_target_policy(${target}
    POLICIES ${ARG_POLICIES} POLICY_OPTIONS ${ARG_POLICY_OPTIONS})
  boilerplate_set_output_name(${target} "${target}")
  if(WIN32)
    _boilerplate_get_core_module_dir(_core_modules)
    add_custom_command(TARGET ${target} POST_BUILD
      COMMAND "${CMAKE_COMMAND}" "-DRUNTIME_FILES=$<TARGET_RUNTIME_DLLS:${target}>"
        "-DDESTINATION=$<TARGET_FILE_DIR:${target}>"
        -P "${_core_modules}/packaging/CopyRuntimeLibraries.cmake" VERBATIM)
  endif()

  set(_application_libraries)
  foreach(_dependency IN LISTS ARG_LIBRARIES)
    if(TARGET ${_dependency})
      _boilerplate_real_target(${_dependency} _real_dependency)
      get_target_property(_dependency_type ${_real_dependency} TYPE)
      if(_dependency_type STREQUAL "SHARED_LIBRARY")
        list(APPEND _application_libraries ${_dependency})
      endif()
    endif()
  endforeach()
  if(_application_libraries)
    set_property(TARGET ${target} PROPERTY BOILERPLATE_APPLICATION_LIBRARIES "${_application_libraries}")
  endif()

  if(ARG_RUNTIMES)
    set_property(TARGET ${target} PROPERTY BOILERPLATE_APPLICATION_RUNTIMES "${ARG_RUNTIMES}")
    foreach(_runtime IN LISTS ARG_RUNTIMES)
      _boilerplate_append_target_property(${_runtime} BOILERPLATE_OWNING_APPLICATIONS ${target})
    endforeach()
  endif()
  if(ARG_PLUGINS)
    foreach(_plugin IN LISTS ARG_PLUGINS)
      boilerplate_application_use_plugin(${target} ${_plugin})
    endforeach()
  endif()
  if(ARG_RESOURCE_DIRS)
    set_property(TARGET ${target} PROPERTY BOILERPLATE_APPLICATION_RESOURCE_DIRS "${ARG_RESOURCE_DIRS}")
  endif()

  boilerplate_get_target_setting(${target} CFI _cfi)
  boilerplate_get_target_setting(${target} CFI_DIAGNOSTICS _diagnostics)
  if(NOT _cfi STREQUAL "none" AND _diagnostics)
    message(FATAL_ERROR
      "Application ${target}: diagnostic CFI requires a host-owned UBSan runtime; use trap mode or a custom host/runtime arrangement")
  endif()
endfunction()

# Happy path: one application image plus one generated/default host. Additional
# hosts can be attached later with boilerplate_add_apphost(). The semantic root
# remains <name>; the default host target is <name>_host and its file is <name>.
function(boilerplate_add_application name)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "NO_DEFAULT_HOST" "VERSION;ENTRYPOINT;HOST;HOST_KIND"
    "SOURCES;RUNTIMES;LIBRARIES;PLUGINS;INCLUDE_DIRS;RESOURCE_DIRS;POLICIES;POLICY_OPTIONS;HOST_LIBRARIES;HOST_POLICIES;HOST_POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT ARG_SOURCES)
    message(FATAL_ERROR "boilerplate_add_application(${name}): SOURCES required; invalid arguments")
  endif()
  set(_module_args SOURCES ${ARG_SOURCES})
  foreach(_one IN ITEMS VERSION ENTRYPOINT)
    if(ARG_${_one})
      list(APPEND _module_args ${_one} "${ARG_${_one}}")
    endif()
  endforeach()
  foreach(_many IN ITEMS RUNTIMES LIBRARIES PLUGINS INCLUDE_DIRS RESOURCE_DIRS POLICIES POLICY_OPTIONS)
    if(ARG_${_many})
      list(APPEND _module_args ${_many} ${ARG_${_many}})
    endif()
  endforeach()
  boilerplate_add_application_module(${name} ${_module_args})

  if(NOT ARG_NO_DEFAULT_HOST)
    if(ARG_HOST)
      set(_host "${ARG_HOST}")
    else()
      set(_host "${name}_host")
    endif()
    set(_host_args OUTPUT_NAME ${name})
    if(ARG_HOST_KIND)
      list(APPEND _host_args KIND ${ARG_HOST_KIND})
    endif()
    if(ARG_HOST_LIBRARIES)
      list(APPEND _host_args LIBRARIES ${ARG_HOST_LIBRARIES})
    endif()
    if(ARG_HOST_POLICIES)
      list(APPEND _host_args POLICIES ${ARG_HOST_POLICIES})
    elseif(ARG_POLICIES)
      list(APPEND _host_args POLICIES ${ARG_POLICIES})
    endif()
    if(ARG_HOST_POLICY_OPTIONS)
      list(APPEND _host_args POLICY_OPTIONS ${ARG_HOST_POLICY_OPTIONS})
    elseif(ARG_POLICY_OPTIONS)
      list(APPEND _host_args POLICY_OPTIONS ${ARG_POLICY_OPTIONS})
    endif()
    boilerplate_add_host(${_host} ${_host_args})
    boilerplate_host_application(${_host} ${name})
    set_property(TARGET ${name} PROPERTY BOILERPLATE_APPLICATION_DEFAULT_HOST "${_host}")
  endif()
endfunction()
