# Full component/execution framework. The reusable library slice remains in
# lib/cmake and can be copied/built independently.
include_guard(GLOBAL)
if(DEFINED BOILERPLATE_CORE_MODULE_DIR)
  get_filename_component(_boilerplate_core "${BOILERPLATE_CORE_MODULE_DIR}" ABSOLUTE)
else()
  get_filename_component(_boilerplate_core "${CMAKE_CURRENT_LIST_DIR}/../lib/cmake" ABSOLUTE)
endif()
set_property(GLOBAL PROPERTY BOILERPLATE_CORE_MODULE_DIR "${_boilerplate_core}")
include("${_boilerplate_core}/Boilerplate.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/SemanticTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Runtime.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Hosting.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Application.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Plugins.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/Deployment.cmake")
