include_guard(GLOBAL)
include(GNUInstallDirs)

function(_boilerplate_deploy_rpath target destination library_destination)
  file(RELATIVE_PATH _relative "/${destination}" "/${library_destination}")
  if(APPLE)
    set(_origin "@loader_path")
  elseif(UNIX)
    set(_origin "$ORIGIN")
  else()
    return()
  endif()
  set(_paths "${_origin}")
  if(_relative AND NOT _relative STREQUAL ".")
    list(APPEND _paths "${_origin}/${_relative}")
  endif()
  set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH ${_paths})
endfunction()

function(_boilerplate_validate_relocatable_install_dirs)
  foreach(_dir IN ITEMS CMAKE_INSTALL_BINDIR CMAKE_INSTALL_LIBDIR CMAKE_INSTALL_DATADIR)
    if(IS_ABSOLUTE "${${_dir}}" OR "${${_dir}}" MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "Relocatable deployment requires a relative ${_dir}")
    endif()
  endforeach()
endfunction()

function(_boilerplate_collect_runtime_graph out_runtimes out_libraries)
  set(_queue ${ARGN})
  set(_runtimes)
  set(_libraries)
  while(_queue)
    list(POP_FRONT _queue _item)
    if(NOT TARGET ${_item})
      message(FATAL_ERROR "Runtime graph contains non-target dependency: ${_item}")
    endif()
    _boilerplate_real_target(${_item} _real)
    if(_real IN_LIST _runtimes)
      continue()
    endif()
    boilerplate_get_artifact_role(${_real} _role)
    if(NOT _role STREQUAL "RUNTIME")
      message(FATAL_ERROR "Runtime graph requires RUNTIME artifacts, got ${_item} (${_role})")
    endif()
    list(APPEND _runtimes ${_real})
    get_target_property(_deps ${_real} BOILERPLATE_RUNTIME_DEPENDENCIES)
    if(_deps)
      list(APPEND _queue ${_deps})
    endif()
    get_target_property(_libs ${_real} BOILERPLATE_RUNTIME_LIBRARIES)
    if(_libs)
      list(APPEND _libraries ${_libs})
    endif()
  endwhile()
  if(_libraries)
    set(_real_libraries)
    foreach(_library IN LISTS _libraries)
      _boilerplate_real_target(${_library} _real)
      list(APPEND _real_libraries ${_real})
    endforeach()
    list(REMOVE_DUPLICATES _real_libraries)
    set(_libraries ${_real_libraries})
  endif()
  set(${out_runtimes} "${_runtimes}" PARENT_SCOPE)
  set(${out_libraries} "${_libraries}" PARENT_SCOPE)
endfunction()

function(_boilerplate_install_owned_target target destination dependency_set)
  _boilerplate_real_target(${target} _real)
  get_target_property(_imported ${_real} IMPORTED)
  set(_set_args)
  if(dependency_set)
    list(APPEND _set_args RUNTIME_DEPENDENCY_SET "${dependency_set}")
  endif()
  if(_imported)
    install(IMPORTED_RUNTIME_ARTIFACTS ${_real} ${_set_args}
      RUNTIME DESTINATION "${destination}" COMPONENT Runtime
      LIBRARY DESTINATION "${destination}" COMPONENT Runtime)
  else()
    install(TARGETS ${_real} ${_set_args}
      RUNTIME DESTINATION "${destination}" COMPONENT Runtime
      LIBRARY DESTINATION "${destination}" COMPONENT Runtime)
  endif()
endfunction()

function(_boilerplate_install_semantic_application target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "NO_RUNTIME_DEPENDENCIES" ""
    "HOSTS;RUNTIMES;LIBRARIES;PLUGINS;RESOURCE_DIRS;RUNTIME_DIRS;PRE_EXCLUDE_REGEXES;POST_EXCLUDE_REGEXES")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "boilerplate_install_application(${target}): invalid arguments")
  endif()
  if(NOT BOILERPLATE_INSTALL)
    return()
  endif()
  _boilerplate_require_artifact_role(${target} "APPLICATION" "boilerplate_install_application")
  get_target_property(_done ${target} BOILERPLATE_DEPLOYMENT)
  if(_done)
    message(FATAL_ERROR "Application deployment may be registered only once: ${target}")
  endif()
  if(CMAKE_CROSSCOMPILING AND NOT ARG_NO_RUNTIME_DEPENDENCIES)
    message(FATAL_ERROR "Cross deployment requires NO_RUNTIME_DEPENDENCIES and explicit target-platform packaging")
  endif()
  _boilerplate_validate_relocatable_install_dirs()
  set_property(TARGET ${target} PROPERTY BOILERPLATE_DEPLOYMENT TRUE)

  get_target_property(_registered_hosts ${target} BOILERPLATE_APPLICATION_HOSTS)
  get_target_property(_registered_runtimes ${target} BOILERPLATE_APPLICATION_RUNTIMES)
  get_target_property(_registered_libraries ${target} BOILERPLATE_APPLICATION_LIBRARIES)
  get_target_property(_registered_plugins ${target} BOILERPLATE_APPLICATION_PLUGINS)
  get_target_property(_registered_resources ${target} BOILERPLATE_APPLICATION_RESOURCE_DIRS)
  foreach(_property_value IN ITEMS _registered_hosts _registered_runtimes _registered_libraries _registered_plugins _registered_resources)
    if("${${_property_value}}" MATCHES "-NOTFOUND$")
      set(${_property_value})
    endif()
  endforeach()
  set(_application_hosts ${_registered_hosts} ${ARG_HOSTS})
  set(_runtime_roots ${_registered_runtimes} ${ARG_RUNTIMES})
  set(_libraries ${_registered_libraries} ${ARG_LIBRARIES})
  set(_plugins ${_registered_plugins} ${ARG_PLUGINS})
  set(_resource_dirs ${_registered_resources} ${ARG_RESOURCE_DIRS})
  foreach(_list IN ITEMS _application_hosts _runtime_roots _libraries _plugins _resource_dirs)
    if(NOT "${${_list}}" STREQUAL "")
      list(REMOVE_DUPLICATES ${_list})
    endif()
  endforeach()

  # HOST -> APPLICATION and APPLICATION -> PLUGIN are different relations.
  # Application hosts own the process for the primary workload; plugins are
  # co-hosted there by default, but explicit HOST -> PLUGIN edges move their
  # execution placement to those hosts. Both host kinds remain part of the
  # application's deployment product.
  foreach(_host IN LISTS _application_hosts)
    _boilerplate_require_artifact_role(${_host} "HOST" "Application ${target} HOSTS")
    get_target_property(_host_apps ${_host} BOILERPLATE_HOSTED_APPLICATIONS)
    if(NOT target IN_LIST _host_apps)
      message(FATAL_ERROR "Host ${_host} does not host application ${target}; hosted applications: ${_host_apps}")
    endif()
    get_target_property(_host_plugins ${_host} BOILERPLATE_HOSTED_PLUGINS)
    if(_host_plugins AND NOT _host_plugins MATCHES "-NOTFOUND$")
      list(APPEND _plugins ${_host_plugins})
    endif()
  endforeach()
  if(_plugins)
    list(REMOVE_DUPLICATES _plugins)
  endif()
  set(_plugin_hosts)
  foreach(_plugin IN LISTS _plugins)
    _boilerplate_require_artifact_role(${_plugin} "PLUGIN" "Application ${target} PLUGINS")
    get_target_property(_explicit_plugin_hosts ${_plugin} BOILERPLATE_PLUGIN_HOSTS)
    if(_explicit_plugin_hosts AND NOT _explicit_plugin_hosts MATCHES "-NOTFOUND$")
      foreach(_plugin_host IN LISTS _explicit_plugin_hosts)
        _boilerplate_require_artifact_role(${_plugin_host} "HOST"
          "Plugin ${_plugin} execution placement")
        get_target_property(_hosted_plugins ${_plugin_host} BOILERPLATE_HOSTED_PLUGINS)
        if(NOT _plugin IN_LIST _hosted_plugins)
          message(FATAL_ERROR
            "Host ${_plugin_host} is registered for plugin ${_plugin}, but does not retain the HOST -> PLUGIN edge")
        endif()
        list(APPEND _plugin_hosts ${_plugin_host})
      endforeach()
    endif()
    get_target_property(_plugin_runtimes ${_plugin} BOILERPLATE_PLUGIN_RUNTIMES)
    get_target_property(_plugin_libraries ${_plugin} BOILERPLATE_PLUGIN_LIBRARIES)
    if(_plugin_runtimes AND NOT _plugin_runtimes MATCHES "-NOTFOUND$")
      list(APPEND _runtime_roots ${_plugin_runtimes})
    endif()
    if(_plugin_libraries AND NOT _plugin_libraries MATCHES "-NOTFOUND$")
      list(APPEND _libraries ${_plugin_libraries})
    endif()
  endforeach()
  if(_plugin_hosts)
    list(REMOVE_DUPLICATES _plugin_hosts)
  endif()
  set(_hosts ${_application_hosts} ${_plugin_hosts})
  if(_hosts)
    list(REMOVE_DUPLICATES _hosts)
  endif()
  if(_runtime_roots)
    list(REMOVE_DUPLICATES _runtime_roots)
  endif()
  if(_libraries)
    list(REMOVE_DUPLICATES _libraries)
  endif()
  _boilerplate_collect_runtime_graph(_runtimes _runtime_libraries ${_runtime_roots})
  list(APPEND _libraries ${_runtime_libraries})
  if(_libraries)
    set(_real_libraries)
    foreach(_library IN LISTS _libraries)
      if(NOT TARGET ${_library})
        message(FATAL_ERROR "Application ${target} library dependency is not a target: ${_library}")
      endif()
      _boilerplate_real_target(${_library} _real)
      get_target_property(_kind ${_real} TYPE)
      if(NOT _kind STREQUAL "SHARED_LIBRARY")
        message(FATAL_ERROR "Application ${target} LIBRARIES requires shared libraries: ${_library}")
      endif()
      list(APPEND _real_libraries ${_real})
    endforeach()
    list(REMOVE_DUPLICATES _real_libraries)
    set(_libraries ${_real_libraries})
  endif()

  set(_private_dir "${CMAKE_INSTALL_LIBDIR}/${target}")
  set(_plugin_dir "${_private_dir}/plugins")
  set(_resource_dir "${CMAKE_INSTALL_DATADIR}/${target}")
  set(_module_set "${target}_module_runtime_dependencies")
  set(_host_set "${target}_host_runtime_dependencies")
  set(_module_set_name)
  set(_host_set_name)
  if(NOT ARG_NO_RUNTIME_DEPENDENCIES)
    set(_module_set_name "${_module_set}")
    if(_hosts)
      set(_host_set_name "${_host_set}")
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      find_program(BOILERPLATE_PATCHELF patchelf REQUIRED)
    endif()
  endif()

  # The application image and private runtime closure live together. On ELF
  # this yields a simple $ORIGIN dependency scope; on Windows the generated
  # host adds this directory to the DLL search path before loading the app.
  _boilerplate_deploy_rpath(${target} "${_private_dir}" "${_private_dir}")
  _boilerplate_install_owned_target(${target} "${_private_dir}" "${_module_set_name}")
  foreach(_runtime IN LISTS _runtimes)
    _boilerplate_deploy_rpath(${_runtime} "${_private_dir}" "${_private_dir}")
    _boilerplate_install_owned_target(${_runtime} "${_private_dir}" "${_module_set_name}")
    list(APPEND ARG_RUNTIME_DIRS "$<TARGET_FILE_DIR:${_runtime}>")
  endforeach()
  foreach(_library IN LISTS _libraries)
    _boilerplate_deploy_rpath(${_library} "${_private_dir}" "${_private_dir}")
    _boilerplate_install_owned_target(${_library} "${_private_dir}" "${_module_set_name}")
    list(APPEND ARG_RUNTIME_DIRS "$<TARGET_FILE_DIR:${_library}>")
  endforeach()
  foreach(_plugin IN LISTS _plugins)
    _boilerplate_real_target(${_plugin} _real_plugin)
    _boilerplate_deploy_rpath(${_real_plugin} "${_plugin_dir}" "${_private_dir}")
    _boilerplate_install_owned_target(${_real_plugin} "${_plugin_dir}" "${_module_set_name}")
    list(APPEND ARG_RUNTIME_DIRS "$<TARGET_FILE_DIR:${_real_plugin}>")
  endforeach()
  foreach(_host IN LISTS _hosts)
    _boilerplate_real_target(${_host} _real_host)
    _boilerplate_deploy_rpath(${_real_host} "${CMAKE_INSTALL_BINDIR}" "${_private_dir}")
    _boilerplate_install_owned_target(${_real_host} "${CMAKE_INSTALL_BINDIR}" "${_host_set_name}")
  endforeach()

  if(NOT ARG_NO_RUNTIME_DEPENDENCIES)
    set(_pre "api-ms-.*" "ext-ms-.*")
    set(_post)
    if(WIN32)
      list(APPEND _post ".*[/\\\\][Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\][Ss][Yy][Ss][Tt][Ee][Mm]32[/\\\\].*")
    elseif(APPLE)
      list(APPEND _post "^/System/Library/" "^/usr/lib/")
    else()
      list(APPEND _pre "^linux-vdso" "^ld-linux" "^ld64\\." "^lib(c|m|pthread|dl|rt|resolv|util)\\.so(\\.|$)")
    endif()
    if(_hosts)
      install(RUNTIME_DEPENDENCY_SET "${_host_set}"
        DIRECTORIES ${ARG_RUNTIME_DIRS}
        PRE_EXCLUDE_REGEXES ${_pre} ${ARG_PRE_EXCLUDE_REGEXES}
        POST_EXCLUDE_REGEXES ${_post} ${ARG_POST_EXCLUDE_REGEXES}
        RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime
        LIBRARY DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime
        FRAMEWORK DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Runtime)
    endif()
    install(RUNTIME_DEPENDENCY_SET "${_module_set}"
      DIRECTORIES ${ARG_RUNTIME_DIRS}
      PRE_EXCLUDE_REGEXES ${_pre} ${ARG_PRE_EXCLUDE_REGEXES}
      POST_EXCLUDE_REGEXES ${_post} ${ARG_POST_EXCLUDE_REGEXES}
      RUNTIME DESTINATION "${_private_dir}" COMPONENT Runtime
      LIBRARY DESTINATION "${_private_dir}" COMPONENT Runtime
      FRAMEWORK DESTINATION "${_private_dir}" COMPONENT Runtime)

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      set(_fixup [=[
set(_boilerplate_new_files "${CMAKE_INSTALL_MANIFEST_FILES}")
list(REMOVE_DUPLICATES _boilerplate_new_files)
foreach(_file IN LISTS _boilerplate_new_files)
  get_filename_component(_parent "${_file}" DIRECTORY)
  if(_file MATCHES "[.]so([.][^/]*)?$" AND NOT IS_SYMLINK "$ENV{DESTDIR}${_file}")
    if(_parent STREQUAL "${CMAKE_INSTALL_PREFIX}/@_private_dir@" OR
       _parent STREQUAL "${CMAKE_INSTALL_PREFIX}/@CMAKE_INSTALL_BINDIR@")
      execute_process(COMMAND "@BOILERPLATE_PATCHELF@" --set-rpath "$ORIGIN" "$ENV{DESTDIR}${_file}"
        RESULT_VARIABLE _result ERROR_VARIABLE _error)
      if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Cannot make installed dependency relocatable: ${_file}: ${_error}")
      endif()
    endif()
  endif()
endforeach()
]=])
      string(CONFIGURE "${_fixup}" _fixup @ONLY)
      install(CODE "${_fixup}" COMPONENT Runtime)
    endif()
  endif()

  foreach(_dir IN LISTS _resource_dirs)
    get_filename_component(_dir "${_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT IS_DIRECTORY "${_dir}")
      message(FATAL_ERROR "Resource directory does not exist: ${_dir}")
    endif()
    install(DIRECTORY "${_dir}/" DESTINATION "${_resource_dir}" COMPONENT Runtime)
  endforeach()
  get_target_property(_shader_dirs ${target} BOILERPLATE_SHADER_DIRECTORIES)
  if(_shader_dirs)
    list(REMOVE_DUPLICATES _shader_dirs)
    foreach(_dir IN LISTS _shader_dirs)
      install(DIRECTORY "${_dir}/" DESTINATION "${_resource_dir}/shaders" COMPONENT Runtime
        FILES_MATCHING PATTERN "*.spv" PATTERN "*.dxil")
    endforeach()
  endif()
  set_target_properties(${target} PROPERTIES
    BOILERPLATE_INSTALL_PRIVATE_DIR "${_private_dir}"
    BOILERPLATE_INSTALL_PLUGIN_DIR "${_plugin_dir}"
    BOILERPLATE_INSTALL_RESOURCE_DIR "${_resource_dir}"
    BOILERPLATE_APPLICATION_DEPLOYMENT_HOSTS "${_hosts}")
endfunction()

# Compatibility path for the former executable-root application model. New
# projects should register an APPLICATION artifact and deploy from that root.
function(_boilerplate_install_legacy_application target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "NO_RUNTIME_DEPENDENCIES" ""
    "LIBRARIES;PLUGINS;RESOURCE_DIRS;RUNTIME_DIRS;PRE_EXCLUDE_REGEXES;POST_EXCLUDE_REGEXES")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT TARGET ${target})
    message(FATAL_ERROR "boilerplate_install_application(${target}): invalid arguments")
  endif()
  if(NOT BOILERPLATE_INSTALL)
    return()
  endif()
  get_target_property(_type ${target} TYPE)
  get_target_property(_done ${target} BOILERPLATE_DEPLOYMENT)
  if(NOT _type STREQUAL "EXECUTABLE" OR _done)
    message(FATAL_ERROR "Legacy deployment requires an executable registered only once: ${target}")
  endif()
  if(CMAKE_CROSSCOMPILING AND NOT ARG_NO_RUNTIME_DEPENDENCIES)
    message(FATAL_ERROR "Cross deployment requires NO_RUNTIME_DEPENDENCIES and explicit target-platform packaging")
  endif()
  _boilerplate_validate_relocatable_install_dirs()
  if(ARG_LIBRARIES)
    list(REMOVE_DUPLICATES ARG_LIBRARIES)
  endif()
  if(ARG_PLUGINS)
    list(REMOVE_DUPLICATES ARG_PLUGINS)
  endif()
  set_property(TARGET ${target} PROPERTY BOILERPLATE_DEPLOYMENT TRUE)
  set(_set "${target}_runtime_dependencies")
  set(_set_args)
  if(NOT ARG_NO_RUNTIME_DEPENDENCIES)
    set(_set_args RUNTIME_DEPENDENCY_SET "${_set}")
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      find_program(BOILERPLATE_PATCHELF patchelf REQUIRED)
    endif()
  endif()
  set(_plugins "${CMAKE_INSTALL_LIBDIR}/${target}/plugins")
  set(_resources "${CMAKE_INSTALL_DATADIR}/${target}")
  _boilerplate_deploy_rpath(${target} "${CMAKE_INSTALL_BINDIR}" "${CMAKE_INSTALL_LIBDIR}")
  install(TARGETS ${target} ${_set_args}
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime)
  foreach(_dependency IN LISTS ARG_LIBRARIES ARG_PLUGINS)
    if(NOT TARGET ${_dependency})
      message(FATAL_ERROR "Deployment dependency is not a target: ${_dependency}")
    endif()
    get_target_property(_real ${_dependency} ALIASED_TARGET)
    if(NOT _real)
      set(_real "${_dependency}")
    endif()
    get_target_property(_kind ${_real} TYPE)
    get_target_property(_imported ${_real} IMPORTED)
    if(_dependency IN_LIST ARG_PLUGINS)
      if(NOT _kind STREQUAL "MODULE_LIBRARY")
        message(FATAL_ERROR "PLUGINS requires MODULE libraries: ${_dependency}")
      endif()
      set(_destination "${_plugins}")
      set(_runtime_destination "${_plugins}")
    else()
      if(NOT _kind STREQUAL "SHARED_LIBRARY")
        message(FATAL_ERROR "LIBRARIES requires shared libraries: ${_dependency}")
      endif()
      set(_destination "${CMAKE_INSTALL_LIBDIR}")
      set(_runtime_destination "${CMAKE_INSTALL_BINDIR}")
    endif()
    if(_imported)
      install(IMPORTED_RUNTIME_ARTIFACTS ${_real} ${_set_args}
        RUNTIME DESTINATION "${_runtime_destination}" COMPONENT Runtime
        LIBRARY DESTINATION "${_destination}" COMPONENT Runtime)
    else()
      _boilerplate_deploy_rpath(${_real} "${_destination}" "${CMAKE_INSTALL_LIBDIR}")
      install(TARGETS ${_real} ${_set_args}
        RUNTIME DESTINATION "${_runtime_destination}" COMPONENT Runtime
        LIBRARY DESTINATION "${_destination}" COMPONENT Runtime NAMELINK_SKIP)
      add_dependencies(${target} ${_real})
    endif()
    list(APPEND ARG_RUNTIME_DIRS "$<TARGET_FILE_DIR:${_real}>")
  endforeach()
  if(NOT ARG_NO_RUNTIME_DEPENDENCIES)
    set(_pre "api-ms-.*" "ext-ms-.*")
    set(_post)
    if(WIN32)
      list(APPEND _post ".*[/\\\\][Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\][Ss][Yy][Ss][Tt][Ee][Mm]32[/\\\\].*")
    elseif(APPLE)
      list(APPEND _post "^/System/Library/" "^/usr/lib/")
    else()
      list(APPEND _pre "^linux-vdso" "^ld-linux" "^ld64\\." "^lib(c|m|pthread|dl|rt|resolv|util)\\.so(\\.|$)")
    endif()
    install(RUNTIME_DEPENDENCY_SET "${_set}"
      DIRECTORIES ${ARG_RUNTIME_DIRS}
      PRE_EXCLUDE_REGEXES ${_pre} ${ARG_PRE_EXCLUDE_REGEXES}
      POST_EXCLUDE_REGEXES ${_post} ${ARG_POST_EXCLUDE_REGEXES}
      RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime
      LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Runtime
      FRAMEWORK DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Runtime)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      set(_fixup [=[
set(_boilerplate_new_files "${CMAKE_INSTALL_MANIFEST_FILES}")
list(REMOVE_DUPLICATES _boilerplate_new_files)
foreach(_file IN LISTS _boilerplate_new_files)
  get_filename_component(_parent "${_file}" DIRECTORY)
  if(_parent STREQUAL "${CMAKE_INSTALL_PREFIX}/@CMAKE_INSTALL_LIBDIR@" AND
      _file MATCHES "[.]so([.][^/]*)?$" AND
      NOT IS_SYMLINK "$ENV{DESTDIR}${_file}")
    execute_process(COMMAND "@BOILERPLATE_PATCHELF@" --set-rpath "$ORIGIN" "$ENV{DESTDIR}${_file}"
      RESULT_VARIABLE _result ERROR_VARIABLE _error)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot make installed dependency relocatable: ${_file}: ${_error}")
    endif()
  endif()
endforeach()
]=])
      string(CONFIGURE "${_fixup}" _fixup @ONLY)
      install(CODE "${_fixup}" COMPONENT Runtime)
    endif()
  endif()
  foreach(_dir IN LISTS ARG_RESOURCE_DIRS)
    get_filename_component(_dir "${_dir}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT IS_DIRECTORY "${_dir}")
      message(FATAL_ERROR "Resource directory does not exist: ${_dir}")
    endif()
    install(DIRECTORY "${_dir}/" DESTINATION "${_resources}" COMPONENT Runtime)
  endforeach()
  get_target_property(_shader_dirs ${target} BOILERPLATE_SHADER_DIRECTORIES)
  if(_shader_dirs)
    list(REMOVE_DUPLICATES _shader_dirs)
    foreach(_dir IN LISTS _shader_dirs)
      install(DIRECTORY "${_dir}/" DESTINATION "${_resources}/shaders" COMPONENT Runtime
        FILES_MATCHING PATTERN "*.spv" PATTERN "*.dxil")
    endforeach()
  endif()
  set_target_properties(${target} PROPERTIES
    BOILERPLATE_INSTALL_PLUGIN_DIR "${_plugins}" BOILERPLATE_INSTALL_RESOURCE_DIR "${_resources}")
endfunction()

function(boilerplate_install_application target)
  if(NOT TARGET ${target})
    message(FATAL_ERROR "boilerplate_install_application(${target}): target does not exist")
  endif()
  boilerplate_get_artifact_role(${target} _role)
  if(_role STREQUAL "APPLICATION")
    _boilerplate_install_semantic_application(${target} ${ARGN})
  else()
    _boilerplate_install_legacy_application(${target} ${ARGN})
  endif()
endfunction()

# A HOST can also be a standalone deployment root (for example a plugin host).
# Its loading ABI is host-specific, but registered HOST -> PLUGIN edges are still
# semantic deployment edges: callers do not repeat the plugin/runtime closure.
function(boilerplate_install_host target)
  _boilerplate_require_artifact_role(${target} "HOST" "boilerplate_install_host")
  get_target_property(_plugins ${target} BOILERPLATE_HOSTED_PLUGINS)
  if(_plugins MATCHES "-NOTFOUND$")
    set(_plugins)
  endif()
  set(_libraries)
  foreach(_plugin IN LISTS _plugins)
    get_target_property(_plugin_runtimes ${_plugin} BOILERPLATE_PLUGIN_RUNTIMES)
    get_target_property(_plugin_libraries ${_plugin} BOILERPLATE_PLUGIN_LIBRARIES)
    if(_plugin_runtimes AND NOT _plugin_runtimes MATCHES "-NOTFOUND$")
      list(APPEND _libraries ${_plugin_runtimes})
    endif()
    if(_plugin_libraries AND NOT _plugin_libraries MATCHES "-NOTFOUND$")
      list(APPEND _libraries ${_plugin_libraries})
    endif()
  endforeach()
  if(_plugins)
    list(REMOVE_DUPLICATES _plugins)
  endif()
  if(_libraries)
    list(REMOVE_DUPLICATES _libraries)
  endif()
  set(_graph_args)
  if(_libraries)
    list(APPEND _graph_args LIBRARIES ${_libraries})
  endif()
  if(_plugins)
    list(APPEND _graph_args PLUGINS ${_plugins})
  endif()
  _boilerplate_install_legacy_application(${target} ${_graph_args} ${ARGN})
endfunction()
