# lib/cmake/LibraryPlatformSettings.cmake
if(WIN32)
  set(LIBRARY_PREFIX "")
  set(SHARED_LIB_SUFFIX ".dll")
  set(STATIC_LIB_SUFFIX ".lib")
  set(DEBUG_SUFFIX "_d")
elseif(APPLE)
  set(LIBRARY_PREFIX "lib")
  set(SHARED_LIB_SUFFIX ".dylib")
  set(STATIC_LIB_SUFFIX ".a")
  set(DEBUG_SUFFIX "_d")
else()
  set(LIBRARY_PREFIX "lib")
  set(SHARED_LIB_SUFFIX ".so")
  set(STATIC_LIB_SUFFIX ".a")
  set(DEBUG_SUFFIX "_d")
endif()
