name: CMake CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build lcov gcovr clang cmake doxygen graphviz nsis

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure (Release)
        run: cmake --preset vcpkg-release

      - name: Build
        run: cmake --build --preset build-vcpkg-release

      - name: Run tests
        run: ctest --preset test-vcpkg-release

      - name: Generate Coverage
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/vcpkg/*' --output-file coverage.info
          lcov --list coverage.info

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure (Release)
        run: cmake --preset vcpkg-release

      - name: Build
        run: cmake --build --preset build-vcpkg-release

      - name: Run tests
        run: ctest --preset test-vcpkg-release

      - name: Build Installer (NSIS)
        run: makensis setup.nsi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install ninja cmake doxygen graphviz

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure (Release)
        run: cmake --preset vcpkg-release

      - name: Build
        run: cmake --build --preset build-vcpkg-release

      - name: Run tests
        run: ctest --preset test-vcpkg-release
